@php
$mi=$mix->input_data??[];
$mr=$mix->result_data??[];
$mv=fn($key,$default=null)=>$mi[$key]??$mr[$key]??$default;
$mf=fn($raw,$digits=3)=>is_numeric($raw)?number_format((float)$raw,$digits,',','.'):(($raw===null||$raw==='')?'—':$raw);
$title=$combined?'PERENCANAAN CAMPURAN BETON NORMAL - GRADASI GABUNGAN':'PERENCANAAN CAMPURAN BETON NORMAL';
$construction=(int)($mi['construction_type']??2);
$slumpRows=[
 [0,'Pondasi beton bertulang (dinding dan pondasi telapak)',75,25],
 [1,'Pondasi telapak tanpa tulangan, pondasi tiang pancang, dan dinding bawah tanah',75,25],
 [2,'Balok dan dinding bertulang',100,25],[3,'Kolom bangunan',100,25],
 [4,'Perkerasan dan pelat lantai',75,25],[5,'Beton massa',50,25],
];
$sizes=[9.5,12.7,19,25,37.5,50,75,150];
$sizeIndex=array_search((float)($mi['max_size']??25),$sizes,true);if($sizeIndex===false)$sizeIndex=3;
$slump=(float)($mi['slump_design']??0);$waterRange=$slump<=50?0:($slump<=100?1:2);$airKey=(int)($mi['air_entrained']??0);
$waterRows=[
 ['Tanpa udara','25-50',[207,199,190,179,166,154,130,113],0,0],['Tanpa udara','75-100',[228,216,205,193,181,169,145,124],0,1],['Tanpa udara','150-175',[243,228,216,202,190,178,160,124],0,2],
 ['Dengan udara','25-50',[181,175,168,160,150,142,122,107],1,0],['Dengan udara','75-100',[202,193,184,175,165,157,133,119],1,1],['Dengan udara','150-175',[216,205,197,184,174,166,154,119],1,2],
];
$strengthRows=[[15,.79,.70],[20,.69,.60],[25,.61,.52],[30,.54,.45],[35,.47,.39],[40,.42,.35]];
$fcr=(float)($mr['fcr']??0);
$activeStrengths=[];foreach($strengthRows as $row){if($row[0]<=$fcr)$activeStrengths[0]=$row[0];if($row[0]>=$fcr){$activeStrengths[1]=$row[0];break;}}if(!$activeStrengths)$activeStrengths=[15];
$coarseReference=[[9.5,.50,.48,.46,.44],[12.7,.59,.57,.55,.53],[19,.66,.64,.62,.60],[25,.71,.69,.67,.65],[37.5,.75,.73,.71,.69],[50,.78,.76,.74,.72],[75,.82,.80,.78,.76],[150,.87,.85,.83,.81]];
$densityRows=[['Tanpa udara',[2280,2310,2345,2380,2410,2445,2490,2530],0],['Dengan udara',[2200,2230,2275,2315,2350,2375,2420,2470],1]];
$combinedRows=$mr['combined_gradation_rows']??[];
if($combined&&!$combinedRows){
 $fineRun=$latestRun('fine','sieve');$coarseRun=$latestRun('coarse','sieve');$fineCum=$fineRun?->results['observations'][0]['sieve_cumulative']??[];$coarseCum=$coarseRun?->results['observations'][0]['sieve_cumulative']??[];
 $limits=[40=>['r375'=>[100,100,100,100],'r190'=>[50,59,67,75],'r095'=>[36,44,52,60],'r475'=>[24,32,40,47],'r236'=>[18,25,31,38],'r118'=>[12,17,24,30],'r060'=>[7,12,17,23],'r030'=>[3,7,11,15],'r015'=>[0,2,4,6]],20=>['r190'=>[100,100,100,100],'r095'=>[45,55,65,75],'r475'=>[30,35,42,48],'r236'=>[23,28,35,42],'r118'=>[16,21,28,34],'r060'=>[9,14,21,27],'r030'=>[2,3,5,12],'r015'=>[0,0,2,4]],10=>['r095'=>[100,100,100,100],'r475'=>[30,45,60,75],'r236'=>[20,33,46,60],'r118'=>[16,26,37,46],'r060'=>[10,19,28,34],'r030'=>[4,8,14,20],'r015'=>[0,1,3,6]]];
 $max=(int)($mi['gradation_max_size']??20);$curve=(int)($mi['gradation_curve']??5);$fp=(float)($mr['combined_fine_percent']??$mi['combined_fine_percent']??50);$cp=100-$fp;
 foreach(($limits[$max]??[]) as $key=>$curves){$fine=in_array($key,['r375','r190','r095'],true)?100:(isset($fineCum[$key])?100-(float)$fineCum[$key]:null);$coarse=isset($coarseCum[$key])?100-(float)$coarseCum[$key]:(in_array($key,['r236','r118','r060','r030','r015'],true)?0:null);$target=$curve===5?array_sum($curves)/4:($curves[$curve-1]??null);$combinedValue=$fine===null||$coarse===null?null:$fine*$fp/100+$coarse*$cp/100;$combinedRows[$key]=['fine'=>$fine,'coarse'=>$coarse,'fine_weighted'=>$fine===null?null:$fine*$fp/100,'coarse_weighted'=>$coarse===null?null:$coarse*$cp/100,'combined'=>$combinedValue,'target'=>$target,'deviation'=>$combinedValue===null?null:abs($combinedValue-$target)];}
}
$sieveNames=['r375'=>['1 1/2 in','37,5'],'r190'=>['3/4 in','19,0'],'r095'=>['3/8 in','9,5'],'r475'=>['No.4','4,75'],'r236'=>['No.8','2,36'],'r118'=>['No.16','1,18'],'r060'=>['No.30','0,60'],'r030'=>['No.50','0,30'],'r015'=>['No.100','0,15']];
@endphp

<section class="page mix-appendix-page"><h2 class="mix-appendix-title">LAMPIRAN PERHITUNGAN {{$combined?'DESAIN CAMPURAN 2012 (GRADASI GABUNGAN)':'DESAIN CAMPURAN 2012'}}</h2><div class="mix-sheet">
 <div class="mix-sheet-head"><h3>{{$title}}</h3><div>SNI 7656:2012</div><p>Laboratorium Bahan dan Struktur</p></div>
 <table class="mix-meta"><tr><td><b>Proyek</b><br>{{$project->number}} - {{$project->name}}</td><td><b>Tanggal perencanaan</b><br>{{$mix->work_date?->format('d/m/Y')}}</td><td><b>Pemohon / perusahaan</b><br>{{$project->owner?:($project->contractor?:'-')}}</td><td><b>Nomor desain</b><br>{{$mix->number}}</td></tr></table>
 <div class="mix-bar"><span class="mix-no">1</span>Data umum bahan penyusun beton</div>
 <table class="mix-grid"><tr>@foreach([['cement_sg','Berat jenis semen',''],['coarse_sg','Berat jenis SSD agregat kasar',''],['coarse_absorption','Penyerapan agregat kasar','%'],['coarse_moisture','Kadar air agregat kasar','%']] as [$key,$label,$unit])<td><span class="mix-label">{{$label}}</span><span class="mix-input">{{$mf($mi[$key]??null)}}</span><span class="mix-unit">{{$unit}} - dari hasil uji laboratorium</span></td>@endforeach</tr><tr>@foreach([['coarse_density','Berat isi padat agregat kasar','kg/m³'],['fine_sg','Berat jenis SSD agregat halus',''],['fine_absorption','Penyerapan agregat halus','%'],['fine_moisture','Kadar air agregat halus','%']] as [$key,$label,$unit])<td><span class="mix-label">{{$label}}</span><span class="mix-input">{{$mf($mi[$key]??null)}}</span><span class="mix-unit">{{$unit}} - dari hasil uji laboratorium</span></td>@endforeach</tr><tr><td><span class="mix-label">Berat isi padat agregat halus</span><span class="mix-input">{{$mf($mi['fine_density']??null)}}</span><span class="mix-unit">kg/m³</span></td><td><span class="mix-label">Modulus kehalusan agregat halus</span><span class="mix-input">{{$mf($mi['fine_fm']??null)}}</span></td><td colspan="2"><div class="mix-help"><b>Sumber nilai:</b> seluruh karakteristik bahan berasal dari pemeriksaan material proyek yang telah disimpan.</div></td></tr></table>
 <div class="mix-bar"><span class="mix-no">2</span>Kuat tekan beton yang disyaratkan</div><table class="mix-grid"><tr><td><span class="mix-label">Kuat tekan f'c</span><span class="mix-input">{{$mf($mi['fc']??null)}}</span><span class="mix-unit">MPa</span></td><td><span class="mix-label">Umur pengujian</span><span class="mix-input">{{$mf($mi['age']??28,0)}}</span><span class="mix-unit">hari</span></td><td><span class="mix-label">Volume pekerjaan</span><span class="mix-input">{{$mf($mi['volume_work']??1)}}</span><span class="mix-unit">m³</span></td><td></td></tr></table>
 <div class="mix-bar"><span class="mix-no">3</span>Penetapan deviasi standar</div><table class="mix-grid"><tr><td><span class="mix-label">Deviasi standar terpilih</span><span class="mix-input">{{$mf($mi['sd']??null)}}</span><span class="mix-unit">MPa</span></td><td><span class="mix-label">Tambahan deviasi</span><span class="mix-input">{{$mf($mi['sd_additional']??0)}}</span><span class="mix-unit">MPa</span></td><td><span class="mix-label">Jumlah hasil uji</span><span class="mix-input">{{$mf($mi['test_count']??30,0)}}</span><span class="mix-unit">buah</span></td><td><span class="mix-label">Faktor pengali</span><span class="mix-input">{{$mf($mi['deviation_factor']??null)}}</span></td></tr></table><div class="mix-formula">Margin = (deviasi standar + tambahan deviasi) x faktor pengali.</div>
 <div class="mix-bar"><span class="mix-no">4</span>Margin</div><table class="mix-grid"><tr><td><span class="mix-label">Margin = (S + tambahan) x faktor</span><span class="mix-result">{{$mf($mr['margin']??null)}}</span><span class="mix-unit">MPa</span></td><td colspan="3"></td></tr></table>
 <div class="mix-bar"><span class="mix-no">5</span>Kuat tekan rata-rata yang ditargetkan</div><table class="mix-grid"><tr><td><span class="mix-label">f'cr = f'c + margin</span><span class="mix-result">{{$mf($mr['fcr']??null)}}</span><span class="mix-unit">MPa</span></td><td colspan="3"></td></tr></table>
 </div>{!!$footer()!!}</section>

<section class="page mix-appendix-page"><h2 class="mix-appendix-title">LAMPIRAN PERHITUNGAN {{$combined?'GRADASI GABUNGAN':'DESAIN CAMPURAN 2012'}} - SLUMP DAN AGREGAT</h2><div class="mix-sheet">
 <div class="mix-sheet-head"><h3>{{$title}}</h3><div>SNI 7656:2012 - {{$mix->number}}</div></div>
 <div class="mix-bar"><span class="mix-no">6</span>Penentuan nilai slump - Tabel 1 SNI 7656:2012</div><table class="mix-table"><tr><th>Pilih</th><th>Tipe konstruksi</th><th>Maksimum (mm)</th><th>Minimum (mm)</th></tr>@foreach($slumpRows as [$id,$label,$max,$min])<tr class="{{$construction===$id?'selected':''}}"><td class="center">{{$construction===$id?'X':''}}</td><td>{{$label}}</td><td class="center">{{$max}}</td><td class="center">{{$min}}</td></tr>@endforeach<tr class="{{$construction===6?'selected':''}}"><td class="center">{{$construction===6?'X':''}}</td><td><b>Lainnya / kebutuhan khusus</b></td><td class="center">{{$construction===6?$mf($mi['slump_max']??null,0):'Manual'}}</td><td class="center">{{$construction===6?$mf($mi['slump_min']??null,0):'Manual'}}</td></tr></table>
 <table class="mix-grid"><tr><td><span class="mix-label">Slump minimum</span><span class="mix-input">{{$mf($mi['slump_min']??null)}}</span><span class="mix-unit">mm</span></td><td><span class="mix-label">Slump maksimum</span><span class="mix-input">{{$mf($mi['slump_max']??null)}}</span><span class="mix-unit">mm</span></td><td><span class="mix-label">Penentuan nilai slump awal</span><span class="mix-input">{{$mf($mi['slump_design']??null)}}</span><span class="mix-unit">mm</span></td><td><div class="mix-help">Nilai slump rencana berada di dalam batas tipe konstruksi terpilih.</div></td></tr></table>
 <div class="mix-bar"><span class="mix-no">7</span>Penentuan agregat maksimum - Tabel 1 SNI 7656:2012</div><table class="mix-table"><tr><th>No.</th><th>Ketentuan</th><th>Data (mm)</th><th>Perhitungan (mm)</th></tr><tr><td>1</td><td>1/5 ukuran terkecil cetakan/bekisting</td><td class="selected">{{$mf($mi['smallest_form_dimension']??null)}}</td><td class="center">{{$mf(isset($mi['smallest_form_dimension'])?$mi['smallest_form_dimension']/5:null)}}</td></tr><tr><td>2</td><td>1/3 tebal pelat lantai</td><td class="selected">{{$mf($mi['slab_thickness']??null)}}</td><td class="center">{{$mf(isset($mi['slab_thickness'])?$mi['slab_thickness']/3:null)}}</td></tr><tr><td>3</td><td>3/4 jarak minimum tulangan</td><td class="selected">{{$mf($mi['clear_rebar_spacing']??null)}}</td><td class="center">{{$mf(isset($mi['clear_rebar_spacing'])?$mi['clear_rebar_spacing']*.75:null)}}</td></tr></table><table class="mix-grid"><tr><td><span class="mix-label">Nilai agregat maksimum yang digunakan</span><span class="mix-input">{{$mf($mi['max_size']??null)}}</span><span class="mix-unit">mm</span></td><td colspan="3"><div class="mix-formula">Sistem mengambil ukuran standar terbesar yang tidak melebihi seluruh batas struktur dan hasil uji kerikil.</div></td></tr></table>
 </div>{!!$footer()!!}</section>

<section class="page mix-appendix-page"><h2 class="mix-appendix-title">LAMPIRAN PERHITUNGAN {{$combined?'GRADASI GABUNGAN':'DESAIN CAMPURAN 2012'}} - LANJUTAN</h2><div class="mix-sheet">
 <div class="mix-sheet-head"><h3>{{$title}}</h3><div>SNI 7656:2012 - {{$mix->number}}</div></div>
 <div class="mix-bar"><span class="mix-no">8</span>Perkiraan air pencampur dan kadar udara - Tabel 3 SNI 7656:2012</div><table class="mix-table"><tr><th rowspan="2">Jenis beton</th><th rowspan="2">Slump (mm)</th><th colspan="8">Kebutuhan air (kg/m³) menurut ukuran maksimum agregat (mm)</th></tr><tr>@foreach($sizes as $size)<th>{{$size}}</th>@endforeach</tr>@foreach($waterRows as [$airLabel,$rangeLabel,$values,$rowAir,$rowRange])<tr><td>{{$airLabel}}</td><td>{{$rangeLabel}}</td>@foreach($values as $index=>$waterValue)<td class="center {{$rowAir===$airKey&&$rowRange===$waterRange&&$index===$sizeIndex?'mix-active':''}}">{{$waterValue}}</td>@endforeach</tr>@endforeach</table><table class="mix-grid"><tr><td><span class="mix-label">Jenis beton</span><span class="mix-input">{{$airKey?'Dengan kandungan udara':'Tanpa kandungan udara'}}</span></td><td><span class="mix-label">Kebutuhan air dari tabel</span><span class="mix-input">{{$mf($mi['water']??null)}}</span><span class="mix-unit">kg/m³</span></td><td><span class="mix-label">Kadar udara dari tabel</span><span class="mix-input">{{$mf($mi['air_content']??null)}}</span><span class="mix-unit">%</span></td><td><div class="mix-help">Sel hijau menunjukkan nilai tabel yang digunakan.</div></td></tr></table>
 <div class="mix-bar"><span class="mix-no">9</span>Penetapan rasio air-semen (FAS)</div><table class="mix-table"><tr><th>Kuat tekan rata-rata sasaran (MPa)</th><th>Tanpa udara</th><th>Dengan udara</th><th>Keterangan</th></tr>@foreach($strengthRows as [$strength,$normal,$air])<tr class="{{in_array($strength,$activeStrengths,true)?'selected':''}}"><td class="center">{{$strength}}</td><td class="center">{{$normal}}</td><td class="center">{{$air}}</td><td class="center">{{in_array($strength,$activeStrengths,true)?(count($activeStrengths)===1?'Sesuai':($strength===$activeStrengths[0]?'Batas bawah':'Batas atas')):'—'}}</td></tr>@endforeach</table><table class="mix-grid"><tr><td><span class="mix-label">FAS hasil tabel/interpolasi</span><span class="mix-input">{{$mf($mr['wc_ratio_calculated']??$mi['wc_ratio']??null,4)}}</span></td><td colspan="3"><div class="mix-formula">FAS ditentukan dari kuat tekan rata-rata sasaran dengan interpolasi linier pada tabel.</div></td></tr></table>
 <div class="mix-bar"><span class="mix-no">10</span>Kadar semen</div><table class="mix-grid"><tr><td><span class="mix-label">Semen = air / FAS</span><span class="mix-result">{{$mf($mr['cement']??null)}}</span><span class="mix-unit">kg/m³</span></td><td colspan="3"></td></tr></table>
 <div class="mix-bar"><span class="mix-no">11</span>{{$combined?'Penentuan Pasir dan Kerikil dari Gradasi Gabungan':'Penetapan jumlah agregat kasar'}}</div>
 @if($combined)<div class="mix-summary"><table><tr><td>Pasir optimum<br><strong>{{$mf($mr['combined_fine_percent']??null,1)}}%</strong></td><td>Kerikil optimum<br><strong>{{$mf($mr['combined_coarse_percent']??null,1)}}%</strong></td><td>Total<br><strong>100,0%</strong></td><td>Deviasi rata-rata<br><strong>{{$mf($mr['combined_deviation']??null,4)}}</strong></td></tr></table></div><table class="mix-table"><tr><th>Saringan</th><th>mm</th><th>Lolos pasir</th><th>Lolos kerikil</th><th>Bobot pasir</th><th>Bobot kerikil</th><th>Massa lolos gabungan</th><th>Sasaran</th><th>Deviasi</th></tr>@foreach($combinedRows as $key=>$row)<tr><td>{{$sieveNames[$key][0]??$key}}</td><td class="center">{{$sieveNames[$key][1]??'—'}}</td><td class="right">{{$mf($row['fine']??null,2)}}</td><td class="right">{{$mf($row['coarse']??null,2)}}</td><td class="right">{{$mf($row['fine_weighted']??null,2)}}</td><td class="right">{{$mf($row['coarse_weighted']??null,2)}}</td><td class="right selected">{{$mf($row['combined']??null,2)}}</td><td class="right">{{$mf($row['target']??null,2)}}</td><td class="right">{{$mf($row['deviation']??null,2)}}</td></tr>@endforeach</table><div class="mix-formula">Komposisi tersimpan digunakan sebagai snapshot laporan: pasir {{$mf($mr['combined_fine_percent']??null,1)}}% dan kerikil {{$mf($mr['combined_coarse_percent']??null,1)}}%.</div>
 @else<table class="mix-table"><tr><th rowspan="2">Ukuran maksimum (mm)</th><th colspan="4">Volume agregat kasar per satuan volume beton untuk MHB pasir</th></tr><tr><th>2,4</th><th>2,6</th><th>2,8</th><th>3,0</th></tr>@foreach($coarseReference as $row)<tr class="{{(float)$row[0]===(float)($mi['max_size']??0)?'selected':''}}"><td class="center">{{$row[0]}}</td>@foreach(array_slice($row,1) as $ref)<td class="center">{{$ref}}</td>@endforeach</tr>@endforeach</table><table class="mix-grid"><tr><td><span class="mix-label">Volume agregat kasar hasil interpolasi</span><span class="mix-result">{{$mf($mr['coarse_ratio']??null,4)}}</span></td><td><span class="mix-label">Massa agregat kasar SSD</span><span class="mix-result">{{$mf($mr['coarse_ssd']??null)}}</span><span class="mix-unit">kg/m³</span></td><td colspan="2"><div class="mix-formula">Volume tabel disesuaikan terhadap modulus kehalusan pasir, lalu dikalikan berat isi padat agregat kasar.</div></td></tr></table>@endif
 </div>{!!$footer()!!}</section>

<section class="page mix-appendix-page"><h2 class="mix-appendix-title">LAMPIRAN PERHITUNGAN {{$combined?'GRADASI GABUNGAN':'DESAIN CAMPURAN 2012'}} - KOMPOSISI AKHIR</h2><div class="mix-sheet">
 <div class="mix-sheet-head"><h3>{{$title}}</h3><div>SNI 7656:2012 - {{$mix->number}}</div></div>
 <div class="mix-bar"><span class="mix-no">12</span>Perkiraan awal berat beton segar</div><table class="mix-table"><tr><th>Jenis beton</th>@foreach($sizes as $size)<th>{{$size}} mm</th>@endforeach</tr>@foreach($densityRows as [$densityLabel,$values,$densityAir])<tr><td>{{$densityLabel}}</td>@foreach($values as $index=>$density)<td class="center {{$densityAir===$airKey&&$index===$sizeIndex?'mix-active':''}}">{{$density}}</td>@endforeach</tr>@endforeach</table><table class="mix-grid"><tr><td><span class="mix-label">Perkiraan berat beton segar</span><span class="mix-input">{{$mf($mi['fresh_density']??null)}}</span><span class="mix-unit">kg/m³</span></td><td><span class="mix-label">Total berat agregat tersedia</span><span class="mix-result">{{$mf($mr['aggregate_mass_available']??null)}}</span><span class="mix-unit">kg/m³</span></td><td><span class="mix-label">{{$combined?'Berat pasir hasil gradasi':'Agregat halus (metode massa)'}}</span><span class="mix-result">{{$mf($mr['fine_mass_method']??null)}}</span><span class="mix-unit">kg/m³</span></td><td></td></tr></table>
 <div class="mix-bar"><span class="mix-no">13</span>{{$combined?'Volume absolut agregat dari hasil gradasi':'Agregat halus dengan metode volume absolut'}}</div><table class="mix-grid"><tr>@foreach([['vol_water','Volume air','m³'],['vol_cement','Volume semen','m³'],['vol_coarse','Volume agregat kasar','m³'],['vol_air','Volume udara','m³']] as [$key,$label,$unit])<td><span class="mix-label">{{$label}}</span><span class="mix-result">{{$mf($mr[$key]??null,4)}}</span><span class="mix-unit">{{$unit}}</span></td>@endforeach</tr><tr><td><span class="mix-label">Volume agregat halus</span><span class="mix-result">{{$mf($mr['vol_fine']??null,4)}}</span><span class="mix-unit">m³</span></td><td><span class="mix-label">Massa agregat halus SSD</span><span class="mix-result">{{$mf($mr['fine_ssd']??null)}}</span><span class="mix-unit">kg/m³</span></td><td colspan="2"><div class="mix-formula">Volume bahan dihitung dari massa dan berat jenis masing-masing bahan.</div></td></tr></table>
 <div class="mix-bar"><span class="mix-no">14</span>Koreksi kadar air agregat</div><table class="mix-grid"><tr>@foreach([['fine_free_water','Air bebas agregat halus'],['coarse_free_water','Air bebas agregat kasar'],['fine_field','Agregat halus kondisi lapangan'],['coarse_field','Agregat kasar kondisi lapangan']] as [$key,$label])<td><span class="mix-label">{{$label}}</span><span class="mix-result">{{$mf($mr[$key]??null)}}</span><span class="mix-unit">kg/m³</span></td>@endforeach</tr><tr><td><span class="mix-label">Air yang ditambahkan</span><span class="mix-result">{{$mf($mr['water_added']??null)}}</span><span class="mix-unit">kg/m³</span></td><td><span class="mix-label">Total massa beton</span><span class="mix-result">{{$mf($mr['total_fresh_mass']??null)}}</span><span class="mix-unit">kg/m³</span></td><td colspan="2"></td></tr></table>
 <div class="mix-bar"><span class="mix-no">15</span>Komposisi akhir dan kebutuhan campuran percobaan</div><div class="mix-help"><b>Dasar volume trial mix:</b> adukan dihitung dari volume geometris seluruh benda uji silinder dalam satu kali pencampuran. Persentase kelebihan ditambahkan setelah volume seluruh silinder diperoleh.</div><table class="mix-grid"><tr><td><span class="mix-label">Diameter silinder</span><span class="mix-input">{{$mf($mi['trial_cylinder_diameter_mm']??null)}}</span><span class="mix-unit">mm</span></td><td><span class="mix-label">Tinggi silinder</span><span class="mix-input">{{$mf($mi['trial_cylinder_height_mm']??null)}}</span><span class="mix-unit">mm</span></td><td><span class="mix-label">Jumlah silinder satu batch</span><span class="mix-input">{{$mf($mi['trial_cylinder_count']??null,0)}}</span><span class="mix-unit">buah</span></td><td><span class="mix-label">Kelebihan / kehilangan</span><span class="mix-input">{{$mf($mi['waste']??null)}}</span><span class="mix-unit">%</span></td></tr><tr><td><span class="mix-label">Volume satu silinder</span><span class="mix-result">{{$mf($mr['trial_single_cylinder_volume_liter']??null)}}</span><span class="mix-unit">liter</span></td><td><span class="mix-label">Total volume seluruh silinder</span><span class="mix-input">{{$mf($mr['trial_volume_liter']??$mi['trial_volume_liter']??null)}}</span><span class="mix-unit">liter</span></td><td><span class="mix-label">Volume adukan setelah kelebihan</span><span class="mix-result">{{$mf($mr['trial_batch_volume_liter']??null)}}</span><span class="mix-unit">liter</span></td><td></td></tr></table>
 <table class="mix-table mix-composition"><tr><th>Bahan</th><th>Komposisi lapangan (kg/m³)</th><th>Perbandingan</th><th>Campuran percobaan (kg)</th><th>Per 1 zak semen (kg)</th></tr><tr><td>Semen</td><td>{{$mf($mr['cement']??null)}}</td><td>{{$mf($mr['ratio_cement']??1,4)}}</td><td>{{$mf($mr['trial_cement']??null)}}</td><td>50,000</td></tr><tr><td>Agregat halus</td><td>{{$mf($mr['fine_field']??null)}}</td><td>{{$mf($mr['ratio_fine']??null,4)}}</td><td>{{$mf($mr['trial_fine']??null)}}</td><td>{{$mf($mr['fine_per_sack']??null)}}</td></tr><tr><td>Agregat kasar</td><td>{{$mf($mr['coarse_field']??null)}}</td><td>{{$mf($mr['ratio_coarse']??null,4)}}</td><td>{{$mf($mr['trial_coarse']??null)}}</td><td>{{$mf($mr['coarse_per_sack']??null)}}</td></tr><tr><td>Air</td><td>{{$mf($mr['water_added']??null)}}</td><td>{{$mf($mr['ratio_water']??null,4)}}</td><td>{{$mf($mr['trial_water']??null)}}</td><td>{{$mf($mr['water_per_sack']??null)}}</td></tr></table><div class="mix-formula">Perbandingan akhir semen : pasir : kerikil : air = 1 : {{$mf($mr['ratio_fine']??null,4)}} : {{$mf($mr['ratio_coarse']??null,4)}} : {{$mf($mr['ratio_water']??null,4)}}.</div>
 </div>{!!$footer()!!}</section>
