@extends('layouts.app')
@section('title','Manajemen Pengguna')
@section('subtitle','Akun, peran, status, dan hak akses setiap menu')
@section('content')
<div class="d-flex justify-content-between align-items-start mb-3"><div><h3 class="fw-bold">Manajemen Pengguna</h3><p class="text-secondary">Hak akses dilindungi pada sidebar dan route. URL langsung tanpa izin menghasilkan 403.</p></div>@if(auth()->user()->hasPermission('users.create'))<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newUser"><i class="bi bi-person-plus me-2"></i>Tambah Pengguna</button>@endif</div>
<div class="row g-3">@foreach($users as $user)<div class="col-xl-6"><div class="card p-4 h-100"><div class="d-flex justify-content-between"><div><h5 class="fw-bold mb-1">{{$user->name}}</h5><div class="text-secondary">{{$user->username}} · {{$user->email}}</div></div><div><span class="badge text-bg-{{in_array($user->role,['admin','administrator'])?'dark':($user->is_active?'success':'secondary')}}">{{in_array($user->role,['admin','administrator'])?'Administrator':($user->is_active?'Aktif':'Nonaktif')}}</span></div></div><hr><div class="row small"><div class="col-6"><b>Role:</b> {{$user->role}}</div><div class="col-6"><b>Instansi:</b> {{$user->institution?:'-'}}</div></div><div class="mt-3 d-flex gap-2">@if(auth()->user()->hasPermission('users.edit'))<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editUser{{$user->id}}"><i class="bi bi-shield-check me-1"></i>Atur Akun & Izin</button>@endif @if(auth()->user()->hasPermission('users.delete')&&!in_array($user->role,['admin','administrator'])&&$user->id!==auth()->id())<form method="post" action="{{route('accounts.destroy',$user)}}" onsubmit="return confirm('Hapus akun ini?')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form>@endif</div></div></div>@endforeach</div>

@if(auth()->user()->hasPermission('users.create'))<div class="modal fade" id="newUser"><div class="modal-dialog modal-xl"><form method="post" action="{{route('accounts.store')}}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">Tambah Pengguna</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('accounts.partials.form',['user'=>null])</div><div class="modal-footer"><button class="btn btn-primary">Simpan Pengguna</button></div></form></div></div>@endif
@foreach($users as $user) @if(auth()->user()->hasPermission('users.edit'))<div class="modal fade" id="editUser{{$user->id}}"><div class="modal-dialog modal-xl"><form method="post" action="{{route('accounts.update',$user)}}" class="modal-content">@csrf @method('patch')<div class="modal-header"><h5 class="modal-title">Atur {{$user->name}}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('accounts.partials.form',['user'=>$user])</div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>@endif @endforeach
@endsection
