@extends('layouts.app')
@section('title','Data Proyek')
@section('subtitle','Kelola identitas dan masa pekerjaan')
@section('content')
@php $projectFields=[['number','Nomor proyek','text',1],['name','Nama proyek','text',1],['work_package','Paket pekerjaan','text',0],['owner','Pemilik / perusahaan pemohon','text',0],['contractor','Kontraktor','text',0],['consultant','Konsultan','text',0],['location','Lokasi proyek','text',0],['contract_number','Nomor kontrak','text',0],['contract_date','Tanggal kontrak','date',0],['start_date','Tanggal mulai','date',0],['end_date','Tanggal selesai','date',0],['person_in_charge','Penanggung jawab','text',0],['supervisor','Nama pengawas','text',0],['concrete_grade','Mutu beton rencana','text',0],['construction_type','Jenis konstruksi','text',0],['environment','Kondisi lingkungan','text',0]]; @endphp
<div class="d-flex justify-content-between mb-3"><div><h3 class="fw-bold">Daftar Proyek</h3><p class="text-secondary">Satu proyek dapat memiliki beberapa sumber material dan desain campuran.</p></div><button class="btn btn-primary align-self-start" data-bs-toggle="modal" data-bs-target="#add"><i class="bi bi-plus-lg me-2"></i>Tambah Proyek</button></div>
<div class="card p-3"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Nomor</th><th>Proyek</th><th>Pemilik / Kontraktor</th><th>Mutu</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
@forelse($projects as $p)
<tr><td><b>{{$p->number}}</b></td><td>{{$p->name}}<div class="small text-secondary">{{$p->location}}</div></td><td>{{$p->owner??'—'}}<div class="small text-secondary">{{$p->contractor}}</div></td><td>{{$p->concrete_grade??'—'}}</td><td><span class="badge {{$p->status==='aktif'?'text-bg-success':'text-bg-secondary'}}">{{ucfirst($p->status)}}</span></td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editProject{{$p->id}}" title="Ubah proyek" aria-label="Ubah proyek"><i class="bi bi-pencil-square"></i></button><form method="post" action="{{route('projects.destroy',$p)}}" onsubmit="return confirm('Arsipkan proyek ini?')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger" title="Arsipkan" aria-label="Arsipkan proyek"><i class="bi bi-trash"></i></button></form></div></td></tr>
@empty<tr><td colspan="6" class="text-center text-secondary py-5">Belum ada proyek. Tambahkan proyek pertama.</td></tr>@endforelse
</tbody></table></div></div>

<div class="modal fade" id="add"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form method="post" action="{{route('projects.store')}}" class="modal-content">@csrf
<div class="modal-header"><h5 class="modal-title">Proyek Baru</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
@foreach($projectFields as $f)<div class="col-md-6"><label class="form-label">{{$f[1]}}</label><input class="form-control" type="{{$f[2]}}" name="{{$f[0]}}" {{$f[3]?'required':''}}></div>@endforeach
<div class="col-12"><div class="border rounded-3 p-3 bg-light"><label class="form-label d-block mb-2">Desain campuran yang dimasukkan ke laporan *</label><div class="d-flex flex-wrap gap-4"><div class="form-check"><input class="form-check-input" type="checkbox" name="report_include_mix_design_2012" value="1" id="addReportMix2012" checked><label class="form-check-label" for="addReportMix2012">Desain Campuran 2012</label></div><div class="form-check"><input class="form-check-input" type="checkbox" name="report_include_mix_design_2012_combined" value="1" id="addReportMixCombined" checked><label class="form-check-label" for="addReportMixCombined">Desain Campuran 2012 (Gradasi Gabungan)</label></div></div><div class="form-text">Pilih sedikitnya satu. Pilihan ini hanya mengatur isi laporan dan tidak membatasi menu analisis.</div></div></div>
<div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="aktif">Aktif</option><option value="selesai">Selesai</option></select></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes"></textarea></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Proyek</button></div></form></div></div>

@foreach($projects as $p)
<div class="modal fade" id="editProject{{$p->id}}"><div class="modal-dialog modal-xl modal-dialog-scrollable"><form method="post" action="{{route('projects.update',$p)}}" class="modal-content">@csrf @method('put')
<div class="modal-header"><h5 class="modal-title">Ubah Proyek — {{$p->number}}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><div class="modal-body"><div class="row g-3">
@foreach($projectFields as $f) @php $field=$f[0]; $fieldValue=$f[2]==='date' ? optional($p->$field)->format('Y-m-d') : $p->$field; @endphp <div class="col-md-6"><label class="form-label">{{$f[1]}}</label><input class="form-control" type="{{$f[2]}}" name="{{$field}}" value="{{$fieldValue}}" {{$f[3]?'required':''}}></div>@endforeach
<div class="col-12"><div class="border rounded-3 p-3 bg-light"><label class="form-label d-block mb-2">Desain campuran yang dimasukkan ke laporan *</label><div class="d-flex flex-wrap gap-4"><div class="form-check"><input class="form-check-input" type="checkbox" name="report_include_mix_design_2012" value="1" id="editReportMix2012{{$p->id}}" @checked(old('report_include_mix_design_2012',$p->report_include_mix_design_2012))><label class="form-check-label" for="editReportMix2012{{$p->id}}">Desain Campuran 2012</label></div><div class="form-check"><input class="form-check-input" type="checkbox" name="report_include_mix_design_2012_combined" value="1" id="editReportMixCombined{{$p->id}}" @checked(old('report_include_mix_design_2012_combined',$p->report_include_mix_design_2012_combined))><label class="form-check-label" for="editReportMixCombined{{$p->id}}">Desain Campuran 2012 (Gradasi Gabungan)</label></div></div><div class="form-text">Pilih sedikitnya satu. Pilihan ini hanya mengatur isi laporan dan tidak membatasi menu analisis.</div></div></div>
<div class="col-md-6"><label class="form-label">Status</label><select class="form-select" name="status"><option value="aktif" @selected($p->status==='aktif')>Aktif</option><option value="selesai" @selected($p->status==='selesai')>Selesai</option></select></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes">{{$p->notes}}</textarea></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan Perubahan</button></div></form></div></div>
@endforeach
@endsection
@php($requestedEditProject=$projects->firstWhere('id',(int)request('edit')))
@if($requestedEditProject)
@push('scripts')
<script>
document.addEventListener('DOMContentLoaded',()=>new bootstrap.Modal(document.getElementById('editProject{{$requestedEditProject->id}}')).show());
</script>
@endpush
@endif
