@php($p=$project)
<section class="project-form-section"><h6 class="fw-bold">1. Data Umum Pekerjaan</h6><div class="row g-3">
<div class="col-md-4"><label class="form-label">Nomor proyek/laporan</label><input class="form-control" name="number" value="{{old('number',$p?->number)}}" placeholder="Otomatis jika dikosongkan" @if($p) readonly @endif></div>
<div class="col-md-8"><label class="form-label">Nama proyek/pekerjaan *</label><input class="form-control" name="name" value="{{old('name',$p?->name)}}" required></div>
@foreach([['work_package','Paket pekerjaan'],['owner','Pemilik pekerjaan'],['contractor','Kontraktor pelaksana'],['consultant','Konsultan'],['contract_number','Nomor kontrak'],['concrete_grade','Mutu beton rencana'],['construction_type','Jenis konstruksi']] as [$field,$label])<div class="col-md-6"><label class="form-label">{{$label}}</label><input class="form-control" name="{{$field}}" value="{{old($field,$p?->$field)}}"></div>@endforeach
<div class="col-md-4"><label class="form-label">Tanggal kontrak</label><input type="date" class="form-control" name="contract_date" value="{{old('contract_date',$p?->contract_date?->format('Y-m-d'))}}"></div><div class="col-md-4"><label class="form-label">Jangka waktu mulai</label><input type="date" class="form-control" name="start_date" value="{{old('start_date',$p?->start_date?->format('Y-m-d'))}}"></div><div class="col-md-4"><label class="form-label">Jangka waktu selesai</label><input type="date" class="form-control" name="end_date" value="{{old('end_date',$p?->end_date?->format('Y-m-d'))}}"></div>
</div></section>
<section class="project-form-section"><h6 class="fw-bold">2. Lokasi dan Peta</h6><p class="small text-secondary">Klik peta atau geser marker. Koordinat juga dapat diketik manual tanpa API Google berbayar.</p><div class="row g-3">
<div class="col-md-6"><label class="form-label">Keterangan lokasi</label><textarea class="form-control" name="location_description" rows="3">{{old('location_description',$p?->location_description)}}</textarea></div><div class="col-md-6"><label class="form-label">Alamat lokasi proyek</label><textarea class="form-control" name="location_address" rows="3">{{old('location_address',$p?->location_address?:$p?->location)}}</textarea><input type="hidden" name="location" value="{{old('location',$p?->location)}}"></div>
<div class="col-md-4"><label class="form-label">Latitude</label><input type="number" step="0.0000001" class="form-control" name="latitude" value="{{old('latitude',$p?->latitude)}}"></div><div class="col-md-4"><label class="form-label">Longitude</label><input type="number" step="0.0000001" class="form-control" name="longitude" value="{{old('longitude',$p?->longitude)}}"></div><div class="col-md-4"><label class="form-label">Format koordinat laporan</label><select class="form-select" name="coordinate_format"><option value="decimal" @selected(old('coordinate_format',$p?->coordinate_format)==='decimal')>Decimal Degrees</option><option value="dms" @selected(old('coordinate_format',$p?->coordinate_format)==='dms')>DMS (Derajat Menit Detik)</option></select></div>
<div class="col-12"><div id="{{$mapId}}" class="project-map"></div></div>
<div class="col-md-6"><label class="form-label">Upload gambar peta/site map</label><input type="file" class="form-control" name="map_image" accept="image/*">@if($p?->map_image)<a class="small" target="_blank" href="{{asset('storage/'.$p->map_image)}}">Lihat peta tersimpan</a>@endif</div><div class="col-md-6"><label class="form-label">Caption/keterangan peta</label><input class="form-control" name="map_caption" value="{{old('map_caption',$p?->map_caption)}}" placeholder="Gambar 1. Peta Lokasi Pekerjaan"></div>
</div></section>
