<!doctype html>
<html lang="id">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Layanan Pengujian Laboratorium Beton</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" rel="stylesheet">
<style>
:root{--navy:#09283a;--teal:#087f74;--mint:#e6f5f1;--gold:#eba83a;--ink:#18323e}
body{font-family:Inter,system-ui,sans-serif;color:var(--ink);background:#f5f8f8}.navbar{background:#fff;border-bottom:1px solid #dce7e7}.brand-mark{width:42px;height:42px;background:var(--teal);color:#fff;border-radius:12px;display:grid;place-items:center;font-size:22px}
.hero{background:linear-gradient(120deg,#082638 0%,#0a5e5b 70%,#078477 100%);color:#fff;padding:78px 0;position:relative;overflow:hidden}.hero:after{content:"";position:absolute;width:360px;height:360px;border:70px solid #ffffff12;border-radius:50%;right:-80px;top:-100px}.hero .eyebrow{color:#8ee3d7;letter-spacing:.12em;font-weight:700;font-size:.76rem}.hero h1{font-size:clamp(2.2rem,5vw,4.2rem);line-height:1.05}.hero-card{background:#ffffff14;border:1px solid #ffffff2b;border-radius:18px;padding:24px;backdrop-filter:blur(8px)}
.section{padding:65px 0}.service-card{height:100%;background:#fff;border:0;border-radius:16px;box-shadow:0 10px 35px #17333e10;padding:25px}.service-icon{width:50px;height:50px;border-radius:13px;background:var(--mint);color:var(--teal);display:grid;place-items:center;font-size:23px}.step{display:flex;gap:15px}.step-number{min-width:38px;height:38px;background:var(--teal);color:#fff;border-radius:50%;display:grid;place-items:center;font-weight:700}.requirement{background:#fff;border-left:4px solid var(--gold);border-radius:10px;padding:14px 16px}.cta{background:var(--navy);color:#fff;border-radius:22px;padding:42px}.footer{background:#061d2a;color:#bcd0d6;padding:35px 0}
</style>
</head>
<body>
<nav class="navbar navbar-expand-lg sticky-top"><div class="container py-2"><a class="navbar-brand d-flex gap-3 align-items-center" href="{{route('lab-services.brochure')}}"><span class="brand-mark"><i class="bi bi-buildings"></i></span><span><b>LABORATORIUM BETON</b><small class="d-block text-secondary">Universitas Muhammadiyah Buton</small></span></a><div class="ms-auto d-flex gap-2"><a href="{{route('login')}}" class="btn btn-outline-secondary">Masuk</a><a href="{{auth()->check()?route('lab-requests.index'):route('applicant.register')}}" class="btn btn-success">Ajukan Permohonan</a></div></div></nav>

<header class="hero"><div class="container position-relative" style="z-index:1"><div class="row align-items-center g-5"><div class="col-lg-7"><div class="eyebrow mb-3">BROSUR LAYANAN PENGUJIAN</div><h1 class="fw-bold">Permohonan Pengujian Laboratorium Beton</h1><p class="lead text-white-50 mt-4">Pemeriksaan material, analisis agregat, desain campuran, dan pengujian kuat tekan dalam satu layanan laboratorium yang terdokumentasi.</p><div class="d-flex gap-3 mt-4 flex-wrap"><a href="{{auth()->check()?route('lab-requests.index'):route('applicant.register')}}" class="btn btn-warning btn-lg px-4"><i class="bi bi-file-earmark-text me-2"></i>Buat Permohonan</a><a href="#layanan" class="btn btn-outline-light btn-lg px-4">Lihat Layanan</a></div></div><div class="col-lg-5"><div class="hero-card"><h4 class="fw-bold">Mudah dan Terpantau</h4><div class="mt-4"><div class="d-flex gap-3 mb-3"><i class="bi bi-person-check fs-4 text-warning"></i><div><b>Daftar sebagai pemohon</b><div class="text-white-50 small">Satu akun untuk seluruh permohonan.</div></div></div><div class="d-flex gap-3 mb-3"><i class="bi bi-ui-checks fs-4 text-warning"></i><div><b>Isi data pengujian</b><div class="text-white-50 small">Cantumkan jenis layanan dan sampel.</div></div></div><div class="d-flex gap-3"><i class="bi bi-bell fs-4 text-warning"></i><div><b>Pantau status</b><div class="text-white-50 small">Lihat hasil tinjauan dan jadwal laboratorium.</div></div></div></div></div></div></div></div></header>

<section class="section" id="layanan"><div class="container"><div class="text-center mb-5"><div class="text-success fw-bold small">LAYANAN TERSEDIA</div><h2 class="fw-bold">Jenis Pengujian Laboratorium</h2><p class="text-secondary">Pilih kebutuhan yang paling sesuai. Rincian akhir akan dikonfirmasi oleh petugas.</p></div><div class="row g-4">
@php($icons=['pemeriksaan-material'=>'clipboard2-pulse','analisis-agregat'=>'bar-chart-steps','desain-campuran'=>'calculator','kuat-tekan'=>'speedometer','paket-lengkap'=>'collection','lainnya'=>'three-dots'])
@foreach($services as $key=>$label)<div class="col-md-6 col-xl-4"><div class="service-card"><div class="service-icon mb-3"><i class="bi bi-{{$icons[$key]??'beaker'}}"></i></div><h5 class="fw-bold">{{$label}}</h5><p class="text-secondary mb-0">@switch($key)@case('pemeriksaan-material')Pemeriksaan sifat semen, air, pasir, dan kerikil sebagai bahan penyusun beton.@break @case('analisis-agregat')Analisis saringan, gradasi, kadar air, berat jenis, penyerapan, dan berat isi agregat.@break @case('desain-campuran')Perencanaan proporsi beton berdasarkan SNI 7656:2012 dan data bahan yang tersedia.@break @case('kuat-tekan')Pembuatan jadwal serta pengujian benda uji beton berdasarkan umur pengujian.@break @case('paket-lengkap')Rangkaian pemeriksaan bahan, desain campuran, percobaan, dan evaluasi kuat tekan.@break @default Sampaikan kebutuhan laboratorium lain untuk ditinjau oleh petugas.@endswitch</p></div></div>@endforeach
</div></div></section>

<section class="section bg-white"><div class="container"><div class="row g-5"><div class="col-lg-6"><div class="text-success fw-bold small mb-2">ALUR PERMOHONAN</div><h2 class="fw-bold mb-4">Empat Tahap Pelayanan</h2>@foreach([['Daftar atau masuk','Buat akun pemohon menggunakan identitas dan alamat surel aktif.'],['Isi permohonan','Masukkan nama pekerjaan, layanan, data sampel, lokasi, dan waktu yang diharapkan.'],['Tinjauan laboratorium','Petugas memeriksa kelengkapan serta memberikan status dan keterangan.'],['Penjadwalan pengujian','Permohonan yang diterima dijadwalkan sesuai kesiapan laboratorium dan sampel.']] as $i=>$step)<div class="step mb-4"><div class="step-number">{{$i+1}}</div><div><h5 class="fw-bold mb-1">{{$step[0]}}</h5><div class="text-secondary">{{$step[1]}}</div></div></div>@endforeach</div><div class="col-lg-6"><div class="text-success fw-bold small mb-2">SIAPKAN DATA</div><h2 class="fw-bold mb-4">Kelengkapan Permohonan</h2>@foreach(['Identitas pemohon dan instansi/perusahaan','Nama serta lokasi pekerjaan atau proyek','Jenis layanan pengujian yang dibutuhkan','Jenis, kondisi, dan jumlah sampel','Tanggal pelaksanaan yang diharapkan','Uraian mutu rencana atau kebutuhan khusus'] as $item)<div class="requirement mb-3"><i class="bi bi-check-circle-fill text-success me-2"></i>{{$item}}</div>@endforeach</div></div></div></section>

<section class="section"><div class="container"><div class="cta"><div class="row align-items-center g-4"><div class="col-lg-8"><h2 class="fw-bold">Siap mengajukan pengujian?</h2><p class="text-white-50 mb-0">Buat akun pemohon, isi formulir, lalu pantau tanggapan laboratorium melalui aplikasi.</p></div><div class="col-lg-4 text-lg-end"><a href="{{auth()->check()?route('lab-requests.index'):route('applicant.register')}}" class="btn btn-warning btn-lg px-4">Ajukan Permohonan</a></div></div></div></div></section>

<footer class="footer"><div class="container d-flex justify-content-between gap-4 flex-wrap"><div><b>{{$laboratory?->name?:'Laboratorium Bahan dan Struktur'}}</b><div>{{$laboratory?->institution?:'Universitas Muhammadiyah Buton'}}</div><div class="small mt-2">{{$laboratory?->address}}</div></div><div class="text-md-end"><div>{{$laboratory?->phone}}</div><div>{{$laboratory?->email}}</div><small>Dikembangkan oleh MUHAMMAD ABDU, S.T., M.T.</small></div></div></footer>
</body>
</html>
