@extends('layouts.app')
@section('title',$combined?'Desain Campuran SNI 7656:2012 (Gradasi Gabungan)':'Desain Campuran SNI 7656:2012')
@section('subtitle',$combined?'Penentuan pasir dan kerikil berdasarkan persentase gradasi gabungan':'Lembar perhitungan otomatis berdasarkan data hasil pemeriksaan material')
@push('head')
<style>
.md-sheet{max-width:1180px;margin:auto;background:#fff;border:1px solid #87939a;border-radius:4px;overflow:hidden;box-shadow:0 6px 22px #17313c16}
.md-head{text-align:center;padding:20px;border-bottom:2px solid #273b44}.md-head h4{margin:0;font-weight:800}.md-head p{margin:3px 0 0;font-size:.82rem}
.md-section{border-bottom:1px solid #73828a}.md-title{display:flex;gap:10px;align-items:center;background:#d9dcde;border-bottom:1px solid #73828a;padding:8px 12px;font-weight:800;font-size:.9rem}
.md-no{display:grid;place-items:center;width:27px;height:27px;background:#243f4c;color:white;border-radius:50%;flex:0 0 auto}
.md-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0}.md-cell{padding:8px 10px;border-right:1px solid #d7dcdf;border-bottom:1px solid #e0e4e6;min-height:66px}
.md-cell label{display:block;font-size:.72rem;font-weight:700;color:#53656d;margin-bottom:4px}.md-cell input,.md-cell select{border:1px solid #9ca8ad;border-radius:2px;width:100%;padding:6px 8px;background:#f0e9fa}
.md-cell .unit{font-size:.7rem;color:#708087}.md-result{background:#eff7ef;font-size:1.02rem;font-weight:800;color:#146b60;padding:7px 8px;min-height:38px;border-left:3px solid #1b9a89}
.md-result.invalid{color:#b02a37;border-color:#dc3545;background:#fff0f1}.formula{font-size:.68rem;color:#708087;margin-top:3px}
.composition th{background:#d9dcde!important;color:#24333a!important}.composition td,.composition th{text-align:right}.composition td:first-child,.composition th:first-child{text-align:left}
.source-note{background:#e8f3f5;border-left:4px solid #138b80;padding:10px 14px;font-size:.82rem}.sticky-save{position:sticky;bottom:0;background:#fff;border-top:1px solid #ccd5d9;padding:12px 16px;z-index:5}
.test-status{border:1px solid #ced8dc;border-radius:5px;padding:9px 11px;background:#f5faf9}.test-status.missing{border-color:#dc3545;background:#fff0f1;color:#9f1d2a}.md-cell.missing{background:#fff1f2}.md-cell.missing input{background:#ffd9dd;border:2px solid #dc3545}.missing-note{display:block;color:#b02a37;font-size:.68rem;font-weight:700;margin-top:3px}
.reference-table{font-size:.78rem}.reference-table th{background:#d9dcde!important;text-align:center}.reference-table td{vertical-align:middle}.reference-table tr.selected td{background:#e4f4ef;font-weight:700}.reference-help{background:#fff9df;border-left:4px solid #e3b341;padding:9px 11px;font-size:.76rem}
.reference-table td.active-ref{background:#bfe7db!important;color:#075f55;font-weight:800;outline:2px solid #138b80}.step-formula{padding:10px 12px;background:#eef3f5;border-top:1px solid #c7d1d5;font-size:.76rem}
.gradation-panel{border:1px solid #8d999f;border-radius:5px;overflow:hidden}.gradation-panel-title{background:#eef2f3;border-bottom:1px solid #aab4b9;padding:9px 12px;font-weight:800}.gradation-analysis th,.gradation-analysis td{text-align:center;vertical-align:middle;white-space:nowrap}.gradation-analysis .composition-value{color:#dc3545;font-weight:900;font-size:.92rem}.gradation-analysis .combined-mass{background:#ecf7f3;font-weight:800}.analysis-summary{background:#102f3d;color:#fff;border-radius:5px;padding:13px 16px}.analysis-summary strong{color:#66e0c7;font-size:1.15rem}.analysis-ready{background:#e7f6ef;border:1px solid #8dd2b7;color:#126344}.analysis-pending{background:#fff3cd;border:1px solid #e7c766;color:#775b00}
.gradation-chart-wrap{background:#fff;border:1px solid #d4dadd;border-radius:5px;padding:12px}.gradation-chart{display:block;width:100%;height:auto;min-width:760px}.chart-grid line{stroke:#dce3e6;stroke-width:1}.chart-grid text,.chart-axis-label{fill:#637780;font-size:12px}.chart-series{fill:none;stroke-width:2;stroke-linejoin:round;stroke-linecap:round}.chart-series.average{stroke-width:3;stroke-dasharray:8 5}.chart-series.combined{stroke:#dc3545;stroke-width:4;filter:drop-shadow(0 1px 1px #dc354555)}.chart-point{fill:#dc3545}.chart-legend{display:flex;flex-wrap:wrap;gap:8px 16px;font-size:.76rem}.chart-legend span{display:inline-flex;align-items:center;gap:6px}.chart-swatch{width:23px;height:4px;border-radius:2px;display:inline-block}
@media(max-width:850px){.md-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.md-grid{grid-template-columns:1fr}}
</style>
@endpush
@section('content')
<div class="d-flex justify-content-end mb-3"><a class="btn btn-outline-primary" href="{{route('documentation.index',['project'=>$project?->id,'module'=>$combined?'mix-design-2012-combined':'mix-design-2012'])}}"><i class="bi bi-camera me-2"></i>Dokumentasi Desain Campuran</a></div>
<form method="post" action="{{route($combined?'mix-design-2012-combined.store':'mix-design-2012.store')}}" id="mixForm">@csrf
<div class="md-sheet">
 <div class="md-head"><h4>PERENCANAAN CAMPURAN BETON NORMAL</h4><div>SNI 7656:2012{{$combined?' — GRADASI GABUNGAN':''}}</div><p>Laboratorium Bahan dan Struktur</p></div>
 <div class="p-3 border-bottom">
  <div class="row g-3">
   <div class="col-md-5"><label class="form-label">Proyek</label><select class="form-select" name="project_id" id="projectSelector" required><option value="">— Pilih proyek aktif —</option>@foreach($projects as $p)<option value="{{$p->id}}" @selected(old('project_id',$project?->id)==$p->id)>{{$p->number}} — {{$p->name}}</option>@endforeach</select></div>
   <div class="col-md-3"><label class="form-label">Tanggal perencanaan</label><input class="form-control" type="date" name="work_date" value="{{old('work_date',date('Y-m-d'))}}" required></div>
   <div class="col-md-4"><label class="form-label">Pemohon / perusahaan</label><input class="form-control" value="{{$project?->owner ?? '-'}}" readonly></div>
  </div>
  @if($project)<div class="source-note mt-3"><b>Data proyek {{$project->number}}</b> dipilih. Nilai material di bawah diambil dari pemeriksaan laboratorium terakhir.</div>
  <div class="row g-2 mt-1">
   @foreach([['Semen',$cement],['Air',$water],['Pasir',$fine],['Kerikil',$coarse]] as [$label,$test])
   <div class="col-md-3"><div class="test-status {{$test?'':'missing'}}"><b>{{$label}}</b><div class="small">{{$test?'Sudah diuji — '.$test->test_number:'BELUM DIUJI'}}</div></div></div>
   @endforeach
  </div>
  @php $missingItems=collect($required)->filter(fn($item)=>$item[2]===null); @endphp
  @if($missingItems->isNotEmpty())<div class="alert alert-danger mt-2 mb-0"><b>Data pengujian belum lengkap:</b> {{$missingItems->map(fn($item)=>$item[0].' — '.$item[1])->join(', ')}}. Lengkapi Pemeriksaan Material sebelum menyimpan desain campuran.</div>@endif
  @endif
 </div>

 @php
 $d=fn($key,$default)=>old("data.$key",$default);
 $hasIncomplete=!$project || !$water || collect($required)->contains(fn($item)=>$item[2]===null);
 $cell=function($key,$label,$value,$unit='') use($d,$required){ $labValue=array_key_exists($key,$required); $missing=$labValue&&$required[$key][2]===null; return '<div class="md-cell '.($missing?'missing':'').'"><label>'.$label.'</label><input class="calc-input" type="number" step="any" name="data['.$key.']" data-key="'.$key.'" value="'.e($d($key,$value)).'" required '.($labValue?'readonly':'').'><span class="unit">'.$unit.'</span>'.($missing?'<span class="missing-note">Belum ada hasil pengujian material</span>':($labValue?'<span class="formula">Otomatis dari hasil uji laboratorium</span>':'')).'</div>'; };
 $result=fn($key,$label,$unit='')=>'<div class="md-cell"><label>'.$label.'</label><div class="md-result" data-result="'.$key.'">—</div><span class="unit">'.$unit.'</span></div>';
 @endphp

 <section class="md-section"><div class="md-title"><span class="md-no">1</span>Data umum bahan penyusun beton</div><div class="md-grid">
  {!!$cell('cement_sg','Berat jenis semen',$cement?->specific_gravity ?? '','')!!}
  {!!$cell('coarse_sg','Berat jenis SSD agregat kasar',$coarse?->specific_gravity_ssd ?? '','')!!}
  {!!$cell('coarse_absorption','Penyerapan agregat kasar',$coarse?->absorption ?? '','%')!!}
  {!!$cell('coarse_moisture','Kadar air agregat kasar',$coarse?->field_moisture ?? '','%')!!}
  {!!$cell('coarse_density','Berat isi padat agregat kasar',$coarse?->compacted_bulk_density ?? '','kg/m³')!!}
  {!!$cell('fine_sg','Berat jenis SSD agregat halus',$fine?->specific_gravity_ssd ?? '','')!!}
  {!!$cell('fine_absorption','Penyerapan agregat halus',$fine?->absorption ?? '','%')!!}
  {!!$cell('fine_moisture','Kadar air agregat halus',$fine?->field_moisture ?? '','%')!!}
  {!!$cell('fine_density','Berat isi padat agregat halus',$fine?->compacted_bulk_density ?? '','kg/m³')!!}
  {!!$cell('fine_fm','Modulus kehalusan agregat halus',$fine?->fineness_modulus ?? '','')!!}
 </div></section>

 <section class="md-section"><div class="md-title"><span class="md-no">2</span>Kuat tekan beton yang disyaratkan</div><div class="md-grid">
  {!!$cell('fc',"Kuat tekan f'c",25,'MPa')!!}{!!$cell('age','Umur pengujian',28,'hari')!!}{!!$cell('volume_work','Volume pekerjaan',1,'m³')!!}
 </div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">3</span>Penetapan deviasi standar</div><div class="p-3"><div class="row g-3"><div class="col-lg-7"><table class="table table-bordered reference-table mb-0" id="sdTable"><thead><tr><th>Pilih</th><th class="text-start">Ketersediaan/kendali data laboratorium</th><th>Deviasi standar (MPa)</th></tr></thead><tbody>
  @foreach([[2.8,'Data historis sangat baik'],[3.5,'Data historis baik'],[4.8,'Data historis cukup'],[6.0,'Data historis terbatas'],[7.5,'Belum tersedia data historis']] as [$sdValue,$sdLabel])<tr class="{{$sdValue==7.5?'selected':''}}"><td class="text-center"><input class="form-check-input sd-choice" type="radio" name="sd_choice" value="{{$sdValue}}" @checked($sdValue==7.5)></td><td>{{$sdLabel}}</td><td class="text-center">{{$sdValue}}</td></tr>@endforeach
  </tbody></table></div><div class="col-lg-5"><div class="reference-help mb-2">Pilih deviasi berdasarkan catatan produksi laboratorium. Nilai masih dapat disesuaikan jika tersedia perhitungan deviasi aktual.</div><div class="md-grid" style="grid-template-columns:1fr 1fr">{!!$cell('sd','Deviasi standar terpilih',7.5,'MPa')!!}{!!$cell('sd_additional','Tambahan deviasi',0,'MPa')!!}{!!$cell('test_count','Jumlah hasil uji',30,'buah')!!}{!!$cell('deviation_factor','Faktor pengali',1.64,'')!!}</div></div></div></div>
  <div class="step-formula">Margin = (deviasi standar + tambahan deviasi) × faktor pengali.</div>
 </section>
 <section class="md-section"><div class="md-title"><span class="md-no">4</span>Margin</div><div class="md-grid">{!!$result('margin','Margin = (S + tambahan) × faktor','MPa')!!}</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">5</span>Kuat tekan rata-rata yang ditargetkan</div><div class="md-grid">{!!$result('fcr',"f'cr = f'c + margin",'MPa')!!}</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">6</span>Penentuan nilai slump — Tabel 1 SNI 7656:2012</div>
  <div class="p-3"><div class="row g-3"><div class="col-lg-8"><div class="table-responsive"><table class="table table-bordered reference-table mb-0" id="slumpTable"><thead><tr><th rowspan="2">Pilih</th><th rowspan="2" class="text-start">Tipe konstruksi</th><th colspan="2">Slump (mm)</th></tr><tr><th>Maksimum</th><th>Minimum</th></tr></thead><tbody>
  @foreach([
   [0,'Pondasi beton bertulang (dinding dan pondasi telapak)',75,25],
   [1,'Pondasi telapak tanpa tulangan, pondasi tiang pancang, dan dinding bawah tanah',75,25],
   [2,'Balok dan dinding bertulang',100,25],
   [3,'Kolom bangunan',100,25],
   [4,'Perkerasan dan pelat lantai',75,25],
   [5,'Beton massa',50,25],
  ] as [$id,$label,$max,$min])<tr data-slump-row="{{$id}}" class="{{$id===2?'selected':''}}"><td class="text-center"><input type="radio" class="form-check-input slump-choice" name="slump_choice" value="{{$id}}" data-min="{{$min}}" data-max="{{$max}}" @checked($id===2)></td><td>{{$label}}</td><td class="text-center">{{$max}}</td><td class="text-center">{{$min}}</td></tr>@endforeach
  </tbody></table></div></div><div class="col-lg-4"><div class="reference-help mb-2"><b>Cara mengisi:</b> pilih tipe konstruksi pada tabel. Batas minimum dan maksimum akan terisi otomatis, kemudian tentukan slump rencana di dalam batas tersebut.</div>
  <input type="hidden" name="data[construction_type]" data-key="construction_type" value="2">
  <div class="md-cell"><label>Slump minimum</label><input class="calc-input" type="number" step="any" name="data[slump_min]" data-key="slump_min" value="{{$d('slump_min',25)}}" readonly><span class="unit">mm</span></div>
  <div class="md-cell"><label>Slump maksimum</label><input class="calc-input" type="number" step="any" name="data[slump_max]" data-key="slump_max" value="{{$d('slump_max',100)}}" readonly><span class="unit">mm</span></div>
  <div class="md-cell"><label>Penentuan nilai slump awal</label><input class="calc-input" type="number" min="25" max="100" step="5" name="data[slump_design]" data-key="slump_design" value="{{$d('slump_design',100)}}" required><span class="unit">mm — dapat diketik sesuai kebutuhan dalam batas tabel</span></div>
  </div></div></div>
 </section>
 @php $maxOptions=[9.5,12.7,19,25,37.5,50,75,150]; $testedMax=(float)($coarse?->nominal_maximum_size ?: 25); $maxDefault=in_array($testedMax,$maxOptions,true)?$testedMax:($testedMax==20?19:25); @endphp
 <section class="md-section"><div class="md-title"><span class="md-no">7</span>Penentuan agregat maksimum — Tabel 1 SNI 7656:2012</div><div class="p-3"><div class="table-responsive"><table class="table table-bordered reference-table mb-3"><thead><tr><th>No.</th><th class="text-start">Ketentuan</th><th>Data yang dilengkapi (mm)</th><th>Perhitungan otomatis (mm)</th></tr></thead><tbody>
  <tr><td>1</td><td>1/5 dari ukuran terkecil dimensi antara dinding-dinding cetakan/bekisting</td><td><input class="form-control form-control-sm calc-input" type="number" min="0.01" step="any" name="data[smallest_form_dimension]" data-key="smallest_form_dimension" value="{{$d('smallest_form_dimension',125)}}" required></td><td class="text-center fw-bold" data-aggregate-limit="form">—</td></tr>
  <tr><td>2</td><td>1/3 tebal pelat lantai</td><td><input class="form-control form-control-sm calc-input" type="number" min="0.01" step="any" name="data[slab_thickness]" data-key="slab_thickness" value="{{$d('slab_thickness',75)}}" required></td><td class="text-center fw-bold" data-aggregate-limit="slab">—</td></tr>
  <tr><td>3</td><td>3/4 jarak minimum masing-masing batang tulangan, berkas tulangan, atau tendon</td><td><input class="form-control form-control-sm calc-input" type="number" min="0.01" step="any" name="data[clear_rebar_spacing]" data-key="clear_rebar_spacing" value="{{$d('clear_rebar_spacing',40)}}" required></td><td class="text-center fw-bold" data-aggregate-limit="rebar">—</td></tr>
  </tbody></table></div><input type="hidden" name="data[tested_max_size]" data-key="tested_max_size" value="{{$coarse?->nominal_maximum_size ?? 0}}"><div class="row g-3"><div class="col-md-4"><div class="test-status"><b>Ukuran nominal hasil uji kerikil</b><div>{{$coarse?->nominal_maximum_size ?? 'Belum diuji'}} mm</div></div></div><div class="col-md-4"><div class="test-status"><b>Batas terkecil struktur</b><div data-aggregate-limit="minimum">—</div></div></div><div class="col-md-4"><div class="md-cell"><label>Nilai agregat maksimum yang digunakan</label><input class="calc-input" type="number" step="any" name="data[max_size]" data-key="max_size" value="{{$d('max_size',$maxDefault)}}" readonly><span class="unit">mm — standar terbesar yang tidak melebihi seluruh batas</span></div></div></div></div>
  <div class="step-formula">Sistem menghitung ketiga ketentuan, mengambil nilai terkecil, membandingkannya dengan ukuran hasil uji kerikil, kemudian memilih ukuran standar yang memenuhi.</div>
 </section>
 <section class="md-section"><div class="md-title"><span class="md-no">8</span>Perkiraan air pencampur dan kadar udara — Tabel 3 SNI 7656:2012</div><div class="p-3 pb-0"><div class="table-responsive"><table class="table table-bordered reference-table water-reference"><thead><tr><th rowspan="2">Jenis beton</th><th rowspan="2">Slump (mm)</th><th colspan="8">Kebutuhan air (kg/m³) menurut ukuran maksimum agregat (mm)</th></tr><tr>@foreach($maxOptions as $s)<th data-water-size="{{$s}}">{{$s}}</th>@endforeach</tr></thead><tbody>
 @foreach([
 ['Tanpa udara','25–50',[207,199,190,179,166,154,130,113],0,0],['Tanpa udara','75–100',[228,216,205,193,181,169,145,124],0,1],['Tanpa udara','150–175',[243,228,216,202,190,178,160,124],0,2],
 ['Dengan udara','25–50',[181,175,168,160,150,142,122,107],1,0],['Dengan udara','75–100',[202,193,184,175,165,157,133,119],1,1],['Dengan udara','150–175',[216,205,197,184,174,166,154,119],1,2]
 ] as [$airLabel,$slumpLabel,$values,$airKey,$rangeKey])<tr data-water-row="{{$airKey}}-{{$rangeKey}}"><td>{{$airLabel}}</td><td>{{$slumpLabel}}</td>@foreach($values as $i=>$wv)<td class="text-center" data-water-cell="{{$airKey}}-{{$rangeKey}}-{{$i}}">{{$wv}}</td>@endforeach</tr>@endforeach
 </tbody></table></div></div><div class="md-grid">
  <div class="md-cell"><label>Jenis beton</label><select class="calc-input" name="data[air_entrained]" data-key="air_entrained"><option value="0" @selected((int)$d('air_entrained',0)===0)>Tanpa kandungan udara</option><option value="1" @selected((int)$d('air_entrained',0)===1)>Dengan kandungan udara</option></select><span class="unit">Pilih sesuai persyaratan pekerjaan</span></div>
  <div class="md-cell"><label>Kondisi pemaparan (untuk beton berudara)</label><select class="calc-input" name="data[exposure_level]" data-key="exposure_level"><option value="0">Ringan</option><option value="1" selected>Sedang</option><option value="2">Berat</option></select><span class="unit">Mempengaruhi sasaran kadar udara</span></div>
  <div class="md-cell"><label>Kebutuhan air dari tabel</label><input class="calc-input" type="number" step="any" name="data[water]" data-key="water" value="{{$d('water',193)}}" readonly><span class="unit">kg/m³ — otomatis dari slump, ukuran agregat, dan jenis beton</span></div>
  <div class="md-cell"><label>Kadar udara dari tabel</label><input class="calc-input" type="number" step="any" name="data[air_content]" data-key="air_content" value="{{$d('air_content',1.5)}}" readonly><span class="unit">% — otomatis</span></div>
 </div><div class="step-formula">Sel hijau menunjukkan nilai tabel yang sedang digunakan berdasarkan pilihan slump, ukuran agregat, dan kandungan udara.</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">9</span>Penetapan rasio air-semen (FAS)</div><div class="p-3"><div class="row g-3"><div class="col-lg-8"><table class="table table-bordered reference-table mb-0" id="wcTable"><thead><tr><th>Kuat tekan rata-rata sasaran (MPa)</th><th>Tanpa udara</th><th>Dengan udara</th><th>Keterangan</th></tr></thead><tbody>
 @foreach([[15,.79,.70],[20,.69,.60],[25,.61,.52],[30,.54,.45],[35,.47,.39],[40,.42,.35]] as [$strength,$normal,$air])<tr data-fc-row="{{$strength}}"><td class="text-center">{{$strength}}</td><td class="text-center" data-wc-normal="{{$strength}}">{{$normal}}</td><td class="text-center" data-wc-air="{{$strength}}">{{$air}}</td><td class="text-center" data-wc-status="{{$strength}}">—</td></tr>@endforeach
 </tbody></table></div><div class="col-lg-4"><div class="reference-help mb-2"><b>Otomatis dari poin 5.</b> Jika f'cr tepat sama dengan tabel, satu baris ditandai “Sesuai”. Jika berada di antara dua angka, sistem menandai batas bawah dan batas atas kemudian melakukan interpolasi linier.</div><div class="md-cell"><label>FAS hasil tabel/interpolasi</label><input class="calc-input" type="number" step="any" name="data[wc_ratio]" data-key="wc_ratio" value="{{$d('wc_ratio',0.45)}}" readonly><span class="unit" id="wcInterpolationInfo">Otomatis berdasarkan f'cr</span></div></div></div></div><div class="step-formula">FAS = FAS bawah + ((f'cr − kuat tekan bawah) ÷ (kuat tekan atas − kuat tekan bawah)) × (FAS atas − FAS bawah).</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">10</span>Kadar semen</div><div class="md-grid">{!!$result('cement','Semen = air ÷ FAS','kg/m³')!!}</div></section>
 @php($sieveKeys=['r375'=>['1 1/2"','37,5'],'r190'=>['3/4"','19,0'],'r095'=>['3/8"','9,5'],'r475'=>['No.4','4,75'],'r236'=>['No.8','2,36'],'r118'=>['No.16','1,18'],'r060'=>['No.30','0,60'],'r030'=>['No.50','0,30'],'r015'=>['No.100','0,15']])
 @php($fineCum=$fineSieve?->results['observations'][0]['sieve_cumulative']??[])
 @php($coarseCum=$coarseSieve?->results['observations'][0]['sieve_cumulative']??[])
 <section class="md-section"><div class="md-title"><span class="md-no">11</span>Penentuan Pasir dan Kerikil dari Gradasi Gabungan</div><div class="p-3">
  <div class="gradation-panel mb-3"><div class="gradation-panel-title">A. Tabel Batas Gradasi Campuran</div><div class="p-3"><div class="row g-3 mb-3">
   <div class="col-md-5"><label class="form-label">Ukuran butir maksimum</label><select class="calc-input form-select" name="data[gradation_max_size]" data-key="gradation_max_size"><option value="40" @selected($d('gradation_max_size',20)==40)>40 mm</option><option value="20" @selected($d('gradation_max_size',20)==20)>20 mm</option><option value="10" @selected($d('gradation_max_size',20)==10)>10 mm</option></select></div>
   <div class="col-md-7"><label class="form-label">Batas sasaran analisis</label><select class="calc-input form-select" name="data[gradation_curve]" data-key="gradation_curve">@for($curveChoice=1;$curveChoice<=4;$curveChoice++)<option value="{{$curveChoice}}" @selected($d('gradation_curve',5)==$curveChoice)>Kurva {{$curveChoice}}</option>@endfor<option value="5" @selected($d('gradation_curve',5)==5)>Rata-rata Kurva 1–4</option></select></div>
  </div><div class="table-responsive"><table class="table table-bordered reference-table mb-0" id="gradationLimitTable"><thead><tr><th rowspan="2">Saringan</th><th colspan="6">Persen lolos batas gradasi campuran</th></tr><tr><th>mm</th><th>Kurva 1</th><th>Kurva 2</th><th>Kurva 3</th><th>Kurva 4</th><th>Rata-rata</th></tr></thead><tbody>
  @foreach($sieveKeys as $key=>[$inch,$size])<tr data-limit-sieve="{{$key}}"><td>{{$inch}}</td><td>{{$size}}</td>@for($curve=1;$curve<=4;$curve++)<td class="gradation-bound" data-curve="{{$curve}}">—</td>@endfor<td class="gradation-average">—</td></tr>@endforeach
  </tbody></table></div></div></div>
  <div class="gradation-panel"><div class="gradation-panel-title d-flex justify-content-between align-items-center gap-3"><span>B. Analisis Komposisi Pasir dan Kerikil</span><button type="button" class="btn btn-primary btn-sm px-3" id="analyzeGradation"><i class="bi bi-play-fill me-1"></i>Analisis Gradasi</button></div><div class="p-3">
   <div class="analysis-summary mb-3"><div class="row g-3 text-center"><div class="col-md-3">Pasir optimum<br><strong><span data-combined-fine>—</span>%</strong></div><div class="col-md-3">Kerikil optimum<br><strong><span data-combined-coarse>—</span>%</strong></div><div class="col-md-3">Total<br><strong><span data-combined-total>100,0</span>%</strong></div><div class="col-md-3">Deviasi rata-rata<br><strong><span data-combined-deviation>—</span></strong></div></div></div>
   <input type="hidden" name="data[combined_fine_percent]" data-key="combined_fine_percent" value="{{$d('combined_fine_percent',50)}}"><input type="hidden" name="data[combined_deviation]" data-key="combined_deviation" value="{{$d('combined_deviation',0)}}">
   <div class="table-responsive"><table class="table table-bordered reference-table gradation-analysis mb-2"><thead>
    <tr><th colspan="2">Ukuran Saringan</th><th colspan="2">Persen Lolos Kumulatif</th><th colspan="2">Persen Tertahan Kumulatif</th><th colspan="2">Persen Massa Lolos<br><span class="small">(Lolos × Komposisi)</span></th><th rowspan="2">Massa Lolos<br>Gabungan</th><th rowspan="2">Sasaran<br>Terpilih</th><th rowspan="2">Deviasi<br>Absolut</th></tr>
    <tr><th>in</th><th>mm</th><th>Pasir</th><th>Kerikil</th><th>Pasir</th><th>Kerikil</th><th>Pasir<br><span class="composition-value" data-fine-header>—%</span></th><th>Kerikil<br><span class="composition-value" data-coarse-header>—%</span></th></tr>
   </thead><tbody>
   @foreach($sieveKeys as $key=>[$inch,$size]) @php($finePass=in_array($key,['r375','r190','r095'])?100:(isset($fineCum[$key])?100-$fineCum[$key]:null)) @php($coarsePass=isset($coarseCum[$key])?100-$coarseCum[$key]:(in_array($key,['r236','r118','r060','r030','r015'])?0:null))
   <tr class="combined-row" data-sieve="{{$key}}" data-fine="{{$finePass}}" data-coarse="{{$coarsePass}}"><td>{{$inch}}</td><td>{{$size}}</td><td class="fine-passing">{{$finePass===null?'Belum diuji':number_format($finePass,2,',','.')}}</td><td class="coarse-passing">{{$coarsePass===null?'Belum diuji':number_format($coarsePass,2,',','.')}}</td><td class="fine-retained">{{$finePass===null?'—':number_format(100-$finePass,2,',','.')}}</td><td class="coarse-retained">{{$coarsePass===null?'—':number_format(100-$coarsePass,2,',','.')}}</td><td class="fine-weighted">—</td><td class="coarse-weighted">—</td><td class="combined-passing combined-mass">—</td><td class="combined-target">—</td><td class="combined-row-deviation">—</td></tr>
   @endforeach
   </tbody></table></div>
   <div class="analysis-pending p-2" data-combined-status><b>Tekan Analisis Gradasi.</b> Sistem akan mencoba komposisi 0,0% sampai 100,0% pasir dengan langkah 0,1%.</div>
   <div class="alert alert-warning py-2 mt-2 d-none" data-combined-warning>Persen lolos kumulatif belum lengkap. Lengkapi analisis saringan pasir dan kerikil sebelum menjalankan analisis.</div>
  </div></div>
  <div class="gradation-panel mt-3"><div class="gradation-panel-title d-flex justify-content-between align-items-center gap-3"><span>C. Grafik Kurva Gradasi Campuran</span><span class="badge badge-soft" data-chart-composition>Pasir 50,0% · Kerikil 50,0%</span></div><div class="p-3">
   <div class="chart-legend mb-2"><span><i class="chart-swatch" style="background:#2563eb"></i>Kurva 1</span><span><i class="chart-swatch" style="background:#16a34a"></i>Kurva 2</span><span><i class="chart-swatch" style="background:#d97706"></i>Kurva 3</span><span><i class="chart-swatch" style="background:#7c3aed"></i>Kurva 4</span><span><i class="chart-swatch" style="background:#102f3d"></i>Rata-rata Kurva 1–4</span><span><i class="chart-swatch" style="background:#dc3545"></i>Massa Lolos Gabungan</span></div>
   <div class="gradation-chart-wrap table-responsive"><svg class="gradation-chart" id="gradationChart" viewBox="0 0 920 430" role="img" aria-label="Grafik kurva gradasi campuran"><g class="chart-grid" data-chart-grid></g><polyline class="chart-series" data-chart-series="curve-1" stroke="#2563eb"></polyline><polyline class="chart-series" data-chart-series="curve-2" stroke="#16a34a"></polyline><polyline class="chart-series" data-chart-series="curve-3" stroke="#d97706"></polyline><polyline class="chart-series" data-chart-series="curve-4" stroke="#7c3aed"></polyline><polyline class="chart-series average" data-chart-series="average" stroke="#102f3d"></polyline><polyline class="chart-series combined" data-chart-series="combined"></polyline><g data-chart-points></g><text x="460" y="422" text-anchor="middle" class="chart-axis-label">Ukuran saringan</text><text x="16" y="205" text-anchor="middle" transform="rotate(-90 16 205)" class="chart-axis-label">Persen lolos kumulatif (%)</text></svg></div>
   <div class="small text-secondary mt-2">Garis merah bergerak mengikuti massa lolos gabungan pada setiap komposisi yang sedang dianalisis. Posisi akhirnya menunjukkan komposisi dengan deviasi rata-rata terkecil.</div>
  </div></div>
  <div class="reference-help mt-3"><b>Proses analisis:</b> setiap komposisi diuji mulai 0,0% pasir + 100,0% kerikil, 0,1% + 99,9%, dan seterusnya sampai 100,0% + 0,0%. Kontribusi setiap agregat = persen lolos × persentase komposisi. Keduanya dijumlahkan menjadi massa lolos gabungan, kemudian sistem memilih komposisi dengan rata-rata deviasi absolut terkecil terhadap seluruh sasaran saringan.</div>
  </div><div class="md-grid">{!!$result('aggregate_mass_available','Total berat agregat: beton − semen − air','kg/m³')!!}{!!$result('coarse_ssd','Berat agregat kasar hasil gradasi','kg/m³')!!}</div><div class="step-formula">Berat agregat kasar poin 11 = (berat beton segar poin 12 − berat semen poin 10 − berat air poin 8) × persentase kerikil merah.</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">11</span>Penetapan jumlah agregat kasar</div><div class="p-3 pb-0"><div class="table-responsive"><table class="table table-bordered reference-table coarse-reference"><thead><tr><th rowspan="2">Ukuran maksimum (mm)</th><th colspan="4">Volume agregat kasar per satuan volume beton untuk MHB pasir</th></tr><tr>@foreach([2.4,2.6,2.8,3.0] as $fm)<th>{{$fm}}</th>@endforeach</tr></thead><tbody>
 @foreach([[9.5,.50,.48,.46,.44],[12.7,.59,.57,.55,.53],[19,.66,.64,.62,.60],[25,.71,.69,.67,.65],[37.5,.75,.73,.71,.69],[50,.78,.76,.74,.72],[75,.82,.80,.78,.76],[150,.87,.85,.83,.81]] as $row)<tr data-coarse-size="{{$row[0]}}"><td>{{$row[0]}}</td>@foreach(array_slice($row,1) as $i=>$cv)<td class="text-center" data-coarse-cell="{{$row[0]}}-{{$i}}">{{$cv}}</td>@endforeach</tr>@endforeach
 </tbody></table></div></div><div class="md-grid">{!!$result('coarse_ratio','Volume agregat kasar hasil interpolasi','')!!}{!!$result('coarse_ssd','Massa agregat kasar SSD','kg/m³')!!}</div><div class="step-formula">Volume tabel disesuaikan terhadap modulus kehalusan pasir, lalu dikalikan berat isi padat agregat kasar.</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">12</span>Perkiraan awal berat beton segar</div><div class="p-3 pb-0"><div class="table-responsive"><table class="table table-bordered reference-table density-reference"><thead><tr><th>Jenis beton</th>@foreach($maxOptions as $s)<th>{{$s}} mm</th>@endforeach</tr></thead><tbody><tr><td>Tanpa udara</td>@foreach([2280,2310,2345,2380,2410,2445,2490,2530] as $i=>$density)<td class="text-center" data-density-cell="0-{{$i}}">{{$density}}</td>@endforeach</tr><tr><td>Dengan udara</td>@foreach([2200,2230,2275,2315,2350,2375,2420,2470] as $i=>$density)<td class="text-center" data-density-cell="1-{{$i}}">{{$density}}</td>@endforeach</tr></tbody></table></div></div><div class="md-grid"><div class="md-cell"><label>Perkiraan berat beton segar dari tabel</label><input class="calc-input" type="number" step="any" name="data[fresh_density]" data-key="fresh_density" value="{{$d('fresh_density',2380)}}" readonly><span class="unit">kg/m³</span></div>{!!$result('aggregate_mass_available','Total berat agregat tersedia','kg/m³')!!}{!!$result('fine_mass_method',$combined?'Berat pasir hasil gradasi':'Agregat halus (metode massa)','kg/m³')!!}</div><div class="step-formula">{{$combined?'Berat pasir poin 12 = (berat beton segar − berat semen − berat air) × persentase pasir merah.':'Agregat halus metode massa = berat beton segar − air − semen − agregat kasar.'}}</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">13</span>{{$combined?'Volume absolut agregat dari hasil gradasi':'Agregat halus dengan metode volume absolut'}}</div><div class="md-grid">
  {!!$result('vol_water','Volume air','m³')!!}{!!$result('vol_cement','Volume semen','m³')!!}{!!$result('vol_coarse','Volume agregat kasar','m³')!!}{!!$result('vol_air','Volume udara','m³')!!}
  {!!$result('vol_fine','Sisa volume agregat halus','m³')!!}{!!$result('fine_ssd','Massa agregat halus SSD','kg/m³')!!}
 </div><div class="step-formula">{{$combined?'Volume agregat kasar = berat agregat kasar poin 11 ÷ (berat jenis kerikil × 1.000). Volume pasir = berat pasir poin 12 ÷ (berat jenis pasir × 1.000).':'Volume agregat dihitung dari massa dan berat jenis masing-masing bahan.'}}</div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">14</span>Koreksi kadar air agregat</div><div class="md-grid">
  {!!$result('fine_free_water','Air bebas agregat halus','kg/m³')!!}{!!$result('coarse_free_water','Air bebas agregat kasar','kg/m³')!!}
  {!!$result('fine_field','Agregat halus kondisi lapangan','kg/m³')!!}{!!$result('coarse_field','Agregat kasar kondisi lapangan','kg/m³')!!}
  {!!$result('water_added','Air yang ditambahkan','kg/m³')!!}{!!$result('total_fresh_mass','Total massa beton','kg/m³')!!}
 </div></section>
 <section class="md-section"><div class="md-title"><span class="md-no">15</span>Komposisi akhir dan kebutuhan campuran percobaan</div>
  <div class="p-3">
   <div class="row g-3 mb-3"><div class="col-md-4">{!!$cell('trial_volume_liter','Volume campuran percobaan',20,'liter')!!}</div><div class="col-md-4">{!!$cell('waste','Kelebihan / kehilangan',15,'%')!!}</div></div>
   <div class="table-responsive"><table class="table table-bordered composition mb-3"><thead><tr><th>Bahan</th><th>Komposisi lapangan (kg/m³)</th><th>Perbandingan</th><th>Campuran percobaan (kg)</th><th>Per 1 zak semen (kg)</th></tr></thead><tbody>
    <tr><td>Semen</td><td data-result="cement">—</td><td data-result="ratio_cement">—</td><td data-result="trial_cement">—</td><td>50,000</td></tr>
    <tr><td>Agregat halus</td><td data-result="fine_field">—</td><td data-result="ratio_fine">—</td><td data-result="trial_fine">—</td><td data-result="fine_per_sack">—</td></tr>
    <tr><td>Agregat kasar</td><td data-result="coarse_field">—</td><td data-result="ratio_coarse">—</td><td data-result="trial_coarse">—</td><td data-result="coarse_per_sack">—</td></tr>
    <tr><td>Air</td><td data-result="water_added">—</td><td data-result="ratio_water">—</td><td data-result="trial_water">—</td><td data-result="water_per_sack">—</td></tr>
   </tbody></table></div>
  </div>
 </section>
 <div class="p-3"><label class="form-label">Catatan perencanaan</label><textarea class="form-control" name="notes" rows="3">{{old('notes')}}</textarea></div>
 <div class="sticky-save d-flex justify-content-between align-items-center"><span class="small {{$hasIncomplete?'text-danger':'text-secondary'}}"><i class="bi {{$hasIncomplete?'bi-exclamation-triangle':'bi-lightning-charge'}}"></i> {{$hasIncomplete?'Lengkapi seluruh pengujian material agar desain campuran dapat disimpan.':'Semua hasil diperbarui otomatis saat masukan berubah.'}}</span><button class="btn btn-primary px-4" type="submit" @disabled($hasIncomplete)><i class="bi bi-save me-2"></i>Simpan dan Lanjut ke Kuat Tekan</button></div>
</div></form>
@endsection
@push('scripts')
<script>
(()=>{const form=document.getElementById('mixForm'), fmt=(n,d=3)=>Number.isFinite(n)?n.toLocaleString('id-ID',{minimumFractionDigits:d,maximumFractionDigits:d}):'—', combinedLimits=@json($combinedLimits);
 const combinedMode=@json($combined);document.querySelectorAll('.md-title').forEach(title=>{const isCombined=title.textContent.includes('Gradasi Gabungan'),isConventional=title.textContent.includes('Penetapan jumlah agregat kasar');if((combinedMode&&isConventional)||(!combinedMode&&isCombined))title.closest('.md-section').classList.add('d-none')});
 const val=k=>Number(form.querySelector(`[data-key="${k}"]`)?.value||0), show=(k,n,d=3)=>document.querySelectorAll(`[data-result="${k}"]`).forEach(el=>{el.textContent=fmt(n,d);el.classList.toggle('invalid',!Number.isFinite(n))});
 function syncReferences(){
  const sdChoice=form.querySelector('.sd-choice:checked');if(sdChoice){form.querySelector('[data-key="sd"]').value=sdChoice.value;document.querySelectorAll('#sdTable tbody tr').forEach(r=>r.classList.toggle('selected',r.contains(sdChoice)));}
  const choice=form.querySelector('.slump-choice:checked'),minInput=form.querySelector('[data-key="slump_min"]'),maxInput=form.querySelector('[data-key="slump_max"]'),design=form.querySelector('[data-key="slump_design"]');
  if(choice){minInput.value=choice.dataset.min;maxInput.value=choice.dataset.max;form.querySelector('[data-key="construction_type"]').value=choice.value;design.min=choice.dataset.min;design.max=choice.dataset.max;if(Number(design.value)<Number(choice.dataset.min)||Number(design.value)>Number(choice.dataset.max))design.value=choice.dataset.max;document.querySelectorAll('[data-slump-row]').forEach(r=>r.classList.toggle('selected',r.dataset.slumpRow===choice.value));}
  const formLimit=val('smallest_form_dimension')/5,slabLimit=val('slab_thickness')/3,rebarLimit=val('clear_rebar_spacing')*.75,structuralLimit=Math.min(formLimit,slabLimit,rebarLimit),testedAggregate=Number(@json((float)($coarse?->nominal_maximum_size ?? 0))),standardSizes=[9.5,12.7,19,25,37.5,50,75,150],permittedLimit=testedAggregate>0?Math.min(structuralLimit,testedAggregate):structuralLimit,selectedSize=standardSizes.filter(x=>x<=permittedLimit+.0001).at(-1)??9.5;
  form.querySelector('[data-key="max_size"]').value=selectedSize;document.querySelector('[data-aggregate-limit="form"]').textContent=fmt(formLimit,2);document.querySelector('[data-aggregate-limit="slab"]').textContent=fmt(slabLimit,2);document.querySelector('[data-aggregate-limit="rebar"]').textContent=fmt(rebarLimit,2);document.querySelector('[data-aggregate-limit="minimum"]').textContent=fmt(structuralLimit,2)+' mm';
  const size=String(val('max_size')),sizes=['9.5','12.7','19','25','37.5','50','75','150'],idx=sizes.indexOf(size),slump=val('slump_design'),range=slump<=50?0:(slump<=100?1:2),entrained=val('air_entrained')===1;
  const waterNoAir=[[207,199,190,179,166,154,130,113],[228,216,205,193,181,169,145,124],[243,228,216,202,190,178,160,124]];
  const waterAir=[[181,175,168,160,150,142,122,107],[202,193,184,175,165,157,133,119],[216,205,197,184,174,166,154,119]];
  const trapped=[3,2.5,2,1.5,1,.5,.3,.2],airModerate=[6,5.5,5,4.5,4.5,4,3.5,3],exposureAdjust=[-1.5,0,1.5],exposure=Math.max(0,Math.min(2,val('exposure_level')));
  if(idx>=0){form.querySelector('[data-key="water"]').value=(entrained?waterAir:waterNoAir)[range][idx];form.querySelector('[data-key="air_content"]').value=entrained?Math.max(3,airModerate[idx]+exposureAdjust[exposure]):trapped[idx];}
  document.querySelectorAll('[data-water-cell]').forEach(c=>c.classList.toggle('active-ref',c.dataset.waterCell===`${entrained?1:0}-${range}-${idx}`));
  const strengths=[15,20,25,30,35,40],normalFas=[.79,.69,.61,.54,.47,.42],airFas=[.70,.60,.52,.45,.39,.35],fasValues=entrained?airFas:normalFas,targetFcr=val('fc')+(val('sd')+val('sd_additional'))*val('deviation_factor');
  let lower=0,upper=0;for(let i=0;i<strengths.length;i++){if(strengths[i]<=targetFcr)lower=i;if(strengths[i]>=targetFcr){upper=i;break}upper=i}
  if(targetFcr<=strengths[0])lower=upper=0;if(targetFcr>=strengths.at(-1))lower=upper=strengths.length-1;
  const exact=Math.abs(targetFcr-strengths[lower])<.000001,fas=lower===upper?fasValues[lower]:fasValues[lower]+(targetFcr-strengths[lower])/(strengths[upper]-strengths[lower])*(fasValues[upper]-fasValues[lower]);
  form.querySelector('[data-key="wc_ratio"]').value=fas.toFixed(4);
  document.querySelectorAll('[data-fc-row]').forEach(row=>{const index=strengths.indexOf(Number(row.dataset.fcRow)),chosen=index===lower||index===upper;row.classList.toggle('selected',chosen);const status=row.querySelector('[data-wc-status]');status.textContent=!chosen?'—':(lower===upper||exact?'Sesuai':index===lower?'Batas bawah':'Batas atas');row.querySelectorAll('[data-wc-normal],[data-wc-air]').forEach(cell=>cell.classList.remove('active-ref'));if(chosen)row.querySelector(entrained?'[data-wc-air]':'[data-wc-normal]').classList.add('active-ref');});
  const wcInfo=document.getElementById('wcInterpolationInfo');if(wcInfo)wcInfo.textContent=lower===upper||exact?`Sesuai tabel pada ${strengths[lower]} MPa`:`Interpolasi ${strengths[lower]}–${strengths[upper]} MPa untuk f'cr ${targetFcr.toFixed(3)} MPa`;
  const fmColumns=[2.4,2.6,2.8,3],fm=val('fine_fm'),fmIndex=fmColumns.reduce((best,x,i)=>Math.abs(x-fm)<Math.abs(fmColumns[best]-fm)?i:best,0);
  document.querySelectorAll('[data-coarse-cell]').forEach(c=>c.classList.toggle('active-ref',c.dataset.coarseCell===`${size}-${fmIndex}`));
 const densities=[[2280,2310,2345,2380,2410,2445,2490,2530],[2200,2230,2275,2315,2350,2375,2420,2470]];
  if(idx>=0)form.querySelector('[data-key="fresh_density"]').value=densities[entrained?1:0][idx];
  document.querySelectorAll('[data-density-cell]').forEach(c=>c.classList.toggle('active-ref',c.dataset.densityCell===`${entrained?1:0}-${idx}`));
 }
 let gradationAnalyzed=false,gradationAnimating=false;
 const gradationTarget=(values,curve)=>{if(curve<=4)return values[curve-1]??null;const available=values.filter(value=>value!==null&&value!==undefined).map(Number);return available.length?available.reduce((sum,value)=>sum+value,0)/available.length:null};
 const activeGradationKeys=maxSize=>({10:['r095','r475','r236','r118','r060','r030','r015'],20:['r190','r095','r475','r236','r118','r060','r030','r015'],40:['r375','r190','r095','r475','r236','r118','r060','r030','r015']})[Number(maxSize)]||[];
 function updateGradationChart(limits,combinedValues,finePercent,coarsePercent,activeKeys){
  const chart=document.getElementById('gradationChart');if(!chart)return;const activeSet=new Set(activeKeys),rows=[...document.querySelectorAll('.combined-row')].filter(row=>activeSet.has(row.dataset.sieve)),left=70,right=890,top=24,bottom=350,width=right-left,height=bottom-top,x=index=>left+index*width/(rows.length-1),y=value=>bottom-Math.max(0,Math.min(100,Number(value)))*height/100;
  let grid='';for(let value=0;value<=100;value+=20){const py=y(value);grid+=`<line x1="${left}" y1="${py}" x2="${right}" y2="${py}"></line><text x="${left-10}" y="${py+4}" text-anchor="end">${value}</text>`;}rows.forEach((row,index)=>{const px=x(index),inch=row.children[0].textContent.trim(),mm=row.children[1].textContent.trim();grid+=`<line x1="${px}" y1="${top}" x2="${px}" y2="${bottom}"></line><text x="${px}" y="${bottom+18}" text-anchor="middle">${inch}</text><text x="${px}" y="${bottom+34}" text-anchor="middle">${mm} mm</text>`;});chart.querySelector('[data-chart-grid]').innerHTML=grid;
  const seriesPoints=values=>rows.map((row,index)=>{const value=values(row.dataset.sieve);return value===null||value===undefined||!Number.isFinite(Number(value))?null:`${x(index)},${y(value)}`;}).filter(Boolean).join(' ');
  for(let curve=1;curve<=4;curve++)chart.querySelector(`[data-chart-series="curve-${curve}"]`).setAttribute('points',seriesPoints(key=>(limits[key]||[])[curve-1]??null));
  chart.querySelector('[data-chart-series="average"]').setAttribute('points',seriesPoints(key=>gradationTarget(limits[key]||[],5)));
  const combinedPoints=seriesPoints(key=>combinedValues[key]);chart.querySelector('[data-chart-series="combined"]').setAttribute('points',combinedPoints);
  chart.querySelector('[data-chart-points]').innerHTML=rows.map((row,index)=>{const value=combinedValues[row.dataset.sieve];return Number.isFinite(value)?`<circle class="chart-point" cx="${x(index)}" cy="${y(value)}" r="4"></circle>`:'';}).join('');
  const composition=document.querySelector('[data-chart-composition]');if(composition)composition.textContent=`Pasir ${fmt(finePercent,1)}% · Kerikil ${fmt(coarsePercent,1)}%`;
 }
 function optimizeCombinedGradation(runSearch=false){
  if(!combinedMode)return val('combined_fine_percent');
  const maxSize=String(Math.round(val('gradation_max_size'))),activeKeys=activeGradationKeys(maxSize),activeSet=new Set(activeKeys),curve=Math.max(1,Math.min(5,Math.round(val('gradation_curve')))),limits=combinedLimits[maxSize]||{},rows=[...document.querySelectorAll('.combined-row')];
  document.querySelectorAll('[data-limit-sieve]').forEach(row=>{const active=activeSet.has(row.dataset.limitSieve);row.classList.toggle('d-none',!active);const values=limits[row.dataset.limitSieve]||[null,null,null,null],available=values.filter(value=>value!==null&&value!==undefined).map(Number),average=available.length?available.reduce((sum,value)=>sum+value,0)/available.length:null;row.querySelectorAll('.gradation-bound').forEach((cell,i)=>{const target=values[i];cell.textContent=target===null||target===undefined?'—':fmt(Number(target),2);cell.classList.toggle('active-ref',active&&curve===i+1&&target!==null);});const averageCell=row.querySelector('.gradation-average');averageCell.textContent=average===null?'—':fmt(average,2);averageCell.classList.toggle('active-ref',active&&curve===5&&average!==null);});
  let missing=0;rows.forEach(row=>{const active=activeSet.has(row.dataset.sieve);row.classList.toggle('d-none',!active);const values=limits[row.dataset.sieve]||[null,null,null,null],target=active?gradationTarget(values,curve):null,fine=row.dataset.fine===''?NaN:Number(row.dataset.fine),coarse=row.dataset.coarse===''?NaN:Number(row.dataset.coarse);row.dataset.target=target===null?'':target;row.querySelector('.combined-target').textContent=target===null?'—':fmt(Number(target),2);if(target!==null&&(!Number.isFinite(fine)||!Number.isFinite(coarse)))missing++;});
  const fineInput=form.querySelector('[data-key="combined_fine_percent"]');let finePercent=Math.max(0,Math.min(100,fineInput.value===''?50:Number(fineInput.value))),bestDeviation=NaN;
  if(runSearch&&missing===0){let bestFine=0,bestAverage=Infinity;for(let tenths=0;tenths<=1000;tenths++){const candidateFine=tenths/10,candidateCoarse=100-candidateFine;let deviationSum=0,count=0;rows.forEach(row=>{const fine=Number(row.dataset.fine),coarse=Number(row.dataset.coarse),target=row.dataset.target===''?NaN:Number(row.dataset.target);if(Number.isFinite(fine)&&Number.isFinite(coarse)&&Number.isFinite(target)){const combined=fine*candidateFine/100+coarse*candidateCoarse/100;deviationSum+=Math.abs(combined-target);count++;}});const average=count?deviationSum/count:Infinity;if(average<bestAverage-0.0000001){bestAverage=average;bestFine=candidateFine;}}finePercent=bestFine;bestDeviation=bestAverage;gradationAnalyzed=true;form.querySelector('[data-key="combined_fine_percent"]').value=finePercent.toFixed(1);}
  const coarsePercent=100-finePercent,combinedValues={};let deviationSum=0,deviationCount=0;rows.forEach(row=>{const fine=row.dataset.fine===''?NaN:Number(row.dataset.fine),coarse=row.dataset.coarse===''?NaN:Number(row.dataset.coarse),target=row.dataset.target===''?NaN:Number(row.dataset.target),fineWeighted=Number.isFinite(fine)?fine*finePercent/100:NaN,coarseWeighted=Number.isFinite(coarse)?coarse*coarsePercent/100:NaN,combined=Number.isFinite(fineWeighted)&&Number.isFinite(coarseWeighted)?fineWeighted+coarseWeighted:NaN,deviation=Number.isFinite(combined)&&Number.isFinite(target)?Math.abs(combined-target):NaN;combinedValues[row.dataset.sieve]=combined;row.querySelector('.fine-weighted').textContent=Number.isFinite(fineWeighted)?fmt(fineWeighted,2):'—';row.querySelector('.coarse-weighted').textContent=Number.isFinite(coarseWeighted)?fmt(coarseWeighted,2):'—';row.querySelector('.combined-passing').textContent=Number.isFinite(combined)?fmt(combined,2):'Belum lengkap';row.querySelector('.combined-row-deviation').textContent=Number.isFinite(deviation)?fmt(deviation,2):'—';if(Number.isFinite(deviation)){deviationSum+=deviation;deviationCount++;}});
  const averageDeviation=deviationCount?deviationSum/deviationCount:NaN;if(!Number.isFinite(bestDeviation))bestDeviation=averageDeviation;form.querySelector('[data-key="combined_deviation"]').value=Number.isFinite(bestDeviation)?bestDeviation.toFixed(4):'';document.querySelector('[data-combined-fine]').textContent=fmt(finePercent,1);document.querySelector('[data-combined-coarse]').textContent=fmt(coarsePercent,1);document.querySelector('[data-combined-total]').textContent=fmt(finePercent+coarsePercent,1);document.querySelector('[data-combined-deviation]').textContent=Number.isFinite(bestDeviation)?fmt(bestDeviation,4):'—';document.querySelector('[data-fine-header]').textContent=fmt(finePercent,1)+'%';document.querySelector('[data-coarse-header]').textContent=fmt(coarsePercent,1)+'%';document.querySelector('[data-combined-warning]')?.classList.toggle('d-none',missing===0);
  const status=document.querySelector('[data-combined-status]');if(status){status.className=(gradationAnalyzed&&missing===0?'analysis-ready':'analysis-pending')+' p-2';status.innerHTML=missing?'<b>Data belum lengkap.</b> Lengkapi hasil analisis saringan pasir dan kerikil.':(gradationAnalyzed?`<b>Analisis selesai.</b> Komposisi dipilih dari 1.001 percobaan dengan deviasi rata-rata terkecil ${fmt(bestDeviation,4)}.`:'<b>Tekan Analisis Gradasi.</b> Sistem akan mencoba komposisi 0,0% sampai 100,0% pasir dengan langkah 0,1%.');}updateGradationChart(limits,combinedValues,finePercent,coarsePercent,activeKeys);
  return finePercent;
 }
 async function animateCombinedGradation(){
  if(!combinedMode||gradationAnimating)return;const button=document.getElementById('analyzeGradation'),status=document.querySelector('[data-combined-status]'),fineInput=form.querySelector('[data-key="combined_fine_percent"]'),rows=[...document.querySelectorAll('.combined-row')];gradationAnalyzed=false;optimizeCombinedGradation(false);
  const targetRows=rows.filter(row=>row.dataset.target!==''),ready=targetRows.length>0&&targetRows.every(row=>Number.isFinite(Number(row.dataset.fine))&&Number.isFinite(Number(row.dataset.coarse)));if(!ready){optimizeCombinedGradation(true);return;}
  gradationAnimating=true;button.disabled=true;button.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Menganalisis...';fineInput.value='0.0';optimizeCombinedGradation(false);
  await new Promise(resolve=>{let tenths=0;const frame=()=>{tenths=Math.min(1000,tenths+5);fineInput.value=(tenths/10).toFixed(1);optimizeCombinedGradation(false);status.className='analysis-pending p-2';status.innerHTML=`<b>Analisis berjalan:</b> menguji ${fmt(tenths/10,1)}% pasir + ${fmt(100-tenths/10,1)}% kerikil. Perhitungan dilakukan setiap langkah 0,1%.`;if(tenths<1000)requestAnimationFrame(frame);else resolve();};requestAnimationFrame(frame);});
  optimizeCombinedGradation(true);calculate();gradationAnimating=false;button.disabled=false;button.innerHTML='<i class="bi bi-arrow-repeat me-1"></i>Analisis Ulang';
 }
 function calculate(){syncReferences();let cement=val('water')/val('wc_ratio'),margin=(val('sd')+val('sd_additional'))*val('deviation_factor'),fcr=val('fc')+margin;
  const bases={'9.5':.74,'12.7':.83,'19':.90,'25':.95,'37.5':.99,'50':1.02,'75':1.06,'150':1.11};let ratio,coarse,fineMass,vw=val('water')/1000,vc=cement/(val('cement_sg')*1000),va=val('air_content')/100,vg,vf,fine;
  let aggregateMassAvailable=val('fresh_density')-val('water')-cement;if(combinedMode){let fp=optimizeCombinedGradation(),cp=100-fp;fineMass=aggregateMassAvailable*fp/100;coarse=aggregateMassAvailable*cp/100;fine=fineMass;vg=coarse/(val('coarse_sg')*1000);vf=fine/(val('fine_sg')*1000);ratio=vg;}else{ratio=(bases[String(val('max_size'))]??NaN)-.1*Math.min(val('fine_fm'),3);coarse=val('coarse_density')*ratio;fineMass=val('fresh_density')-val('water')-cement-coarse;vg=coarse/(val('coarse_sg')*1000);vf=1-vw-vc-vg-va;fine=vf*val('fine_sg')*1000;}
  let ff=(val('fine_moisture')-val('fine_absorption'))/100*fine,cf=(val('coarse_moisture')-val('coarse_absorption'))/100*coarse,fField=fine*(1+val('fine_moisture')/100)/(1+val('fine_absorption')/100),cField=coarse*(1+val('coarse_moisture')/100)/(1+val('coarse_absorption')/100),water=Math.max(0,val('water')-ff-cf),factor=val('trial_volume_liter')/1000*(1+val('waste')/100);
  let r={margin,fcr,cement,aggregate_mass_available:aggregateMassAvailable,coarse_ratio:ratio,coarse_ssd:coarse,fine_mass_method:fineMass,vol_water:vw,vol_cement:vc,vol_coarse:vg,vol_air:va,vol_fine:vf,fine_ssd:fine,fine_free_water:ff,coarse_free_water:cf,fine_field:fField,coarse_field:cField,water_added:water,total_fresh_mass:cement+fField+cField+water,ratio_cement:1,ratio_fine:fField/cement,ratio_coarse:cField/cement,ratio_water:water/cement,trial_cement:cement*factor,trial_fine:fField*factor,trial_coarse:cField*factor,trial_water:water*factor,fine_per_sack:fField/(cement/50),coarse_per_sack:cField/(cement/50),water_per_sack:water/(cement/50)};
  Object.entries(r).forEach(([k,n])=>show(k,n,k.startsWith('vol_')||k.startsWith('ratio_')||k==='coarse_ratio'?4:3));
 }
 form.addEventListener('input',event=>{if(['gradation_max_size','gradation_curve'].includes(event.target.dataset.key))gradationAnalyzed=false;calculate();});document.getElementById('analyzeGradation')?.addEventListener('click',animateCombinedGradation);calculate();
 document.getElementById('projectSelector').addEventListener('change',e=>{if(e.target.value)location.href=`{{route($combined?'mix-design-2012-combined.create':'mix-design-2012.create')}}?project=${e.target.value}`});
})();
</script>
@endpush
