@extends('layouts.app') @section('title','Pemeriksaan '.$label) @section('subtitle','Form karakteristik material') @section('content')
<div class="d-flex justify-content-between align-items-start mb-4"><div><a class="text-decoration-none small" href="{{route('material-tests.index')}}"><i class="bi bi-arrow-left me-1"></i>Kembali ke semua material</a><h3 class="fw-bold mt-2">Pemeriksaan {{$label}}</h3><p class="text-secondary">Nilai kosong tidak dianggap nol. Isi hanya hasil pengujian yang tersedia.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{route('documentation.index',['module'=>$type])}}"><i class="bi bi-camera me-2"></i>Dokumentasi</a><span class="badge badge-soft align-self-center">Draf pemeriksaan</span></div></div>
<form method="post" action="{{route('material-tests.store',$type)}}">@csrf
<div class="card p-4 mb-4"><h5 class="fw-bold mb-3"><span class="badge rounded-pill text-bg-dark me-2">1</span>Identitas Sampel</h5><div class="row g-3">
<div class="col-md-6"><label class="form-label">Proyek *</label><select class="form-select" name="project_id" id="test-project" required><option value="">Pilih proyek</option>@foreach($projects as $project)<option value="{{$project->id}}" @selected(old('project_id')==$project->id)>{{$project->number}} — {{$project->name}}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Sampel / sumber / lokasi material</label><select class="form-select" name="material_source_id" id="test-source"><option value="">Pilih proyek terlebih dahulu</option>@foreach($materials as $material)<option value="{{$material->id}}" data-project="{{$material->project_id}}" data-code="{{$material->code}}" data-name="{{$material->name}}" data-quarry="{{$material->quarry ?: $material->producer}}" data-supplier="{{$material->supplier}}" data-sample="{{$material->sample_number}}" data-condition="{{$material->condition}}" @selected(old('material_source_id')==$material->id)>{{$material->code}} — {{$material->name}} — {{$material->quarry ?: ($material->producer ?: 'lokasi belum diisi')}}</option>@endforeach</select></div>
<div class="col-12"><div id="test-sample-list"></div></div>
<div class="col-12"><div class="border rounded p-3 bg-light"><div class="d-flex justify-content-between align-items-center mb-2"><b>Identitas sampel terpilih</b><span class="small text-secondary">Data dapat diperbaiki dan ikut tersimpan bersama pemeriksaan.</span></div><div class="row g-2">
<div class="col-md-4"><label class="form-label">Nama material</label><input class="form-control form-control-sm source-field" name="source_name" data-source-field="name"></div>
<div class="col-md-4"><label class="form-label">Lokasi sumber</label><input class="form-control form-control-sm source-field" name="source_quarry" data-source-field="quarry"></div>
<div class="col-md-4"><label class="form-label">Pemasok</label><input class="form-control form-control-sm source-field" name="source_supplier" data-source-field="supplier"></div>
<div class="col-md-4"><label class="form-label">Nomor sampel sumber</label><input class="form-control form-control-sm source-field" name="source_sample_number" data-source-field="sample"></div>
<div class="col-md-4"><label class="form-label">Kondisi material</label><input class="form-control form-control-sm source-field" name="source_condition" data-source-field="condition"></div>
</div></div></div>
<div class="col-md-4"><label class="form-label">Nomor sampel *</label><input class="form-control" name="sample_number" value="{{old('sample_number')}}" required></div>
<div class="col-md-4"><label class="form-label">Tanggal diterima</label><input type="date" class="form-control" name="received_at" value="{{old('received_at')}}"></div>
<div class="col-md-4"><label class="form-label">Tanggal pengujian *</label><input type="date" class="form-control" name="tested_at" value="{{old('tested_at',date('Y-m-d'))}}" required></div>
<div class="col-md-6"><label class="form-label">Petugas pengujian *</label><input class="form-control" name="technician" value="{{old('technician',auth()->user()->name)}}" required></div>
</div></div>
<div class="card p-4 mb-4"><h5 class="fw-bold mb-3"><span class="badge rounded-pill text-bg-dark me-2">2</span>Karakteristik {{$label}}</h5><div class="row g-3">
@foreach($fields as $field)<div class="col-md-6"><label class="form-label">{{$field['label']}}{{$field['required']?' *':''}}</label><div class="input-group"><input class="form-control" name="{{$field['name']}}" value="{{old($field['name'])}}" {{$field['required']?'required':''}} @if(str_contains($field['rule'],'numeric')) type="number" step="any" @endif>@if($field['unit'])<span class="input-group-text">{{$field['unit']}}</span>@endif</div></div>@endforeach
<div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes" rows="3">{{old('notes')}}</textarea></div></div></div>
<div class="card p-3"><div class="d-flex justify-content-between align-items-center"><div class="small text-secondary"><i class="bi bi-shield-check me-1"></i>Status memenuhi akan ditentukan setelah batas referensi resmi tersedia.</div><div><a class="btn btn-light me-2" href="{{route('material-tests.index')}}">Batal</a><button class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan Draf</button></div></div></div>
</form>@endsection
@push('scripts')<script>
(()=>{const project=document.getElementById('test-project'),source=document.getElementById('test-source'),all=[...source.options].slice(1).map(o=>({value:o.value,text:o.textContent,project:o.dataset.project,...o.dataset}));
function selectSource(){const item=all.find(x=>x.value===source.value);document.querySelectorAll('.source-field').forEach(input=>input.value=item?.[input.dataset.sourceField]||'');if(item?.sample&&!document.querySelector('[name="sample_number"]').value)document.querySelector('[name="sample_number"]').value=item.sample;}
function renderSources(items){const host=document.getElementById('test-sample-list');host.innerHTML='';if(!project.value)return;if(!items.length){host.innerHTML='<div class="alert alert-warning mb-0">Belum ada sampel material untuk proyek ini.</div>';return}const title=document.createElement('div');title.className='small fw-bold mb-2';title.textContent=`Semua sampel/lokasi yang tersedia (${items.length})`;host.appendChild(title);const row=document.createElement('div');row.className='row g-2';items.forEach(item=>{const col=document.createElement('div');col.className='col-md-6 col-xl-4';const card=document.createElement('button');card.type='button';card.className='btn btn-outline-secondary text-start w-100 h-100 source-card';card.dataset.id=item.value;card.innerHTML='<b></b><div class="small mt-1 source-location"></div><div class="small text-secondary source-meta"></div>';card.querySelector('b').textContent=`${item.code||''} — ${item.name||''}`;card.querySelector('.source-location').textContent=`Lokasi: ${item.quarry||'belum diisi'}`;card.querySelector('.source-meta').textContent=`Sampel: ${item.sample||'-'} • Pemasok: ${item.supplier||'-'}`;card.addEventListener('click',()=>{source.value=item.value;selectSource();document.querySelectorAll('.source-card').forEach(x=>x.classList.toggle('btn-primary',x.dataset.id===item.value));});col.appendChild(card);row.appendChild(col)});host.appendChild(row);}
function filterSources(keep=true){const selected=keep?source.value:'';source.innerHTML='<option value="">Pilih sampel / lokasi</option>';const matches=all.filter(x=>!x.project||x.project===project.value);matches.forEach(x=>{const o=new Option(x.text,x.value);Object.entries(x).forEach(([k,v])=>{if(!['text','value'].includes(k))o.dataset[k]=v??''});source.add(o)});renderSources(matches);if([...source.options].some(o=>o.value===selected))source.value=selected;else if(matches.length===1)source.value=matches[0].value;selectSource();}
project.addEventListener('change',()=>filterSources(false));source.addEventListener('change',selectSource);filterSources(true);
})();
</script>@endpush
