@extends('layouts.app') @section('title',$config['label']) @section('subtitle',$config['standard']) @section('content')
<a href="{{route('aggregate-tests.menu',$aggregate)}}" class="small text-decoration-none"><i class="bi bi-arrow-left me-1"></i>Daftar pengujian</a>
<div class="d-flex justify-content-between mt-2 mb-4"><div><h3 class="fw-bold mb-1">{{$config['label']}}</h3><p class="text-secondary mb-0">{{$aggregate==='fine'?'Agregat Halus / Pasir':'Agregat Kasar / Kerikil'}} • {{$config['standard']}}</p></div><button type="button" class="btn btn-outline-primary align-self-start" id="add-observation"><i class="bi bi-plus-lg me-2"></i>Tambah Observasi</button></div>
<form method="post" action="{{route('aggregate-tests.store',[$aggregate,$test])}}">@csrf
<div class="card p-4 mb-4"><div class="row g-3"><div class="col-md-6"><label class="form-label">Proyek *</label><select class="form-select" name="project_id" id="single-test-project" required><option value="">Pilih proyek</option>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->number}} — {{$p->name}}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Sumber material</label><select class="form-select" name="material_source_id" id="single-test-source"><option value="">Pilih sumber</option>@foreach($materials as $m)<option value="{{$m->id}}" data-project="{{$m->project_id}}">{{$m->code}} — {{$m->name}}</option>@endforeach</select></div>
<div class="col-12"><div id="single-test-loaded" class="alert alert-info mb-0 d-none"></div></div>
<div class="col-md-4"><label class="form-label">Nomor sampel *</label><input class="form-control" name="sample_number" required></div><div class="col-md-4"><label class="form-label">Tanggal uji *</label><input type="date" class="form-control" name="tested_at" value="{{date('Y-m-d')}}" required></div><div class="col-md-4"><label class="form-label">Petugas *</label><input class="form-control" name="technician" value="{{auth()->user()->name}}" required></div></div></div>
<div class="card overflow-hidden mb-4"><div class="p-3 border-bottom d-flex justify-content-between"><b>Data Pengujian</b><span class="small text-secondary">Salin blok Excel, klik sel awal, lalu tempel (Ctrl+V)</span></div><div class="table-responsive"><table class="table table-bordered align-middle mb-0" id="observation-table" data-excel-paste data-excel-grow="columns" data-excel-add="#add-observation"><thead><tr><th style="min-width:330px">Parameter</th><th class="text-center observation-head" style="min-width:190px"><span class="observation-title">Observasi I</span><button type="button" class="btn btn-sm btn-link text-danger remove-single-observation" title="Hapus Observasi"><i class="bi bi-trash"></i></button><input type="hidden" class="single-observation-id" name="observations[0][id]"></th></tr></thead><tbody>
@foreach($config['fields'] as [$name,$label,$unit])<tr><td><span class="badge text-bg-secondary me-2">{{chr(64+$loop->iteration)}}</span><b>{{$label}}</b>@if($unit)<span class="text-secondary small ms-1">({{$unit}})</span>@endif</td><td class="observation-cell"><input type="number" step="any" min="0" class="form-control text-end" name="observations[0][{{$name}}]"></td></tr>@endforeach
</tbody></table></div><div class="p-3 border-top bg-light"><b class="small">Alur perhitungan</b>@if($test==='sieve')<div class="small text-secondary mt-2">MT = jumlah seluruh massa tertahan; Selisih = A − MT; % kumulatif = massa tertahan kumulatif / A × 100; FM = jumlah % kumulatif saringan standar / 100.</div>@else<div class="row g-2 mt-1">@foreach($config['process'] as [$key,$code,$label,$formula,$unit])<div class="col-md-6"><div class="border rounded bg-white p-2 h-100"><span class="badge text-bg-primary me-1">{{$code}}</span><b class="small">{{$label}}</b><div class="small text-secondary mt-1">{{$code}} = {{$formula}}{{$unit?' ('.$unit.')':''}}</div></div></div>@endforeach</div>@endif</div></div>
<div class="card p-4 mb-4"><label class="form-label">Catatan</label><textarea class="form-control" name="notes"></textarea></div><div class="text-end"><button class="btn btn-primary btn-lg"><i class="bi bi-calculator me-2"></i>Hitung dan Simpan</button></div></form>
@endsection
@push('scripts')<script>
let observationCount=1,singleRunId=''; const roman=n=>['I','II','III','IV','V','VI','VII','VIII','IX','X'][n-1]||n,singleDeleteUrl={{ Illuminate\Support\Js::from(route('aggregate-tests.observations.destroy',['project'=>'__PROJECT__','run'=>'__RUN__','observation'=>'__OBS__'])) }},singleSavedRuns=@json($savedRuns),singleProject=document.getElementById('single-test-project'),singleSource=document.getElementById('single-test-source'),singleSources=[...singleSource.options].slice(1).map(option=>({value:option.value,text:option.textContent,project:option.dataset.project})),singleDefaults={testedAt:document.querySelector('[name="tested_at"]').value,technician:document.querySelector('[name="technician"]').value};
function addObservation(){
 observationCount++; const table=document.getElementById('observation-table');
 const th=document.createElement('th'); th.className='text-center observation-head'; th.style.minWidth='190px'; th.innerHTML=`<span class="observation-title">Observasi ${roman(observationCount)}</span><button type="button" class="btn btn-sm btn-link text-danger remove-single-observation" title="Hapus Observasi"><i class="bi bi-trash"></i></button><input type="hidden" class="single-observation-id" name="observations[${observationCount-1}][id]">`; table.tHead.rows[0].appendChild(th);
 [...table.tBodies[0].rows].forEach(row=>{const source=row.querySelector('input');const td=document.createElement('td');td.className='observation-cell';const input=source.cloneNode();input.value='';input.name=source.name.replace(/observations\[\d+\]/,`observations[${observationCount-1}]`);td.appendChild(input);row.appendChild(td);});
}
document.getElementById('add-observation').addEventListener('click',addObservation);
function loadSingleSavedRun(){const project=singleProject.value,source=singleSource.value,info=document.getElementById('single-test-loaded');if(!project){info.classList.add('d-none');return}const run=singleSavedRuns[`${project}-${source||0}`]||(!source?singleSavedRuns[`${project}-any`]:null),observations=run?.observations||[],wanted=Math.max(1,observations.length),table=document.getElementById('observation-table');singleRunId=run?.id||'';while(observationCount<wanted)addObservation();while(observationCount>wanted){table.tHead.rows[0].lastElementChild.remove();[...table.tBodies[0].rows].forEach(row=>row.lastElementChild.remove());observationCount--}table.querySelectorAll('.observation-head').forEach((head,index)=>{head.querySelector('.single-observation-id').value=observations[index]?.id||'';head.querySelector('.remove-single-observation').dataset.observationId=observations[index]?.id||''});table.tBodies[0].querySelectorAll('tr').forEach(row=>row.querySelectorAll('input[type="number"]').forEach((input,index)=>input.value=observations[index]?.[input.name.match(/\[([^\]]+)\]$/)?.[1]]??''));document.querySelector('[name="sample_number"]').value=run?.sample_number||'';document.querySelector('[name="tested_at"]').value=run?.tested_at||singleDefaults.testedAt;document.querySelector('[name="technician"]').value=run?.technician||singleDefaults.technician;document.querySelector('[name="notes"]').value=run?.notes||'';info.classList.remove('d-none');info.innerHTML=run?`<b>Data ${run.number} dimuat kembali ke kolom input.</b> Anda dapat melanjutkan atau memperbaikinya.`:'Proyek ini belum memiliki data pemeriksaan tersimpan. Silakan isi data baru.'}
function filterSingleSources(){const current=singleSource.value;singleSource.innerHTML='<option value="">Pilih sumber</option>';singleSources.filter(item=>!item.project||item.project===singleProject.value).forEach(item=>singleSource.add(new Option(item.text,item.value)));if([...singleSource.options].some(option=>option.value===current))singleSource.value=current;loadSingleSavedRun()}
singleProject.addEventListener('change',filterSingleSources);singleSource.addEventListener('change',loadSingleSavedRun);filterSingleSources();
function reindexSingle(){const table=document.getElementById('observation-table');observationCount=table.querySelectorAll('.observation-head').length;table.querySelectorAll('.observation-head').forEach((head,index)=>{head.querySelector('.observation-title').textContent='Observasi '+roman(index+1);head.querySelector('.single-observation-id').name=`observations[${index}][id]`});table.tBodies[0].querySelectorAll('tr').forEach(row=>row.querySelectorAll('input[type="number"]').forEach((input,index)=>input.name=input.name.replace(/observations\[\d+\]/,`observations[${index}]`)))}
function removeSingle(index){const table=document.getElementById('observation-table');table.querySelectorAll('.observation-head')[index].remove();[...table.tBodies[0].rows].forEach(row=>row.children[index+1].remove());reindexSingle()}
document.getElementById('observation-table').addEventListener('click',async event=>{const button=event.target.closest('.remove-single-observation');if(!button)return;const heads=[...document.querySelectorAll('.observation-head')];if(heads.length<=1){alert('Minimal satu observasi harus tetap tersedia.');return}const index=heads.indexOf(button.closest('.observation-head')),id=button.dataset.observationId;if(!id){removeSingle(index);return}if(!confirm(`Hapus Observasi ${roman(index+1)}?`))return;button.disabled=true;try{const response=await fetch(singleDeleteUrl.replace('__PROJECT__',singleProject.value).replace('__RUN__',singleRunId).replace('__OBS__',id),{method:'DELETE',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'}}),payload=await response.json();if(!response.ok)throw new Error(payload.message||'Observasi gagal dihapus.');const run=Object.values(singleSavedRuns).find(item=>String(item.id)===String(singleRunId));if(run)run.observations.splice(index,1);removeSingle(index)}catch(error){alert(error.message);button.disabled=false}});
</script>@endpush
