@extends('layouts.app') @section('title',$aggregate==='fine'?'Lembar Pengujian Pasir':'Lembar Pengujian Kerikil') @section('subtitle','Seluruh pengujian dalam satu tampilan') @section('content')
<div class="d-flex justify-content-between mb-4"><div><a href="{{route('material-tests.index')}}" class="small text-decoration-none"><i class="bi bi-arrow-left me-1"></i>Semua material</a><h3 class="fw-bold mt-2 mb-1">{{$aggregate==='fine'?'Pemeriksaan Agregat Halus / Pasir':'Pemeriksaan Agregat Kasar / Kerikil'}}</h3><p class="text-secondary">Isi data yang tersedia. Data yang belum lengkap dapat disimpan sebagai draf dan dilanjutkan nanti.</p></div><div class="d-flex gap-2"><a href="{{route('documentation.index',['module'=>$aggregate==='fine'?'fine-aggregate':'coarse-aggregate'])}}" class="btn btn-outline-primary align-self-start"><i class="bi bi-camera me-2"></i>Dokumentasi</a></div></div>
<form method="post" action="{{route('aggregate-tests.worksheet.store',$aggregate)}}" id="worksheet-form">@csrf
<div class="card p-4 mb-4"><h5 class="fw-bold mb-3">Identitas Pemeriksaan</h5><div class="row g-3">
<div class="col-md-6"><label class="form-label">Proyek *</label><select class="form-select" name="project_id" id="worksheet-project" required><option value="">Pilih proyek</option>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->number}} — {{$p->name}}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Sampel / sumber / lokasi material</label><select class="form-select" name="material_source_id" id="worksheet-source"><option value="">Pilih proyek terlebih dahulu</option>@foreach($materials as $m)<option value="{{$m->id}}" data-project="{{$m->project_id}}" data-code="{{$m->code}}" data-name="{{$m->name}}" data-quarry="{{$m->quarry ?: $m->producer}}" data-supplier="{{$m->supplier}}" data-sample="{{$m->sample_number}}" data-condition="{{$m->condition}}">{{$m->code}} — {{$m->name}} — {{$m->quarry ?: ($m->producer ?: 'lokasi belum diisi')}}</option>@endforeach</select></div>
<div class="col-12"><div id="worksheet-sample-list"></div></div>
<div class="col-12"><div id="loaded-test-info" class="alert alert-info mb-0 d-none"></div></div>
<div class="col-12"><div class="border rounded p-3 bg-light"><div class="d-flex justify-content-between mb-2"><b>Identitas sampel terpilih</b><span class="small text-secondary">Dapat diubah dan disimpan bersama hasil pemeriksaan.</span></div><div class="row g-2"><div class="col-md-4"><label class="form-label">Nama material</label><input class="form-control form-control-sm worksheet-source-field" name="source_name" data-source-field="name"></div><div class="col-md-4"><label class="form-label">Lokasi sumber</label><input class="form-control form-control-sm worksheet-source-field" name="source_quarry" data-source-field="quarry"></div><div class="col-md-4"><label class="form-label">Pemasok</label><input class="form-control form-control-sm worksheet-source-field" name="source_supplier" data-source-field="supplier"></div><div class="col-md-4"><label class="form-label">Nomor sampel sumber</label><input class="form-control form-control-sm worksheet-source-field" name="source_sample_number" data-source-field="sample"></div><div class="col-md-4"><label class="form-label">Kondisi material</label><input class="form-control form-control-sm worksheet-source-field" name="source_condition" data-source-field="condition"></div></div></div></div>
<div class="col-md-4"><label class="form-label">Nomor sampel *</label><input class="form-control" name="sample_number" required></div><div class="col-md-4"><label class="form-label">Tanggal uji *</label><input type="date" class="form-control" name="tested_at" value="{{date('Y-m-d')}}" required></div><div class="col-md-4"><label class="form-label">Petugas *</label><input class="form-control" name="technician" value="{{auth()->user()->name}}" required></div></div></div>
@foreach($tests as $slug=>$test)<section class="card overflow-hidden mb-4 test-section" data-test="{{$slug}}" data-aggregate="{{$aggregate}}">
<div class="p-3 border-bottom d-flex justify-content-between align-items-center bg-light"><div><b class="fs-5">{{$loop->iteration}}. {{$test['label']}}</b><div class="small text-secondary">{{$test['standard']}}</div></div><button type="button" class="btn btn-sm btn-outline-primary add-observation"><i class="bi bi-plus-lg me-1"></i>Tambah Observasi</button></div>
@if($slug==='sieve')
<input type="hidden" class="sieve-observation-id" name="runs[sieve][observations][0][id]">
<div class="p-3 bg-warning-subtle border-bottom"><div class="row align-items-end g-3"><div class="col-md-4"><label class="form-label">{{$aggregate==='fine'?'Zona gradasi pasir':'Ukuran maksimum agregat kasar'}}</label><select class="form-select" id="selected-zone" name="runs[sieve][observations][0][selected_zone]">@if($aggregate==='fine')<option value="1">Zona I — kasar</option><option value="2">Zona II — sedang</option><option value="3">Zona III — agak halus</option><option value="4">Zona IV — halus</option>@else<option value="1">Ukuran maksimum 10 mm</option><option value="2">Ukuran maksimum 20 mm</option><option value="3">Ukuran maksimum 40 mm</option>@endif<option value="all">Semua Gradasi</option></select></div><div class="col-md-4"><label class="form-label">Massa sampel awal</label><div class="input-group"><input type="number" min="0.001" step="any" class="form-control sieve-sample-mass bg-light" name="runs[sieve][observations][0][sample_mass]" readonly><span class="input-group-text">g</span></div><div class="small text-secondary mt-1">Otomatis dari total massa tertahan. Data belum lengkap tetap dapat disimpan sebagai draf.</div></div><div class="col-md-4 small text-secondary">Grafik menampilkan batas sesuai pilihan. Pilih Semua Gradasi untuk membandingkan seluruh batas sekaligus.</div></div></div>
<div class="table-responsive"><table class="table table-bordered table-sm align-middle mb-0 sieve-table" data-excel-paste><thead><tr class="text-center"><th rowspan="2">Saringan</th><th rowspan="2">mm</th><th rowspan="2"><span class="badge text-bg-secondary">A</span><br>Massa Saringan (g)</th><th rowspan="2"><span class="badge text-bg-secondary">B</span><br>Saringan + Benda Uji (g)</th><th rowspan="2"><span class="badge text-bg-primary">C</span><br>Massa Tertahan<br><small>(B − A)</small></th><th rowspan="2"><span class="badge text-bg-primary">D</span><br>% Tertahan<br><small>(C / total C × 100)</small></th><th rowspan="2"><span class="badge text-bg-primary">E</span><br>% Kumulatif<br><small>(ΣD)</small></th><th rowspan="2"><span class="badge text-bg-primary">F</span><br>% Lolos<br><small>(100 − E)</small></th>@for($z=1;$z<=($aggregate==='fine'?4:3);$z++)<th colspan="2">{{$aggregate==='fine'?'Zona '.$z:['Maks. 10 mm','Maks. 20 mm','Maks. 40 mm'][$z-1]}}</th>@endfor</tr><tr class="text-center">@for($z=1;$z<=($aggregate==='fine'?4:3);$z++)<th>Bawah</th><th>Atas</th>@endfor</tr></thead><tbody>
@php
$sieves=$aggregate==='fine'?[['3/8 in','9.5','r095'],['No.4','4.75','r475'],['No.8','2.36','r236'],['No.16','1.18','r118'],['No.30','0.60','r060'],['No.50','0.30','r030'],['No.100','0.15','r015'],['Wadah dasar','0','pan']]:[['SNI 76 / 3 in','75','r750'],['SNI 38 / 1½ in','37.5','r375'],['SNI 19 / ¾ in','19','r190'],['SNI 9,6 / ⅜ in','9.5','r095'],['No.4','4.75','r475'],['Wadah dasar','0','pan']];
$fineLimits=['r095'=>[[100,100],[100,100],[100,100],[100,100]],'r475'=>[[90,100],[90,100],[90,100],[95,100]],'r236'=>[[60,95],[75,100],[85,100],[95,100]],'r118'=>[[30,70],[55,90],[75,100],[90,100]],'r060'=>[[15,34],[35,59],[60,79],[80,100]],'r030'=>[[5,20],[8,30],[12,40],[15,50]],'r015'=>[[0,10],[0,10],[0,10],[0,15]],'pan'=>[[0,0],[0,0],[0,0],[0,0]]];
$coarseLimits=['r750'=>[['',''],['',''],[100,100]],'r375'=>[['',''],[100,100],[95,100]],'r190'=>[[100,100],[95,100],[35,70]],'r095'=>[[50,85],[30,60],[10,40]],'r475'=>[[0,10],[0,10],[0,5]],'pan'=>[[0,0],[0,0],[0,0]]];
$activeLimits=$aggregate==='fine'?$fineLimits:$coarseLimits;
$zoneCount=$aggregate==='fine'?4:3;
$gradationNames=$aggregate==='fine'?['Zona I','Zona II','Zona III','Zona IV']:['Maks. 10 mm','Maks. 20 mm','Maks. 40 mm'];
@endphp
@foreach($sieves as [$number,$size,$key])<tr data-sieve="{{$key}}" data-size="{{$size}}"><td class="text-center">{{$number}}</td><td class="text-center">{{$size}}</td><td><input type="number" min="0" step="any" class="form-control form-control-sm sieve-empty" name="runs[sieve][observations][0][{{$key}}_sieve_mass]"></td><td><input type="number" min="0" step="any" class="form-control form-control-sm sieve-combined" name="runs[sieve][observations][0][{{$key}}_combined_mass]"></td><td class="text-end sieve-retained">0,00<input type="hidden" name="runs[sieve][observations][0][{{$key}}]" value="0"></td><td class="text-end sieve-percent">0,00</td><td class="text-end sieve-cumulative">0,00</td><td class="text-end fw-bold sieve-passing">100,00</td>@for($z=1;$z<=$zoneCount;$z++)<td><input type="number" min="0" max="100" step="any" class="form-control form-control-sm zone-bound" data-zone="{{$z}}" data-kind="lower" name="runs[sieve][observations][0][zone_{{$z}}_{{$key}}_lower]" value="{{$activeLimits[$key][$z-1][0]??''}}"></td><td><input type="number" min="0" max="100" step="any" class="form-control form-control-sm zone-bound" data-zone="{{$z}}" data-kind="upper" name="runs[sieve][observations][0][zone_{{$z}}_{{$key}}_upper]" value="{{$activeLimits[$key][$z-1][1]??''}}"></td>@endfor</tr>@endforeach
</tbody><tfoot><tr class="table-secondary"><th colspan="4">Total massa tertahan (ΣC)</th><th class="text-end sieve-total">0,00</th><th colspan="2"></th><th class="text-end"><span class="badge text-bg-dark">FM</span> <span class="sieve-fm">0,000</span></th><th colspan="8"></th></tr></tfoot></table></div>
<div class="p-3 border-top bg-light"><b class="small">Alur perhitungan:</b> <span class="small text-secondary">C = B − A; D = C / total C × 100; E = jumlah D berjalan; F = 100 − E; FM = jumlah E pada saringan standar / 100.</span></div>
<div class="p-4"><canvas id="gradation-chart" height="95"></canvas></div>
@else
<div class="table-responsive"><table class="table table-bordered align-middle mb-0 observation-table" data-excel-paste data-excel-grow="columns"><thead><tr><th style="min-width:330px">Data Pengujian <div class="excel-paste-hint text-lowercase">tempel blok dari Excel mulai dari sel pertama</div></th><th class="text-center obs-head" style="min-width:200px"><span class="obs-title">Observasi I</span><button type="button" class="btn btn-sm btn-link text-danger remove-observation ms-1" title="Hapus Observasi"><i class="bi bi-trash"></i></button><input type="hidden" class="observation-record-id" name="runs[{{$slug}}][observations][0][id]"></th><th class="text-center average-head table-dark" style="min-width:200px">Hasil Rata-rata</th></tr></thead><tbody class="input-rows">
@foreach($test['fields'] as [$name,$label,$unit])<tr data-field="{{$name}}"><td><span class="badge text-bg-secondary me-2">{{chr(64+$loop->iteration)}}</span>{{$label}} @if($unit)<span class="text-secondary small">({{$unit}})</span>@endif</td><td><input type="number" min="0" step="any" class="form-control text-end observation-input" name="runs[{{$slug}}][observations][0][{{$name}}]"></td><td class="average-placeholder bg-light text-center text-secondary">—</td></tr>@endforeach
</tbody><tbody class="result-rows border-top border-3">@foreach($test['process'] as [$key,$code,$label,$formula,$unit])<tr data-result="{{$key}}"><td class="bg-light"><span class="badge text-bg-primary me-2">{{$code}}</span><b>{{$label}}</b><div class="small text-secondary ms-5">{{$code}} = {{$formula}}{{$unit?' ('.$unit.')':''}}</div></td><td class="text-end result-value">—</td><td class="text-end average-value table-success fw-bold">—</td></tr>@endforeach
</tbody></table></div>
@endif
</section>@endforeach
<div class="card p-4 mb-4"><label class="form-label">Catatan keseluruhan</label><textarea class="form-control" name="notes" rows="3"></textarea></div>
<div class="sticky-bottom bg-white border-top p-3 text-end" style="margin:0 -28px -28px"><button class="btn btn-primary btn-lg"><i class="bi bi-save me-2"></i>Simpan Semua Hasil</button></div></form>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>
const savedTestRuns=@json($savedRuns),observationDeleteUrl={{ Illuminate\Support\Js::from(route('aggregate-tests.observations.destroy',['project'=>'__PROJECT__','run'=>'__RUN__','observation'=>'__OBS__'])) }},worksheetProject=document.getElementById('worksheet-project'),worksheetSource=document.getElementById('worksheet-source'),worksheetSources=[...worksheetSource.options].slice(1).map(o=>({value:o.value,text:o.textContent,project:o.dataset.project,...o.dataset}));
const worksheetDefaults={testedAt:document.querySelector('[name="tested_at"]').value,technician:document.querySelector('[name="technician"]').value};
function loadSavedTests(){
 const project=worksheetProject.value,source=worksheetSource.value,info=document.getElementById('loaded-test-info');
 if(!project){info.classList.add('d-none');return}
 const selectedSource=worksheetSources.find(item=>item.value===source);
 document.querySelector('[name="sample_number"]').value=selectedSource?.sample||'';
 document.querySelector('[name="tested_at"]').value=worksheetDefaults.testedAt;
 document.querySelector('[name="technician"]').value=worksheetDefaults.technician;
 document.querySelector('[name="notes"]').value='';
 let loaded=[];
 document.querySelectorAll('.test-section').forEach(section=>{
  const run=savedTestRuns[`${project}-${source||0}-${section.dataset.test}`]||(!source?savedTestRuns[`${project}-any-${section.dataset.test}`]:null),observations=run?.observations||[];
  if(section.dataset.test!=='sieve'){
   const wanted=Math.max(1,observations.length);
   while(section.querySelectorAll('.obs-head').length>wanted){const heads=[...section.querySelectorAll('.obs-head')],index=heads.length-1;heads[index].remove();section.querySelectorAll('.input-rows tr,.result-rows tr[data-result]').forEach(row=>row.children[index+1]?.remove())}
   while(section.querySelectorAll('.obs-head').length<wanted)section.querySelector('.add-observation').click();
   section.dataset.runId=run?.id||'';
   section.querySelectorAll('.obs-head').forEach((head,index)=>{head.querySelector('.observation-record-id').value=observations[index]?.id||'';head.querySelector('.remove-observation').dataset.observationId=observations[index]?.id||''});
   section.querySelectorAll('.input-rows tr').forEach(row=>row.querySelectorAll('input').forEach((input,i)=>input.value=observations[i]?.[row.dataset.field]??''));
   recalc(section);
  }else{
   const observation=observations[0]||{};
   section.querySelectorAll('.sieve-empty,.sieve-combined').forEach(input=>input.value='');
   section.querySelectorAll('input,select').forEach(input=>{const match=input.name?.match(/\[([^\]]+)\]$/);if(match&&observation[match[1]]!==undefined)input.value=observation[match[1]]});
   recalcSieve();
  }
  if(run){loaded.push(`${section.querySelector('.fs-5')?.textContent.trim()||section.dataset.test} (${run.number})`);document.querySelector('[name="sample_number"]').value=run.sample_number||'';document.querySelector('[name="tested_at"]').value=run.tested_at||worksheetDefaults.testedAt;document.querySelector('[name="technician"]').value=run.technician||worksheetDefaults.technician;document.querySelector('[name="notes"]').value=run.notes||''}
 });
 if(loaded.length){info.innerHTML='<b>Data pemeriksaan tersimpan dimuat kembali ke kolom input:</b> '+loaded.join(', ')+'. Anda dapat melanjutkan atau memperbaiki nilainya.';info.classList.remove('d-none')}
 else{info.textContent='Proyek ini belum memiliki data pemeriksaan tersimpan. Silakan isi data baru.';info.classList.remove('d-none')}
}
function showWorksheetSource(){const item=worksheetSources.find(x=>x.value===worksheetSource.value);document.querySelectorAll('.worksheet-source-field').forEach(input=>input.value=item?.[input.dataset.sourceField]||'');if(item?.sample)document.querySelector('[name="sample_number"]').value=item.sample;loadSavedTests();}
function renderWorksheetSources(items){const host=document.getElementById('worksheet-sample-list');host.innerHTML='';if(!worksheetProject.value)return;if(!items.length){host.innerHTML='<div class="alert alert-warning mb-0">Belum ada sampel material untuk proyek ini. Tambahkan terlebih dahulu pada Sumber Material.</div>';return}const title=document.createElement('div');title.className='small fw-bold mb-2';title.textContent=`Semua sampel/lokasi yang tersedia (${items.length})`;host.appendChild(title);const row=document.createElement('div');row.className='row g-2';items.forEach(item=>{const col=document.createElement('div');col.className='col-md-6 col-xl-4';const card=document.createElement('button');card.type='button';card.className='btn btn-outline-secondary text-start w-100 h-100 sample-card';card.dataset.id=item.value;card.innerHTML=`<b></b><div class="small mt-1 sample-location"></div><div class="small text-secondary sample-meta"></div>`;card.querySelector('b').textContent=`${item.code||''} — ${item.name||''}`;card.querySelector('.sample-location').textContent=`Lokasi: ${item.quarry||'belum diisi'}`;card.querySelector('.sample-meta').textContent=`Sampel: ${item.sample||'-'} • Pemasok: ${item.supplier||'-'}`;card.addEventListener('click',()=>{worksheetSource.value=item.value;showWorksheetSource();document.querySelectorAll('.sample-card').forEach(x=>x.classList.toggle('btn-primary',x.dataset.id===item.value));});col.appendChild(card);row.appendChild(col)});host.appendChild(row);}
function filterWorksheetSources(){worksheetSource.innerHTML='<option value="">Pilih sampel / lokasi</option>';const matches=worksheetSources.filter(x=>!x.project||x.project===worksheetProject.value);matches.forEach(x=>{const o=new Option(x.text,x.value);Object.entries(x).forEach(([k,v])=>{if(!['text','value'].includes(k))o.dataset[k]=v??''});worksheetSource.add(o)});renderWorksheetSources(matches);if(matches.length===1)worksheetSource.value=matches[0].value;showWorksheetSource();}
worksheetProject.addEventListener('change',filterWorksheetSources);worksheetSource.addEventListener('change',showWorksheetSource);
const roman=n=>['I','II','III','IV','V','VI','VII','VIII','IX','X'][n-1]||n;
function calculate(test,agg,v){let d;
 if(test==='moisture'&&(d=v.dry_container-v.container)>0){let wet=v.wet_container-v.container;return {wet_sample:wet,dry_sample:d,moisture:(wet-d)/d*100};}
 if(test==='silt'&&v.dry_before>0){let lost=v.dry_before-v.dry_after;return {mass_lost:lost,silt:lost/v.dry_before*100};}
 if(test==='specific-gravity'&&agg==='fine'&&(d=v.pyc_water+v.ssd-v.pyc_sample_water)>0&&v.oven_dry>0)return {displaced:d,bulk_dry:v.oven_dry/d,bulk_ssd:v.ssd/d,apparent:v.oven_dry/(v.pyc_water+v.oven_dry-v.pyc_sample_water),absorption:(v.ssd-v.oven_dry)/v.oven_dry*100};
 if(test==='specific-gravity'&&agg==='coarse'&&(d=v.ssd-v.submerged)>0&&v.oven_dry>0)return {displaced:d,bulk_dry:v.oven_dry/d,bulk_ssd:v.ssd/d,apparent:v.oven_dry/(v.oven_dry-v.submerged),absorption:(v.ssd-v.oven_dry)/v.oven_dry*100};
 if(test==='bulk-density'&&v.volume>0&&v.specific_gravity>0){let mass=v.full_container-v.container,bd=mass/(v.volume/1000000);return {aggregate_mass:mass,bulk_density:bd,voids:(v.specific_gravity*1000-bd)/(v.specific_gravity*1000)*100};}
 if(test==='sieve'&&v.sample_mass>0){let ks=agg==='fine'?['r095','r475','r236','r118','r060','r030','r015','pan']:['r750','r375','r190','r095','r475','pan'],sum=ks.reduce((s,k)=>s+(v[k]||0),0),cum=0,fm=0;ks.forEach(k=>{cum+=v[k]||0;if(agg==='fine'&&['r475','r236','r118','r060','r030','r015'].includes(k))fm+=cum/v.sample_mass*100});return {mass_total:sum,mass_difference:v.sample_mass-sum,fineness_modulus:agg==='fine'?fm/100:0};}
 if(test==='los-angeles'&&v.initial>0){let loss=v.initial-v.retained;return {mass_loss:loss,abrasion:loss/v.initial*100};} return null;}
function recalc(section){const heads=[...section.querySelectorAll('.obs-head')],results={};heads.forEach((_,i)=>{let vals={};section.querySelectorAll('.input-rows tr').forEach(r=>{let el=r.children[i+1]?.querySelector('input');vals[r.dataset.field]=el&&el.value!==''?Number(el.value):NaN});let out=Object.values(vals).every(Number.isFinite)?calculate(section.dataset.test,section.dataset.aggregate,vals):null;section.querySelectorAll('.result-rows tr[data-result]').forEach(r=>{let cell=r.children[i+1],value=out?.[r.dataset.result];if(cell)cell.textContent=Number.isFinite(value)?value.toLocaleString('id-ID',{maximumFractionDigits:3}):'—';if(Number.isFinite(value))(results[r.dataset.result]??=[]).push(value);});});section.querySelectorAll('.result-rows tr[data-result]').forEach(row=>{const values=results[row.dataset.result]||[],average=values.length?values.reduce((a,b)=>a+b,0)/values.length:NaN;row.querySelector('.average-value').textContent=Number.isFinite(average)?average.toLocaleString('id-ID',{maximumFractionDigits:3}):'—';});}
function reindexSection(section){section.querySelectorAll('.obs-head').forEach((head,index)=>{head.querySelector('.obs-title').textContent='Observasi '+roman(index+1);head.querySelector('.observation-record-id').name=head.querySelector('.observation-record-id').name.replace(/observations\]\[\d+\]/,`observations][${index}]`)});section.querySelectorAll('.input-rows tr').forEach(row=>row.querySelectorAll('.observation-input').forEach((input,index)=>input.name=input.name.replace(/observations\]\[\d+\]/,`observations][${index}]`)))}
function removeSectionObservation(section,index){const head=section.querySelectorAll('.obs-head')[index];head.remove();section.querySelectorAll('.input-rows tr,.result-rows tr[data-result]').forEach(row=>row.children[index+1]?.remove());reindexSection(section);recalc(section)}
document.querySelectorAll('.test-section:not([data-test="sieve"])').forEach(section=>{section.addEventListener('input',()=>recalc(section));section.querySelector('.add-observation').addEventListener('click',()=>{let table=section.querySelector('table'),n=table.querySelectorAll('.obs-head').length,sourceId=table.querySelector('.observation-record-id');let th=document.createElement('th');th.className='text-center obs-head';th.style.minWidth='200px';th.innerHTML=`<span class="obs-title">Observasi ${roman(n+1)}</span><button type="button" class="btn btn-sm btn-link text-danger remove-observation ms-1" title="Hapus Observasi"><i class="bi bi-trash"></i></button><input type="hidden" class="observation-record-id" name="${sourceId.name.replace(/observations\]\[\d+\]/,`observations][${n}]`)}">`;table.tHead.rows[0].insertBefore(th,table.querySelector('.average-head'));section.querySelectorAll('.input-rows tr').forEach(r=>{let src=r.querySelector('.observation-input'),td=document.createElement('td'),inp=src.cloneNode();inp.value='';inp.name=src.name.replace(/observations\]\[\d+\]/,`observations][${n}]`);td.appendChild(inp);r.insertBefore(td,r.querySelector('.average-placeholder'))});section.querySelectorAll('.result-rows tr[data-result]').forEach(r=>{let td=document.createElement('td');td.className='text-end result-value';td.textContent='—';r.insertBefore(td,r.querySelector('.average-value'))});recalc(section)});section.addEventListener('click',async event=>{const button=event.target.closest('.remove-observation');if(!button)return;const heads=[...section.querySelectorAll('.obs-head')];if(heads.length<=1){alert('Minimal satu observasi harus tetap tersedia.');return}const head=button.closest('.obs-head'),index=heads.indexOf(head),id=button.dataset.observationId;if(!id){removeSectionObservation(section,index);return}if(!confirm(`Hapus Observasi ${roman(index+1)}? Data yang sudah tersimpan akan dihapus.`))return;button.disabled=true;try{const response=await fetch(observationDeleteUrl.replace('__PROJECT__',worksheetProject.value).replace('__RUN__',section.dataset.runId).replace('__OBS__',id),{method:'DELETE',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,'Accept':'application/json'}});const payload=await response.json();if(!response.ok)throw new Error(payload.message||'Observasi gagal dihapus.');const run=Object.values(savedTestRuns).find(item=>String(item.id)===String(section.dataset.runId));if(run)run.observations.splice(index,1);removeSectionObservation(section,index)}catch(error){alert(error.message);button.disabled=false}})});
document.querySelector('[data-test="sieve"] .add-observation')?.remove();
const sieveRows=[...document.querySelectorAll('.sieve-table tbody tr')], sieveLabels=sieveRows.filter(r=>Number(r.dataset.size)>0).map(r=>r.dataset.size+' mm').reverse();
const zoneColors=['#e67e22','#8e44ad','#2980b9','#16a085'],zoneCount=@json($zoneCount),gradationNames=@json($gradationNames); let gradationChart=new Chart(document.getElementById('gradation-chart'),{type:'line',data:{labels:sieveLabels,datasets:[{label:'Hasil Pengujian',data:[],borderColor:'#c0392b',backgroundColor:'#c0392b',borderWidth:3,tension:.2},...Array.from({length:zoneCount},(_,i)=>i+1).flatMap((z,i)=>[{label:`${gradationNames[i]} Bawah`,data:[],borderColor:zoneColors[i],borderDash:[5,4],pointRadius:2},{label:`${gradationNames[i]} Atas`,data:[],borderColor:zoneColors[i],pointRadius:2}])]},options:{responsive:true,plugins:{legend:{position:'bottom'}},scales:{y:{min:0,max:100,title:{display:true,text:'Persen Lolos (%)'}},x:{title:{display:true,text:'Ukuran Saringan'}}}}});
function recalcSieve(){let total=0;sieveRows.forEach(r=>{let empty=Number(r.querySelector('.sieve-empty').value)||0,combined=Number(r.querySelector('.sieve-combined').value)||0,ret=Math.max(0,combined-empty);total+=ret;r.querySelector('.sieve-retained').childNodes[0].textContent=ret.toLocaleString('id-ID',{maximumFractionDigits:2});r.querySelector('input[type="hidden"]').value=ret;});const sampleInput=document.querySelector('.sieve-sample-mass'),sample=total;sampleInput.value=total>0?Number(total.toFixed(3)):'';let cum=0,fm=0,passing=[];sieveRows.forEach(r=>{const ret=Number(r.querySelector('input[type="hidden"]').value)||0,pct=sample>0?ret/sample*100:0;cum+=pct;if(@json($aggregate==='fine')&&['r475','r236','r118','r060','r030','r015'].includes(r.dataset.sieve))fm+=cum;r.querySelector('.sieve-percent').textContent=pct.toLocaleString('id-ID',{maximumFractionDigits:2});r.querySelector('.sieve-cumulative').textContent=cum.toLocaleString('id-ID',{maximumFractionDigits:2});r.querySelector('.sieve-passing').textContent=Math.max(0,100-cum).toLocaleString('id-ID',{maximumFractionDigits:2});if(Number(r.dataset.size)>0)passing.push(Math.max(0,100-cum));});document.querySelector('.sieve-total').textContent=total.toLocaleString('id-ID',{maximumFractionDigits:2});document.querySelector('.sieve-fm').textContent=(fm/100).toLocaleString('id-ID',{maximumFractionDigits:3});gradationChart.data.datasets[0].data=passing.reverse();const selected=document.getElementById('selected-zone').value;Array.from({length:zoneCount},(_,i)=>i+1).forEach((z,i)=>['lower','upper'].forEach((kind,j)=>{const dataset=gradationChart.data.datasets[1+i*2+j];dataset.data=sieveRows.filter(r=>Number(r.dataset.size)>0).map(r=>{const input=r.querySelector(`.zone-bound[data-zone="${z}"][data-kind="${kind}"]`);return input&&input.value!==''?Number(input.value):null}).reverse();dataset.hidden=selected!=='all'&&selected!==String(z)}));gradationChart.update();}
document.querySelector('[data-test="sieve"]')?.addEventListener('input',recalcSieve);
recalcSieve();filterWorksheetSources();
</script>@endpush

