@extends('layouts.app') @section('title',$config['title']) @section('subtitle','Masukan, hasil otomatis, dan arsip proyek')
@push('head')<style>
.workflow-wide-dialog{width:calc(100vw - 290px);max-width:none;margin:16px 14px 16px 276px}.workflow-wide-dialog .modal-content{min-height:calc(100vh - 32px)}.workflow-wide-dialog .modal-body{padding:16px}.workflow-wide-dialog table{font-size:.66rem}.workflow-wide-dialog .form-control-sm{min-width:0;width:100%;padding:3px 2px;font-size:.68rem}.strength-table{width:100%;table-layout:fixed}.strength-table th,.strength-table td{padding:4px 2px;white-space:normal;word-break:normal}.strength-table th:nth-child(1){width:3%}.strength-table th:nth-child(2),.strength-table th:nth-child(3){width:9%}.strength-table th:nth-child(4){width:4%}.strength-table th:nth-child(5),.strength-table th:nth-child(6){width:6%}.strength-table th:nth-child(7),.strength-table th:nth-child(8){width:7%}.strength-table th:nth-child(9){width:8%}.strength-table th:nth-child(10){width:9%}.strength-table th:nth-child(11){width:5%}.strength-table th:nth-child(12){width:10%}.strength-table th:nth-child(13){width:8%}.strength-table th:nth-child(14){width:3%}.strength-table input[type=date]{font-size:.62rem;padding-left:1px;padding-right:1px}.strength-table .btn{padding:2px 4px}
@media(max-width:900px){.workflow-wide-dialog{width:calc(100vw - 20px);margin:10px;max-width:none}.workflow-wide-dialog .modal-content{min-height:calc(100vh - 20px)}}
</style>@endpush
@section('content')
<div class="d-flex justify-content-between mb-4"><div><h3 class="fw-bold">{{$config['title']}}</h3><p class="text-secondary">Hasil muncul langsung ketika masukan lengkap. Tekan Simpan untuk memasukkan ke arsip proyek.</p></div><div class="d-flex gap-2">@if($type==='compressive-strength')<a class="btn btn-outline-primary align-self-start" href="{{route('documentation.index',['project'=>$selectedProject,'module'=>'compressive-strength'])}}"><i class="bi bi-camera me-2"></i>Dokumentasi</a>@endif<button class="btn btn-primary align-self-start" data-bs-toggle="modal" data-bs-target="#entry"><i class="bi bi-plus-lg me-2"></i>Tambah Data</button></div></div>
<div class="card overflow-hidden"><table class="table align-middle mb-0"><thead><tr><th>Nomor</th><th>Proyek</th><th>Tanggal</th><th>Hasil</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>@forelse($records as $record)<tr><td><b>{{$record->number}}</b></td><td>{{$record->project?->name??'Proyek tidak tersedia'}} @if($record->project?->trashed())<span class="badge text-bg-light">Diarsipkan</span>@endif</td><td>{{$record->work_date?->format('d/m/Y')??'—'}}</td><td>@foreach($record->result_data??[] as $key=>$value)@if(!is_array($value))<div class="small"><span class="text-secondary">{{$key}}:</span> <b>{{is_numeric($value)?number_format($value,3,',','.'):$value}}</b></div>@endif @endforeach</td><td><span class="badge {{$record->status==='disetujui'?'text-bg-success':($record->status==='diperiksa'?'text-bg-warning':'text-bg-secondary')}}">{{$record->status==='draft'?'Draf':ucfirst($record->status)}}</span></td><td class="text-end"><form method="post" action="{{route('archive.store',['workflows',$record->id])}}" onsubmit="return confirm('Pindahkan data ini ke Arsip?')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger" title="Pindahkan ke Arsip"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">Belum ada data. Klik Tambah Data untuk mulai.</td></tr>@endforelse</tbody></table></div>
<div class="modal fade" id="entry"><div class="modal-dialog {{$type==='compressive-strength'?'workflow-wide-dialog':'modal-lg'}}"><form method="post" action="{{route('workflow.store',$type)}}" class="modal-content workflow-form">@csrf<input type="hidden" name="workflow_id" id="workflow-id"><div class="modal-header"><h5 class="modal-title">{{$config['title']}}</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-md-8"><label class="form-label">Proyek *</label><select class="form-select" name="project_id" id="workflow-project" required><option value="">Pilih proyek</option>@foreach($projects as $p)<option value="{{$p->id}}" @selected(old('project_id',$selectedProject)==$p->id)>{{$p->number}} — {{$p->name}}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Tanggal *</label><input type="date" class="form-control" name="work_date" value="{{date('Y-m-d')}}" required></div>
@if($type==='fresh-concrete')
<div class="col-12"><div class="row g-0 border rounded overflow-hidden"><div class="col-md-6 bg-light p-3 border-end"><h6 class="fw-bold text-success"><i class="bi bi-calculator me-2"></i>DATA RENCANA — OTOMATIS DARI DESAIN CAMPURAN</h6><div id="mix-source-note" class="small text-secondary mb-3">Pilih proyek untuk mengambil desain campuran terakhir.</div>
@foreach([['target_slump','Slump sasaran','mm'],['theoretical_density','Berat isi teoritis','kg/m³'],['batch_mass','Massa adukan rencana','kg']] as [$name,$label,$unit])<div class="mb-3"><label class="form-label">{{$label}}</label><div class="input-group"><input type="number" step="any" class="form-control live-input bg-white" name="data[{{$name}}]" data-key="{{$name}}" readonly required><span class="input-group-text">{{$unit}}</span></div></div>@endforeach
</div><div class="col-md-6 p-3"><h6 class="fw-bold text-primary"><i class="bi bi-pencil-square me-2"></i>HASIL AKTUAL — MASUKAN MANUAL</h6><div class="small text-secondary mb-3">Isi hasil pengukuran beton segar yang sebenarnya.</div>
@foreach([['actual_slump','Slump aktual','mm'],['actual_density','Berat isi aktual','kg/m³'],['design_volume','Volume adukan aktual','m³']] as [$name,$label,$unit])<div class="mb-3"><label class="form-label">{{$label}} *</label><div class="input-group"><input type="number" min="0" step="any" class="form-control live-input" name="data[{{$name}}]" data-key="{{$name}}" required><span class="input-group-text">{{$unit}}</span></div></div>@endforeach
</div></div></div>
@elseif($type==='compressive-strength')
<div class="col-12"><div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Kuat tekan sasaran — poin 2 desain campuran</label><div class="input-group"><input type="number" step="any" class="form-control bg-light" data-key="target_fc" readonly><span class="input-group-text">MPa</span></div></div><div class="col-md-8"><div id="mix-source-note" class="small text-secondary">Pilih proyek untuk mengambil kuat tekan sasaran.</div></div></div></div>
<div class="col-12"><div class="table-responsive"><table class="table table-bordered table-sm text-center align-middle mb-2"><thead><tr><th>Umur beton (hari)</th>@foreach([3,7,14,21,28,90,365] as $age)<th>{{$age}}</th>@endforeach</tr></thead><tbody><tr><th>Semen Portland biasa</th>@foreach([.40,.65,.88,.95,1,1.20,1.35] as $factor)<td>{{$factor}}</td>@endforeach</tr></tbody></table></div><div class="small text-secondary">Untuk umur di antara nilai tabel, faktor konversi dihitung dengan interpolasi linier.</div></div>
<div class="col-12"><div class="d-flex justify-content-between align-items-center"><div><h6 class="fw-bold mb-0">Data seluruh benda uji dalam satu adukan</h6><div class="excel-paste-hint">Urutan kolom Excel: tanggal buat, tanggal uji, diameter, tinggi, berat, beban maks.</div></div><button type="button" class="btn btn-sm btn-outline-primary" id="add-strength-row"><i class="bi bi-plus-lg me-1"></i>Tambah Benda Uji</button></div><div class="mt-2"><table class="table table-bordered table-sm align-middle strength-table" data-excel-paste data-excel-grow="rows" data-excel-add="#add-strength-row"><thead><tr><th>No.</th><th>Tanggal pembuatan</th><th>Tanggal pengujian</th><th>Umur (hari)</th><th>Diameter (mm)</th><th>Tinggi (mm)</th><th>Berat (g)</th><th>Beban maks. (kN)</th><th>Luas (mm²)</th><th>Kuat tekan aktual (MPa)</th><th>Faktor umur</th><th>Perkiraan 28 hari (MPa)</th><th>Mutu K (kg/cm²)</th><th></th></tr></thead><tbody id="strength-rows"></tbody></table></div></div>
@else
@foreach($config['fields'] as [$name,$label,$unit])<div class="col-md-6"><label class="form-label">{{$label}} *</label><div class="input-group"><input type="number" min="0" step="any" class="form-control live-input" name="data[{{$name}}]" data-key="{{$name}}" required><span class="input-group-text">{{$unit}}</span></div></div>@endforeach
@endif
<div class="col-12"><div class="alert alert-info mb-0 live-result"><b>Hasil otomatis:</b><div class="mt-2 text-secondary">Lengkapi seluruh masukan.</div></div></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button></div></form></div></div>
@endsection
@push('scripts')<script>
const type=@json($type), mixDesigns=@json($mixDesigns), savedWorkflowRecords=@json($savedRecords), box=document.querySelector('.live-result'), inputs=[...document.querySelectorAll('.live-input')];
function loadMixDesign(){const project=document.getElementById('workflow-project').value;if(['fresh-concrete','compressive-strength'].includes(type)){const mix=mixDesigns[project],note=document.getElementById('mix-source-note');if(type==='fresh-concrete')['target_slump','theoretical_density','batch_mass'].forEach(key=>document.querySelector(`[data-key="${key}"]`).value=mix?.[key]??'');if(type==='compressive-strength')document.querySelector('[data-key="target_fc"]').value=mix?.target_fc??'';if(mix){note.className=type==='fresh-concrete'?'small text-success mb-3':'small text-success mt-1';note.textContent=type==='fresh-concrete'?`Terisi dari ${mix.number}. Volume campuran percobaan: ${(mix.design_volume??0).toLocaleString('id-ID',{maximumFractionDigits:4})} m³.`:`Terisi otomatis dari poin 2 desain campuran ${mix.number}: f'c ${Number(mix.target_fc).toLocaleString('id-ID',{maximumFractionDigits:3})} MPa.`}else{note.className=type==='fresh-concrete'?'small text-danger mb-3':'small text-danger mt-1';note.textContent='Proyek ini belum memiliki desain campuran yang tersimpan.'}}loadSavedWorkflow();live();}
const ageFactor=age=>{const ages=[3,7,14,21,28,90,365],f=[.40,.65,.88,.95,1,1.20,1.35];if(age<=3)return f[0];if(age>=365)return f.at(-1);for(let i=0;i<ages.length-1;i++)if(age>=ages[i]&&age<=ages[i+1])return f[i]+(age-ages[i])/(ages[i+1]-ages[i])*(f[i+1]-f[i]);return 1};
function strengthRow(index){return `<tr><td class="row-number">${index+1}</td><td><input type="date" class="form-control form-control-sm strength-input" name="data[rows][${index}][cast_date]" required></td><td><input type="date" class="form-control form-control-sm strength-input" name="data[rows][${index}][test_date]" required></td><td class="age-result">—</td><td><input type="number" min="1" step="any" value="150" class="form-control form-control-sm strength-input" name="data[rows][${index}][diameter]" required></td><td><input type="number" min="1" step="any" value="300" class="form-control form-control-sm strength-input" name="data[rows][${index}][height]" required></td><td><input type="number" min=".001" step="any" class="form-control form-control-sm strength-input" name="data[rows][${index}][weight]" required></td><td><input type="number" min=".001" step="any" class="form-control form-control-sm strength-input" name="data[rows][${index}][load_kn]" required></td><td class="area-result">—</td><td class="actual-result">—</td><td class="factor-result">—</td><td class="estimate-result fw-bold">—</td><td class="k-result fw-bold">—</td><td><button type="button" class="btn btn-sm btn-outline-danger remove-strength-row"><i class="bi bi-x"></i></button></td></tr>`}
function loadSavedWorkflow(){const project=document.getElementById('workflow-project').value,record=savedWorkflowRecords[project],data=record?.input_data||{};document.getElementById('workflow-id').value=record?.id||'';document.querySelector('[name="work_date"]').value=record?.work_date||new Date().toISOString().slice(0,10);document.querySelector('[name="notes"]').value=record?.notes||'';if(type==='compressive-strength'){const body=document.getElementById('strength-rows'),rows=data.rows||[];if(rows.length){body.innerHTML='';rows.forEach((values,index)=>{body.insertAdjacentHTML('beforeend',strengthRow(index));const inputs=body.lastElementChild.querySelectorAll('input');['cast_date','test_date','diameter','height','weight','load_kn'].forEach((key,i)=>inputs[i].value=values[key]??'')})}}else inputs.forEach(input=>{if(!input.readOnly)input.value=data[input.dataset.key]??''})}
function renumberStrengthRows(){document.querySelectorAll('#strength-rows tr').forEach((row,i)=>{row.querySelector('.row-number').textContent=i+1;row.querySelectorAll('input').forEach(input=>input.name=input.name.replace(/rows\]\[\d+\]/,`rows][${i}]`))})}
function recalcStrength(){const target=Number(document.querySelector('[data-key="target_fc"]')?.value||0),values=[];document.querySelectorAll('#strength-rows tr').forEach(row=>{const fields=[...row.querySelectorAll('input')],cast=fields[0].value,test=fields[1].value,diameter=Number(fields[2].value),load=Number(fields[5].value);let age=cast&&test?Math.round((new Date(test)-new Date(cast))/86400000):NaN,area=Math.PI*diameter**2/4,actual=load*1000/area,factor=ageFactor(age),estimate=actual/factor,k=estimate*10.19716213;row.querySelector('.age-result').textContent=Number.isFinite(age)?age:'—';row.querySelector('.area-result').textContent=Number.isFinite(area)?area.toLocaleString('id-ID',{maximumFractionDigits:2}):'—';row.querySelector('.actual-result').textContent=Number.isFinite(actual)?actual.toLocaleString('id-ID',{maximumFractionDigits:3}):'—';row.querySelector('.factor-result').textContent=Number.isFinite(factor)?factor.toLocaleString('id-ID',{maximumFractionDigits:3}):'—';row.querySelector('.estimate-result').textContent=Number.isFinite(estimate)?estimate.toLocaleString('id-ID',{maximumFractionDigits:3}):'—';row.querySelector('.k-result').textContent=Number.isFinite(k)?k.toLocaleString('id-ID',{maximumFractionDigits:2}):'—';if(Number.isFinite(estimate)&&age>=0)values.push(estimate)});if(!values.length||!target){box.innerHTML='<b>Hasil otomatis:</b><div class="mt-2 text-secondary">Lengkapi data benda uji.</div>';return}const mean=values.reduce((a,b)=>a+b,0)/values.length,sd=values.length>1?Math.sqrt(values.reduce((s,x)=>s+(x-mean)**2,0)/(values.length-1)):0,characteristic=mean-1.64*sd;box.innerHTML=`<b>Rekap satu adukan:</b><div class="row mt-2"><div class="col-md-3">Jumlah: <b>${values.length}</b></div><div class="col-md-3">Rata-rata 28 hari: <b>${mean.toLocaleString('id-ID',{maximumFractionDigits:3})} MPa</b></div><div class="col-md-3">SD sampel: <b>${sd.toLocaleString('id-ID',{maximumFractionDigits:3})} MPa</b></div><div class="col-md-3">Karakteristik: <b>${characteristic.toLocaleString('id-ID',{maximumFractionDigits:3})} MPa</b><br><span class="badge ${characteristic>=target?'text-bg-success':'text-bg-danger'}">${characteristic>=target?'Memenuhi':'Tidak memenuhi'}</span></div></div>`}
function live(){if(type==='compressive-strength'){recalcStrength();return}let v={},ok=true;inputs.forEach(i=>{if(i.value==='')ok=false;v[i.dataset.key]=Number(i.value)});if(!ok){box.innerHTML='<b>Hasil otomatis:</b><div class="mt-2 text-secondary">Lengkapi seluruh masukan.</div>';return}let r={};
if(type==='combined-aggregate'){let t=v.fine_percent+v.coarse_percent;r={'Total agregat (%)':t,'Agregat halus (kg)':v.total_mass*v.fine_percent/100,'Agregat kasar (kg)':v.total_mass*v.coarse_percent/100,'Status':Math.abs(t-100)<.001?'Memenuhi 100%':'Tidak memenuhi 100%'}}
if(type==='moisture-correction'){let fd=v.fine_ssd/(1+v.fine_absorption/100),cd=v.coarse_ssd/(1+v.coarse_absorption/100),free=fd*(v.fine_moisture-v.fine_absorption)/100+cd*(v.coarse_moisture-v.coarse_absorption)/100;r={'Pasir lapangan (kg)':fd*(1+v.fine_moisture/100),'Kerikil lapangan (kg)':cd*(1+v.coarse_moisture/100),'Air bebas (kg)':free,'Air ditambahkan (kg)':Math.max(0,v.design_water-free)}}
if(type==='trial-mix'){let f=v.trial_volume/1000*(1+v.waste/100);r={'Semen (kg)':v.cement_m3*f,'Air (kg)':v.water_m3*f,'Pasir (kg)':v.fine_m3*f,'Kerikil (kg)':v.coarse_m3*f}}
if(type==='fresh-concrete'&&v.actual_density>0&&v.design_volume>0){let vol=v.batch_mass/v.actual_density;r={'Selisih slump (mm)':v.actual_slump-v.target_slump,'Volume aktual (m³)':vol,'Hasil volume':vol/v.design_volume}}
if(type==='specimen'&&v.diameter>0&&v.height>0){let vol=Math.PI*(v.diameter/1000)**2/4*(v.height/1000);r={'Luas tekan (mm²)':Math.PI*v.diameter**2/4,'Volume (m³)':vol,'Berat isi (kg/m³)':v.weight/vol}}
if(type==='compressive-strength'&&v.diameter>0){let a=Math.PI*v.diameter**2/4,fc=v.load_kn*1000/a;r={'Luas tekan (mm²)':a,'Kuat tekan (MPa)':fc,'Pencapaian (%)':v.target_fc>0?fc/v.target_fc*100:0}}
if(type==='evaluation'&&v.target_fc>0){let p=v.actual_fc/v.target_fc*100,sl=v.actual_slump>=v.slump_min&&v.actual_slump<=v.slump_max;r={'Pencapaian (%)':p,'Status slump':sl?'Sesuai':'Tidak sesuai','Kesimpulan':p>=100&&sl?'Campuran diterima':p>=90?'Perlu penyesuaian':'Campuran ditolak'}}
box.innerHTML='<b>Hasil otomatis:</b>'+Object.entries(r).map(([k,x])=>`<div class="mt-1">${k}: <b>${typeof x==='number'?x.toLocaleString('id-ID',{maximumFractionDigits:3}):x}</b></div>`).join('');}
inputs.forEach(i=>i.addEventListener('input',live));if(type==='compressive-strength'){const body=document.getElementById('strength-rows');for(let i=0;i<3;i++)body.insertAdjacentHTML('beforeend',strengthRow(i));document.getElementById('add-strength-row').addEventListener('click',()=>{body.insertAdjacentHTML('beforeend',strengthRow(body.children.length));});body.addEventListener('input',recalcStrength);body.addEventListener('click',e=>{const button=e.target.closest('.remove-strength-row');if(button&&body.children.length>1){button.closest('tr').remove();renumberStrengthRows();recalcStrength();}})}document.getElementById('workflow-project')?.addEventListener('change',loadMixDesign);loadMixDesign();</script>@endpush
