@extends('layouts.app')
@section('title','Laporan '.$project->number)
@section('subtitle','Berkas terpadu proyek dan perusahaan')
@section('content')
@php
$badge=match($reportStatus){'disetujui'=>'text-bg-success','diperiksa'=>'text-bg-warning','ditolak'=>'text-bg-danger','draft'=>'text-bg-secondary',default=>'text-bg-light'};
$selectedMixMethod=$project->report_include_mix_design_2012&&$project->report_include_mix_design_2012_combined?'both':($project->report_include_mix_design_2012?'mix-design-2012':($project->report_include_mix_design_2012_combined?'mix-design-2012-combined':null));
$hasStandardMix=$availableMixTypes->contains('mix-design-2012');
$hasCombinedMix=$availableMixTypes->contains('mix-design-2012-combined');
@endphp
<a href="{{route('workflow.reports')}}" class="small text-decoration-none"><i class="bi bi-arrow-left me-1"></i>Kembali ke semua laporan</a>
<div class="card p-4 my-3"><div class="d-flex justify-content-between align-items-start gap-3"><div><div class="text-secondary">{{$project->number}}</div><h3 class="fw-bold mb-1">{{$project->name}}</h3><div><b>Perusahaan/Pemilik:</b> {{$project->owner ?: 'Belum diisi'}}</div><div><b>Kontraktor:</b> {{$project->contractor ?: 'Belum diisi'}} · <b>Lokasi:</b> {{$project->location ?: 'Belum diisi'}}</div></div><span class="badge {{$badge}} fs-6">{{$reportStatus==='draft'?'Draf':ucfirst($reportStatus)}}</span></div>
<div class="d-flex gap-2 mt-4">
@if($reportStatus==='draft')<form method="post" action="{{route('workflow.report.status',$project)}}">@csrf @method('patch')<input type="hidden" name="status" value="diperiksa"><button class="btn btn-warning"><i class="bi bi-send-check me-2"></i>Ajukan Pemeriksaan</button></form>@endif
@if($reportStatus==='diperiksa')<form method="post" action="{{route('workflow.report.status',$project)}}" class="d-flex gap-2" onsubmit="return confirm('Setujui laporan dan kunci isi dokumen?')">@csrf @method('patch')<input type="hidden" name="status" value="disetujui"><select name="approval_role" class="form-select"><option value="pemeriksa">Pemeriksa</option><option value="mengetahui">Mengetahui</option><option value="menyetujui">Menyetujui</option></select><button class="btn btn-success text-nowrap"><i class="bi bi-patch-check me-2"></i>Setujui</button></form><form method="post" action="{{route('workflow.report.status',$project)}}">@csrf @method('patch')<input type="hidden" name="status" value="dikembalikan"><button class="btn btn-outline-warning">Kembalikan</button></form><form method="post" action="{{route('workflow.report.status',$project)}}">@csrf @method('patch')<input type="hidden" name="status" value="ditolak"><button class="btn btn-outline-danger">Tolak</button></form>@endif
@if($reportStatus==='ditolak')<form method="post" action="{{route('workflow.report.status',$project)}}" onsubmit="return confirm('Masukkan laporan yang ditolak ke proses revisi untuk diperbaiki dan diajukan ulang?')">@csrf @method('patch')<input type="hidden" name="status" value="revisi"><button class="btn btn-warning"><i class="bi bi-arrow-counterclockwise me-2"></i>Tinjau Ulang / Masuk Revisi</button></form>@endif
@if($reportStatus==='disetujui')<a class="btn btn-success" href="{{route('workflow.report.final',$project)}}" target="_blank"><i class="bi bi-file-earmark-pdf me-2"></i>Buka Laporan Akhir</a><form method="post" action="{{route('workflow.report.status',$project)}}" class="d-flex gap-2">@csrf @method('patch')<input type="hidden" name="status" value="disetujui"><select name="approval_role" class="form-select"><option value="mengetahui">Tambah: Mengetahui</option><option value="menyetujui">Tambah: Menyetujui</option><option value="pemeriksa">Tambah: Pemeriksa</option></select><button class="btn btn-outline-success text-nowrap">Tambah Persetujuan Saya</button></form><form method="post" action="{{route('workflow.report.status',$project)}}" onsubmit="return confirm('Buat revisi baru dan tandai seluruh persetujuan lama tidak berlaku?')">@csrf @method('patch')<input type="hidden" name="status" value="revisi"><button class="btn btn-outline-danger">Buat Revisi</button></form>@endif
@if($project->verification_code)<a class="btn btn-outline-primary" href="{{route('public.verify',$project->verification_code)}}" target="_blank"><i class="bi bi-qr-code me-2"></i>Halaman Publik</a>@endif
</div></div>
<div class="card p-4 mb-3"><div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><h5 class="fw-bold mb-1">Metode desain campuran yang dimasukkan ke laporan</h5><div class="text-secondary small">Pilihan ini menentukan perhitungan dan komposisi yang tampil pada laporan akhir serta PDF.</div></div>@if($project->locked_at)<span class="badge text-bg-secondary">Dokumen terkunci</span>@endif</div>
<form method="post" action="{{route('workflow.report.mix-design-selection',$project)}}">@csrf @method('patch')
<div class="row g-3">
@foreach([
 ['mix-design-2012','Desain Campuran 2012','Metode penetapan agregat kasar SNI 7656:2012',$hasStandardMix],
 ['mix-design-2012-combined','Desain Campuran 2012 (Gradasi Gabungan)','Proporsi pasir dan kerikil ditentukan dari analisis gradasi gabungan',$hasCombinedMix],
 ['both','Masukkan keduanya','Laporan menampilkan kedua hasil sebagai dua metode perhitungan',$hasStandardMix&&$hasCombinedMix]
] as [$value,$label,$description,$available])
<div class="col-md-4"><label class="border rounded p-3 d-block h-100 {{old('report_mix_design_method',$selectedMixMethod)===$value?'border-primary bg-light':''}}"><div class="form-check"><input class="form-check-input" type="radio" name="report_mix_design_method" value="{{$value}}" {{old('report_mix_design_method',$selectedMixMethod)===$value?'checked':''}} {{(!$available||$project->locked_at)?'disabled':''}}><span class="form-check-label fw-bold">{{$label}}</span></div><div class="small text-secondary mt-2">{{$description}}</div><div class="small mt-2"><span class="badge {{$available?'text-bg-success':'text-bg-warning'}}">{{$available?'Hasil desain tersedia':(($value==='mix-design-2012-combined'||$value==='both')&&$hasCombinedAnalysis?'Analisis tersedia, desain belum disimpan':'Belum dihitung')}}</span></div></label></div>
@endforeach
</div>
@if($project->locked_at)<div class="alert alert-secondary mt-3 mb-0">Laporan sudah disahkan. Klik <b>Buat Revisi</b> terlebih dahulu jika pilihan metode perlu diubah.</div>@else<div class="d-flex align-items-center gap-3 mt-3"><button class="btn btn-primary" {{$hasStandardMix||$hasCombinedMix?'':'disabled'}}><i class="bi bi-save me-2"></i>Simpan Pilihan Laporan</button><span class="small text-secondary">Hanya metode yang sudah mempunyai hasil perhitungan yang dapat dipilih.</span></div>@endif
</form></div>
@if($approvals->isNotEmpty())<div class="card overflow-hidden mb-3"><div class="p-3 border-bottom bg-light"><b>Riwayat Persetujuan dan Kode QR Pejabat</b><div class="small text-secondary">Status dokumen: {{strtoupper($project->document_status==='direvisi'?'revisi':($project->document_status==='valid'?'valid':'dokumen palsu'))}}</div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Peran</th><th>Pejabat</th><th>Waktu</th><th>Status</th><th>Verifikasi</th></tr></thead><tbody>@foreach($approvals as $approval)<tr><td>{{ucfirst($approval->approval_role)}}</td><td><b>{{$approval->user->name}}</b><div class="small text-secondary">{{$approval->user->position}} · {{$approval->user->employee_number}}</div></td><td>{{$approval->approved_at?->format('d/m/Y H:i')}} WITA</td><td><b>{{strtoupper($approval->status==='valid'?'valid':($approval->status==='direvisi'?'revisi':'dokumen palsu'))}}</b></td><td><a target="_blank" href="{{route('public.approval',$approval->verification_token)}}" class="btn btn-sm btn-outline-primary">Periksa kode QR</a></td></tr>@endforeach</tbody></table></div></div>@endif
<div class="card overflow-hidden"><div class="p-3 border-bottom bg-light"><b>Seluruh data dalam satu berkas proyek</b><div class="small text-secondary">{{$records->count()}} pemeriksaan/perhitungan tersimpan.</div></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Modul</th><th>Nomor</th><th>Tanggal</th><th>Ringkasan hasil</th><th>Status</th></tr></thead><tbody>
@forelse($records as $r) @php $rowBadge=match($r->status){'disetujui'=>'text-bg-success','diperiksa'=>'text-bg-warning',default=>'text-bg-secondary'}; @endphp <tr><td><b>{{$r->module}}</b></td><td>{{$r->number}}</td><td>{{$r->date?->format('d/m/Y')}}</td><td class="small" style="max-width:480px">{{$r->result ?: 'Data tersimpan'}}</td><td><span class="badge {{$rowBadge}}">{{$r->status==='draft'?'Draf':ucfirst($r->status)}}</span></td></tr>
@empty<tr><td colspan="5" class="text-center text-secondary py-5">Proyek belum mempunyai data pemeriksaan.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
