@extends('layouts.app')
@section('title','Sumber Material')
@section('subtitle','Data bahan berdasarkan proyek dan jenis')
@section('content')
@php $allTypes=['Semen','Abu terbang','Terak','Abu silika','Air','Pasir','Kerikil','Batu pecah','Agregat berat','Bahan tambah kimia','Bahan tambah mineral']; @endphp
<div class="d-flex justify-content-between mb-3"><div><h3 class="fw-bold">Sumber Material</h3><p class="text-secondary">Gunakan filter untuk melihat material milik proyek atau jenis tertentu.</p></div><button class="btn btn-primary align-self-start" data-bs-toggle="modal" data-bs-target="#add"><i class="bi bi-plus-lg me-2"></i>Tambah Material</button></div>
<form method="get" class="card p-3 mb-3"><div class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label">Filter proyek</label><select class="form-select" name="project"><option value="">Semua proyek</option><option value="general" @selected(request('project')==='general')>Material umum</option>@foreach($filterProjects as $p)<option value="{{$p->id}}" @selected((string)request('project')===(string)$p->id)>{{$p->name}}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Filter jenis</label><select class="form-select" name="type"><option value="">Semua jenis</option>@foreach($types as $type)<option value="{{$type}}" @selected(request('type')===$type)>{{$type}}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Cari kode / nama / catatan</label><input class="form-control" name="search" value="{{request('search')}}" placeholder="Ketik kata pencarian"></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary flex-fill"><i class="bi bi-funnel me-1"></i>Filter</button><a class="btn btn-light" href="{{route('materials.index')}}" title="Reset filter"><i class="bi bi-x-lg"></i></a></div></div></form>
<div class="card p-3"><div class="d-flex justify-content-between mb-2"><b>Daftar Material</b><span class="badge text-bg-light">{{$materials->count()}} data</span></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Proyek</th><th>Kode</th><th>Jenis</th><th>Nama/Merek</th><th>Produsen/Sumber</th><th>Pemasok</th><th>Catatan</th><th>Aksi</th></tr></thead><tbody>
@forelse($materials as $m)<tr><td>{{$m->project->name??'Material umum'}}</td><td><b>{{$m->code}}</b></td><td><span class="badge text-bg-secondary">{{$m->type}}</span></td><td>{{$m->brand?:$m->name}}</td><td>{{$m->producer?:($m->quarry?:'—')}}</td><td>{{$m->supplier?:'—'}}</td><td>{{$m->notes?:'—'}}</td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editMaterial{{$m->id}}" title="Ubah material" aria-label="Ubah material"><i class="bi bi-pencil-square"></i></button><form method="post" action="{{route('materials.destroy',$m)}}" onsubmit="return confirm('Arsipkan material ini?')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger" title="Arsipkan" aria-label="Arsipkan material"><i class="bi bi-trash"></i></button></form></div></td></tr>
@empty<tr><td colspan="8" class="text-center text-secondary py-5">Tidak ada material yang sesuai filter.</td></tr>@endforelse
</tbody></table></div></div>

<div class="modal fade" id="add"><div class="modal-dialog modal-lg"><form method="post" action="{{route('materials.store')}}" class="modal-content">@csrf
<div class="modal-header"><h5>Tambah Sumber Material</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label">Proyek</label><select class="form-select" name="project_id"><option value="">Material umum</option>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->name}}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Kode *</label><input class="form-control" name="code" required></div><div class="col-md-3"><label class="form-label">Jenis *</label><select class="form-select" name="type" required>@foreach($allTypes as $type)<option>{{$type}}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Nama material *</label><input class="form-control" name="name" required></div><div class="col-md-6"><label class="form-label">Merek</label><input class="form-control" name="brand"></div>
<div class="col-md-4"><label class="form-label">Produsen</label><input class="form-control" name="producer"></div><div class="col-md-4"><label class="form-label">Lokasi sumber / quarry</label><input class="form-control" name="quarry"></div><div class="col-md-4"><label class="form-label">Pemasok</label><input class="form-control" name="supplier"></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes" rows="3"></textarea></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Material</button></div></form></div></div>

@foreach($materials as $m)
<div class="modal fade" id="editMaterial{{$m->id}}"><div class="modal-dialog modal-lg"><form method="post" action="{{route('materials.update',$m)}}" class="modal-content">@csrf @method('put')
<div class="modal-header"><h5>Ubah Sumber Material — {{$m->code}}</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><div class="modal-body"><div class="row g-3">
<div class="col-md-6"><label class="form-label">Proyek</label><select class="form-select" name="project_id"><option value="">Material umum</option>@foreach($projects as $p)<option value="{{$p->id}}" @selected($m->project_id==$p->id)>{{$p->name}}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Kode *</label><input class="form-control" name="code" value="{{$m->code}}" required></div><div class="col-md-3"><label class="form-label">Jenis *</label><select class="form-select" name="type" required>@foreach($allTypes as $type)<option @selected($m->type===$type)>{{$type}}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">Nama material *</label><input class="form-control" name="name" value="{{$m->name}}" required></div><div class="col-md-6"><label class="form-label">Merek</label><input class="form-control" name="brand" value="{{$m->brand}}"></div>
<div class="col-md-4"><label class="form-label">Produsen</label><input class="form-control" name="producer" value="{{$m->producer}}"></div><div class="col-md-4"><label class="form-label">Lokasi sumber / quarry</label><input class="form-control" name="quarry" value="{{$m->quarry}}"></div><div class="col-md-4"><label class="form-label">Pemasok</label><input class="form-control" name="supplier" value="{{$m->supplier}}"></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes" rows="3">{{$m->notes}}</textarea></div>
</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan Perubahan</button></div></form></div></div>
@endforeach
@endsection
