@extends('layouts.app') @section('title','Perencanaan Desain Campuran') @section('subtitle','Panduan bertahap SNI 7656:2012') @section('content')
<div class="d-flex justify-content-between mb-3"><div><h3 class="fw-bold">Desain Campuran Beton</h3><p class="text-secondary">Draf perencanaan, validasi, revisi, dan persetujuan.</p></div><button class="btn btn-primary align-self-start" data-bs-toggle="modal" data-bs-target="#add"><i class="bi bi-plus-lg me-2"></i>Buat Desain Campuran</button></div>
<div class="alert alert-warning border-0"><i class="bi bi-exclamation-triangle me-2"></i><b>Data referensi belum diisi.</b> Komposisi akhir hanya dapat dihitung setelah administrator memasukkan tabel resmi yang dimiliki laboratorium.</div>
<div class="card p-3"><table class="table align-middle"><thead><tr><th>Nomor</th><th>Proyek</th><th>Rencana</th><th>f'c</th><th>Slump</th><th>Status</th></tr></thead><tbody>@forelse($designs as $d)<tr><td><b>{{$d->number}}</b></td><td>{{$d->project?->name??'Proyek tidak tersedia'}} @if($d->project?->trashed())<span class="badge text-bg-light">Diarsipkan</span>@endif</td><td>{{$d->planned_at?->format('d/m/Y')??'—'}}<div class="small text-secondary">{{$d->designer}}</div></td><td>{{number_format($d->fc,2,',','.')}} MPa</td><td>{{number_format($d->slump_min,0,',','.')}}–{{number_format($d->slump_max,0,',','.')}} mm</td><td><span class="badge text-bg-secondary">{{$d->status==='draft'?'Draf':ucfirst($d->status)}}</span></td></tr>@empty<tr><td colspan="6" class="text-center text-secondary py-5">Belum ada desain campuran.</td></tr>@endforelse</tbody></table></div>
<div class="modal fade" id="add"><div class="modal-dialog modal-xl"><form method="post" action="{{route('mix-design.store')}}" class="modal-content">@csrf<div class="modal-header"><div><h5 class="mb-0">Desain Campuran Baru</h5><small class="text-secondary">Tahap 1–2 dari 7 • Identitas dan persyaratan beton</small></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><div class="modal-body">
<div class="progress mb-4" style="height:6px"><div class="progress-bar bg-success" style="width:28%"></div></div><div class="row g-3">
<div class="col-md-6"><label class="form-label">Proyek</label><select class="form-select" name="project_id" required><option value="">Pilih proyek</option>@foreach($projects as $p)<option value="{{$p->id}}">{{$p->number}} — {{$p->name}}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Tanggal perencanaan</label><input type="date" class="form-control" name="planned_at" value="{{date('Y-m-d')}}" required></div><div class="col-md-3"><label class="form-label">Perencana</label><input class="form-control" name="designer" value="{{auth()->user()->name}}" required></div>
<div class="col-md-3"><label class="form-label">Jenis beton</label><select class="form-select" name="concrete_type"><option>normal</option><option>berat</option><option>massa</option></select></div>
<div class="col-md-3"><label class="form-label">Kuat tekan karakteristik</label><div class="input-group"><input type="number" step=".01" min=".01" class="form-control" name="fc" required><span class="input-group-text">MPa</span></div></div>
<div class="col-md-3"><label class="form-label">Umur rencana</label><div class="input-group"><input type="number" min="1" class="form-control" name="design_age" value="28" required><span class="input-group-text">hari</span></div></div>
<div class="col-md-3"><label class="form-label">Deviasi standar</label><div class="input-group"><input type="number" step=".01" min="0" class="form-control" name="standard_deviation"><span class="input-group-text">MPa</span></div></div>
<div class="col-md-3"><label class="form-label">Slump minimum</label><div class="input-group"><input type="number" min="0" class="form-control" name="slump_min" required><span class="input-group-text">mm</span></div></div>
<div class="col-md-3"><label class="form-label">Slump maksimum</label><div class="input-group"><input type="number" min="0" class="form-control" name="slump_max" required><span class="input-group-text">mm</span></div></div>
<div class="col-md-3"><label class="form-label">Ukuran agregat maksimum</label><div class="input-group"><input type="number" step=".01" min=".01" class="form-control" name="max_aggregate_size" required><span class="input-group-text">mm</span></div></div>
<div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes"></textarea></div></div></div><div class="modal-footer"><span class="me-auto small text-secondary"><i class="bi bi-cloud-check me-1"></i>Disimpan sebagai draf, bukan laporan resmi</span><button class="btn btn-primary">Simpan Draf</button></div></form></div></div>@endsection
