@extends('layouts.app')
@section('title','Pengaturan Laporan')
@section('subtitle','Kop, tipografi, alamat pemeriksa, margin, dan penandatangan')
@section('content')
@php
$lines = $setting->resolvedHeaderLines($laboratory);
$fontFamilies = \App\Models\ReportSetting::FONT_FAMILIES;
@endphp
<form method="post" action="{{route('report-settings.update')}}" enctype="multipart/form-data" id="report-setting-form">@csrf @method('patch')
<div class="row g-4"><div class="col-xl-8">
<div class="card p-4 mb-4"><h5 class="fw-bold">Ukuran Halaman A4 dan Tipografi</h5><div class="row g-3">
@foreach(['top'=>'Atas','right'=>'Kanan','bottom'=>'Bawah','left'=>'Kiri'] as $key=>$label)<div class="col-sm-6 col-md-3"><label class="form-label">Margin {{$label}}</label><div class="input-group"><input type="number" step=".1" min="5" max="40" name="margin_{{$key}}" class="form-control live-setting" value="{{data_get($setting,'margin_'.$key)}}" required><span class="input-group-text">mm</span></div></div>@endforeach
<div class="col-12"><div class="border rounded bg-light p-3"><div class="row align-items-center g-3"><div class="col-md-5"><label class="form-label fw-bold mb-1">Jenis huruf seluruh isi laporan (di luar kop)</label><div class="form-text mt-0">Berlaku untuk sampul, judul BAB, subbab, paragraf, tabel, lampiran, dan footer. Tulisan kop tetap diatur per baris pada menu kop.</div></div><div class="col-md-7"><select name="font_family" class="form-select form-select-lg live-setting" aria-label="Jenis huruf seluruh isi laporan">@foreach($fontFamilies as $font)<option value="{{$font}}" style="font-family:'{{$font}}'" @selected($setting->font_family===$font)>{{$font}}</option>@endforeach</select></div></div></div></div>
@foreach([['font_size','Isi laporan',$setting->font_size,8,16],['report_heading_size','Judul BAB',$setting->report_heading_size,10,24],['report_subheading_size','Subjudul',$setting->report_subheading_size,9,20],['report_table_size','Tabel',$setting->report_table_size,8,14],['report_caption_size','Caption',$setting->report_caption_size,8,14]] as [$field,$label,$current,$min,$max])<div class="col-6 col-md-4"><label class="form-label">{{$label}}</label><div class="input-group"><input type="number" step=".5" min="{{$min}}" max="{{$max}}" name="{{$field}}" class="form-control live-setting" value="{{$current}}" required><span class="input-group-text">pt</span></div></div>@endforeach
<div class="col-6 col-md-4"><label class="form-label">Line spacing</label><input type="number" step=".05" min="1" max="2" name="report_line_height" class="form-control live-setting" value="{{$setting->report_line_height}}" required></div>
</div></div>

<div class="card p-4 mb-4"><h5 class="fw-bold">Pengaturan Kop Laporan</h5><div class="form-check form-switch mb-3"><input type="checkbox" class="form-check-input live-setting" name="header_lines_enabled" value="1" @checked($setting->header_lines_enabled)><label class="form-check-label">Tampilkan garis kop</label></div>
@foreach($lines as $index=>$line)<div class="border rounded p-3 mb-3"><b>Baris {{$index+1}}</b><div class="row g-2 mt-1"><div class="col-12"><label class="form-label">Isi tulisan</label><input class="form-control live-setting" name="header_lines[{{$index}}][text]" value="{{$line['text']}}"></div><div class="col-6 col-md-3"><label class="form-label">Ukuran</label><input type="number" step=".5" class="form-control live-setting" name="header_lines[{{$index}}][size]" value="{{$line['size']}}"></div><div class="col-6 col-md-3"><label class="form-label">Font</label><select class="form-select live-setting" name="header_lines[{{$index}}][font]">@foreach($fontFamilies as $font)<option value="{{$font}}" @selected($line['font']===$font)>{{$font}}</option>@endforeach</select></div><div class="col-6 col-md-3"><label class="form-label">Rata</label><select class="form-select live-setting" name="header_lines[{{$index}}][align]"><option value="left" @selected($line['align']==='left')>Kiri</option><option value="center" @selected($line['align']==='center')>Tengah</option><option value="right" @selected($line['align']==='right')>Kanan</option></select></div><div class="col-6 col-md-3"><label class="form-label">Line height</label><input type="number" step=".05" class="form-control live-setting" name="header_lines[{{$index}}][line_height]" value="{{$line['line_height']}}"></div>
<div class="col-6 col-md-3"><label class="form-label">Jarak atas</label><input type="number" step=".5" class="form-control live-setting" name="header_lines[{{$index}}][margin_top]" value="{{$line['margin_top']}}"></div><div class="col-6 col-md-3"><label class="form-label">Jarak bawah</label><input type="number" step=".5" class="form-control live-setting" name="header_lines[{{$index}}][margin_bottom]" value="{{$line['margin_bottom']}}"></div><div class="col-12 col-md-6 d-flex gap-3 align-items-end pb-2">@foreach(['bold'=>'Bold','italic'=>'Italic','uppercase'=>'Huruf besar'] as $flag=>$label)<label class="form-check"><input type="checkbox" class="form-check-input live-setting" name="header_lines[{{$index}}][{{$flag}}]" value="1" @checked($line[$flag])> {{$label}}</label>@endforeach</div></div></div>@endforeach
<div class="row g-3">@foreach([['header_line_1_width','Garis pertama','pt'],['header_line_2_width','Garis kedua','pt'],['header_line_gap','Jarak antar garis','mm'],['header_to_line_gap','Jarak kop ke garis','mm'],['line_to_content_gap','Jarak garis ke isi','mm']] as [$field,$label,$unit])<div class="col-sm-6 col-lg"><label class="form-label">{{$label}}</label><div class="input-group"><input type="number" step=".1" class="form-control live-setting" name="{{$field}}" value="{{$setting->$field}}"><span class="input-group-text">{{$unit}}</span></div></div>@endforeach</div></div>

<div class="card p-4 mb-4"><h5 class="fw-bold">Logo Kop</h5><div class="row g-3">
@foreach(['left'=>'Logo 1','right'=>'Logo 2'] as $side=>$caption)
@php
$logo = data_get($setting, 'logo_'.$side);
$logoPosition = data_get($setting, 'logo_'.$side.'_position');
@endphp
<div class="col-md-6"><div class="border rounded p-3 h-100"><label class="form-label fw-semibold">{{$caption}}</label><input type="file" name="logo_{{$side}}" class="form-control mb-2" accept="image/*"><div class="row g-2"><div class="col-6"><label class="form-label">Posisi</label><select name="logo_{{$side}}_position" class="form-select live-setting"><option value="left" @selected($logoPosition==='left')>Kiri</option><option value="center" @selected($logoPosition==='center')>Tengah</option><option value="right" @selected($logoPosition==='right')>Kanan</option></select></div><div class="col-6"><label class="form-label">Lebar (mm)</label><input type="number" step=".5" name="logo_{{$side}}_width" class="form-control live-setting" value="{{data_get($setting,'logo_'.$side.'_width')}}"></div><div class="col-6"><label class="form-label">Tinggi (mm/Auto)</label><input type="number" step=".5" name="logo_{{$side}}_height" class="form-control live-setting" value="{{data_get($setting,'logo_'.$side.'_height')}}"></div><div class="col-6"><label class="form-label">Geser X (mm)</label><input type="number" step=".5" name="logo_{{$side}}_x" class="form-control live-setting" value="{{data_get($setting,'logo_'.$side.'_x')}}"></div><div class="col-6"><label class="form-label">Geser Y (mm)</label><input type="number" step=".5" name="logo_{{$side}}_y" class="form-control live-setting" value="{{data_get($setting,'logo_'.$side.'_y')}}"></div></div>@if($logo)<img class="img-fluid mt-3" style="height:70px" src="{{asset('storage/'.$logo)}}">@endif</div></div>
@endforeach
</div></div>

<div class="card p-4 mb-4"><h5 class="fw-bold">Alamat Laboratorium/Pemeriksa</h5><div class="row g-3"><div class="col-12"><label class="form-label">Alamat pemeriksa</label><textarea name="examiner_address" class="form-control" rows="2">{{$setting->examiner_address}}</textarea></div>@foreach([['examiner_city','Kota'],['examiner_province','Provinsi'],['examiner_postal_code','Kode pos'],['examiner_phone','Telepon'],['examiner_email','Email'],['examiner_website','Website']] as [$field,$label])<div class="col-md-4"><label class="form-label">{{$label}}</label><input name="{{$field}}" class="form-control" value="{{$setting->$field}}"></div>@endforeach</div></div>

<div class="card p-4 mb-4"><h5 class="fw-bold">Data Penandatangan</h5><div class="row g-3"><div class="col-md-6"><label class="form-label">Nama Kepala Laboratorium</label><input name="signer_name" class="form-control" value="{{$setting->signer_name}}" required></div><div class="col-md-6"><label class="form-label">Jabatan</label><input name="signer_position" class="form-control" value="{{$setting->signer_position}}" required></div><div class="col-md-6"><label class="form-label">NIDN/NIP/NBM/Identitas</label><input name="signer_identity" class="form-control" value="{{$setting->signer_identity}}"></div><div class="col-md-3"><label class="form-label">Tanda tangan</label><input type="file" name="signature_image" class="form-control" accept="image/*"></div><div class="col-md-3"><label class="form-label">Stempel</label><input type="file" name="stamp_image" class="form-control" accept="image/*"></div><div class="col-12"><label class="form-label">Pola kata pengantar</label><textarea name="preface_template" rows="5" class="form-control">{{$setting->preface_template}}</textarea></div></div></div>
</div>
<div class="col-xl-4"><div class="card p-3 position-sticky" style="top:85px"><h5 class="fw-bold">Preview Langsung</h5><div id="letterhead-preview" class="bg-white border shadow-sm p-3" style="min-height:370px"></div><div class="d-grid gap-2 mt-3"><button class="btn btn-primary"><i class="bi bi-save me-2"></i>Simpan</button><a class="btn btn-outline-primary" target="_blank" href="{{route('report-settings.preview')}}"><i class="bi bi-eye me-2"></i>Preview Laporan</a></div></div></div></div>
</form>
@endsection
@push('scripts')<script>
function renderPreview(){const form=document.getElementById('report-setting-form'),host=document.getElementById('letterhead-preview'),get=n=>form.elements[n]?.value||'',check=n=>form.elements[n]?.checked,scaled=n=>Math.max(6,Number(n||10)*.48);let lines='';for(let i=0;i<5;i++){const text=get(`header_lines[${i}][text]`),size=scaled(get(`header_lines[${i}][size]`)),font=get(`header_lines[${i}][font]`),align=get(`header_lines[${i}][align]`);lines+=`<div style="font:${check(`header_lines[${i}][italic]`)?'italic':'normal'} ${check(`header_lines[${i}][bold]`)?'700':'400'} ${size}pt '${font}';text-align:${align};text-transform:${check(`header_lines[${i}][uppercase]`)?'uppercase':'none'};line-height:${get(`header_lines[${i}][line_height]`)};margin:${get(`header_lines[${i}][margin_top]`)}px 0 ${get(`header_lines[${i}][margin_bottom]`)}px">${text||'&nbsp;'}</div>`}const borders=check('header_lines_enabled')?`<div style="border-top:${get('header_line_1_width')}pt solid;margin-top:${get('header_to_line_gap')}mm"></div><div style="border-top:${get('header_line_2_width')}pt solid;margin-top:${get('header_line_gap')}mm"></div>`:'';host.innerHTML=`<div style="font-family:'${get('font_family')}'">${lines}<div style="text-align:center;font-size:6pt">${get('examiner_address')} ${get('examiner_city')}</div>${borders}<h4 style="font-size:${scaled(get('report_heading_size'))}pt;margin-top:${get('line_to_content_gap')}mm">BAB I DATA DAN INFORMASI PEKERJAAN</h4><p style="font-size:${scaled(get('font_size'))}pt;line-height:${get('report_line_height')}">Contoh teks isi laporan dan data proyek.</p><table style="width:100%;font-size:${scaled(get('report_table_size'))}pt;border-collapse:collapse"><tr><th style="border:1px solid">Parameter</th><th style="border:1px solid">Nilai</th></tr><tr><td style="border:1px solid">Slump</td><td style="border:1px solid;text-align:center">80 mm</td></tr></table></div>`}document.querySelectorAll('.live-setting,#report-setting-form input,#report-setting-form textarea,#report-setting-form select').forEach(el=>el.addEventListener('input',renderPreview));renderPreview();
</script>@endpush
