@extends('layouts.app')
@section('title','Pengaturan Laporan')
@section('subtitle','Format cetak, logo, dan QR Kepala Laboratorium')
@section('content')
<form method="post" action="{{route('report-settings.update')}}" enctype="multipart/form-data">@csrf @method('patch')
<div class="card p-4 mb-4"><h5 class="fw-bold">Ukuran Halaman A4</h5><div class="row g-3">@foreach(['top'=>'Atas','right'=>'Kanan','bottom'=>'Bawah','left'=>'Kiri'] as $key=>$label)<div class="col-md-3"><label class="form-label">Margin {{$label}}</label><div class="input-group"><input type="number" step=".1" min="5" max="40" name="margin_{{$key}}" class="form-control" value="{{data_get($setting,'margin_'.$key)}}" required><span class="input-group-text">mm</span></div></div>@endforeach<div class="col-md-6"><label class="form-label">Jenis huruf</label><select name="font_family" class="form-select">@foreach(['Arial','Calibri','Times New Roman','Verdana'] as $font)<option @selected($setting->font_family===$font)>{{$font}}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Ukuran huruf</label><div class="input-group"><input type="number" step=".5" min="8" max="16" name="font_size" class="form-control" value="{{$setting->font_size}}"><span class="input-group-text">pt</span></div></div></div></div>
<div class="card p-4 mb-4"><h5 class="fw-bold">Logo dan Legalisasi</h5><div class="alert alert-info py-2">Logo tampil pada kepala setiap halaman laporan. Pilih posisi dan lebarnya, lalu simpan.</div><div class="row g-3">
@foreach(['left'=>'Logo 1','right'=>'Logo 2'] as $side=>$caption)
<div class="col-md-6"><div class="border rounded p-3 h-100"><label class="form-label fw-semibold">{{$caption}}</label><input type="file" name="logo_{{$side}}" class="form-control" accept=".png,.jpg,.jpeg,.webp,image/*"><div class="row g-2 mt-1"><div class="col-7"><label class="form-label small">Posisi</label><select name="logo_{{$side}}_position" class="form-select"><option value="left" @selected(data_get($setting,'logo_'.$side.'_position')==='left')>Kiri</option><option value="center" @selected(data_get($setting,'logo_'.$side.'_position')==='center')> Tengah</option><option value="right" @selected(data_get($setting,'logo_'.$side.'_position')==='right')>Kanan</option></select></div><div class="col-5"><label class="form-label small">Lebar</label><div class="input-group"><input type="number" name="logo_{{$side}}_width" min="8" max="35" step=".5" class="form-control" value="{{data_get($setting,'logo_'.$side.'_width',18)}}"><span class="input-group-text">mm</span></div></div></div>@if(data_get($setting,'logo_'.$side))<div class="mt-3 p-2 bg-light rounded text-center"><img src="{{asset('storage/'.data_get($setting,'logo_'.$side))}}" alt="{{$caption}}" style="height:70px;max-width:100%;object-fit:contain"><div class="small text-success mt-1">Logo tersimpan</div></div>@endif</div></div>
@endforeach
<div class="col-md-6"><label class="form-label">Nama Kepala Laboratorium</label><input name="signer_name" class="form-control" value="{{$setting->signer_name}}" required></div><div class="col-md-6"><label class="form-label">Jabatan</label><input name="signer_position" class="form-control" value="{{$setting->signer_position?:'Kepala Laboratorium'}}" required></div><div class="col-12"><div class="alert alert-success py-2 mb-0">Satu kode QR akan dibuat otomatis pada bagian tanda tangan Kepala Laboratorium. Kode QR berubah untuk setiap dokumen dan identitas penandatangan hanya ditampilkan setelah dipindai.</div></div><div class="col-12"><label class="form-label">Pola kata pengantar</label><textarea name="preface_template" rows="6" class="form-control" placeholder="Gunakan [PROYEK], [PERUSAHAAN], dan [TANGGAL] sebagai penanda otomatis.">{{$setting->preface_template}}</textarea></div></div></div>
<button class="btn btn-primary px-4">Simpan Pengaturan Laporan</button></form>
@endsection
