<!doctype html><html lang="id"><head><meta charset="utf-8"><title>Preview Pengaturan Laporan</title><style>@page{size:A4;margin:{{$setting->margin_top}}mm {{$setting->margin_right}}mm {{$setting->margin_bottom}}mm {{$setting->margin_left}}mm}body{margin:0;background:#dfe5e7;font-family:"{{$setting->font_family}}"}.page{box-sizing:border-box;width:210mm;min-height:297mm;margin:15px auto;background:#fff;padding:{{$setting->margin_top}}mm {{$setting->margin_right}}mm {{$setting->margin_bottom}}mm {{$setting->margin_left}}mm}.header{position:relative;text-align:center}.header img{position:absolute;object-fit:contain}.line1,.line2{width:100%}.line1{border-top:{{$setting->header_line_1_width}}pt solid;margin-top:{{$setting->header_to_line_gap}}mm}.line2{border-top:{{$setting->header_line_2_width}}pt solid;margin-top:{{$setting->header_line_gap}}mm}.body{font-size:{{$setting->font_size}}pt;line-height:{{$setting->report_line_height}}}.body h1{font-size:{{$setting->report_heading_size}}pt}.body h2{font-size:{{$setting->report_subheading_size}}pt}.body table{width:100%;border-collapse:collapse;font-size:{{$setting->report_table_size}}pt}.body th,.body td{border:1px solid;padding:5px;text-align:center}@media print{body{background:#fff}.page{margin:0;padding:0;min-height:auto}}</style></head><body><section class="page"><div class="header">
@foreach(['left','right'] as $side)
@php
$logo = data_get($setting, 'logo_'.$side);
$logoWidth = data_get($setting, 'logo_'.$side.'_width');
$logoHeight = data_get($setting, 'logo_'.$side.'_height');
$logoPosition = data_get($setting, 'logo_'.$side.'_position');
$logoX = data_get($setting, 'logo_'.$side.'_x');
$logoY = data_get($setting, 'logo_'.$side.'_y');
@endphp
@if($logo)<img src="{{asset('storage/'.$logo)}}" style="width:{{$logoWidth}}mm;@if($logoHeight)height:{{$logoHeight}}mm;@endif {{$logoPosition}}:{{$logoX}}mm;top:{{$logoY}}mm">@endif
@endforeach
@foreach($setting->resolvedHeaderLines($laboratory) as $line)<div style="font-family:'{{$line['font']}}';font-size:{{$line['size']}}pt;font-weight:{{$line['bold']?700:400}};font-style:{{$line['italic']?'italic':'normal'}};text-transform:{{$line['uppercase']?'uppercase':'none'}};text-align:{{$line['align']}};line-height:{{$line['line_height']}};margin:{{$line['margin_top']}}mm 0 {{$line['margin_bottom']}}mm">{{$line['text']}}</div>@endforeach <div style="font-size:9pt">{{$setting->examiner_address}}@if($setting->examiner_city), {{$setting->examiner_city}}@endif</div>@if($setting->header_lines_enabled)<div class="line1"></div><div class="line2"></div>@endif</div><main class="body" style="margin-top:{{$setting->line_to_content_gap}}mm"><h1>PREVIEW LAPORAN LABORATORIUM</h1><h2>1.1 Data Umum Pekerjaan</h2><p>Nama pekerjaan: {{$project?->name?:'Contoh Nama Pekerjaan'}}</p><table><tr><th>Parameter</th><th>Nilai</th></tr><tr><td>Slump Beton Segar</td><td>80 mm</td></tr></table><div style="margin-top:30mm;text-align:center"><div>{{$setting->signer_position}}</div>@if($setting->signature_image)<img src="{{asset('storage/'.$setting->signature_image)}}" style="height:25mm">@else<div style="height:25mm"></div>@endif<div><b>{{$setting->signer_name}}</b></div><div>{{$setting->signer_identity}}</div></div></main></section></body></html>
