@extends('layouts.app')
@section('title','Master Standar JMD')
@section('subtitle','Tabel referensi berversi untuk perhitungan dan pengujian')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h3 class="fw-bold mb-1">Master Tabel Perencanaan</h3><p class="text-secondary mb-0">Revisi membuat versi baru; snapshot pengujian lama tidak berubah.</p></div><button class="btn btn-primary align-self-start" data-bs-toggle="modal" data-bs-target="#newStandard"><i class="bi bi-plus-lg me-2"></i>Referensi Baru</button></div>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="card p-3"><div class="small text-secondary">Referensi ditemukan</div><div class="fs-3 fw-bold">{{ $standards->total() }}</div></div></div><div class="col-md-4"><div class="card p-3"><div class="small text-secondary">Tabel aktif</div><div class="fs-3 fw-bold">{{ $activeTableCount }} / 20 jenis</div></div></div><div class="col-md-4"><div class="card p-3"><div class="small text-secondary">Nilai aktif</div><div class="fs-3 fw-bold">{{ $activeValueCount }}</div></div></div></div>
<div class="card p-3 mb-3"><form class="row g-2"><div class="col-md-7"><input class="form-control" name="q" value="{{ request('q') }}" placeholder="Cari nama atau nomor standar"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">Semua versi</option><option value="active" @selected(request('status')==='active')>Aktif</option><option value="inactive" @selected(request('status')==='inactive')>Riwayat/nonaktif</option></select></div><div class="col-md-2 d-grid"><button class="btn btn-outline-primary">Tampilkan</button></div></form></div>

<div class="accordion" id="standardsAccordion">
@forelse($standards as $standard)<div class="accordion-item border-0 card mb-3"><h2 class="accordion-header"><button class="accordion-button collapsed rounded" type="button" data-bs-toggle="collapse" data-bs-target="#standard{{ $standard->id }}"><span class="flex-grow-1"><b>{{ $standard->standard_number ?: 'Tanpa nomor' }}</b> — {{ $standard->name }} <span class="badge ms-2 {{ $standard->is_active?'text-bg-success':'text-bg-secondary' }}">Rev. {{ $standard->revision_number }} · {{ $standard->is_active?'Aktif':'Riwayat' }}</span></span><span class="small text-secondary me-3">{{ $standard->tables->count() }} tabel</span></button></h2>
<div id="standard{{ $standard->id }}" class="accordion-collapse collapse" data-bs-parent="#standardsAccordion"><div class="accordion-body">
 <div class="row g-3 mb-3"><div class="col-md-8"><div class="small text-secondary">Berlaku</div>{{ optional($standard->effective_at)->format('d/m/Y') ?: 'Tidak ditentukan' }} @if($standard->expires_at) s.d. {{ $standard->expires_at->format('d/m/Y') }} @endif<div class="mt-2">{{ $standard->description }}</div></div><div class="col-md-4 text-md-end"><form method="post" action="{{ route('jmd.standards.toggle',$standard) }}" class="d-inline">@csrf @method('patch')<button class="btn btn-sm btn-outline-secondary">{{ $standard->is_active?'Nonaktifkan':'Aktifkan' }}</button></form>@if($standard->is_active)<button class="btn btn-sm btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#reviseStandard{{ $standard->id }}">Buat Revisi</button>@endif</div></div>
 @if($standard->is_active)<div class="collapse mb-3" id="reviseStandard{{ $standard->id }}"><form method="post" action="{{ route('jmd.standards.revise',$standard) }}" class="border rounded p-3 bg-light">@csrf <h6>Revisi Referensi</h6><div class="row g-2"><div class="col-md-6"><input class="form-control" name="name" value="{{ $standard->name }}" required></div><div class="col-md-3"><input class="form-control" name="standard_number" value="{{ $standard->standard_number }}" placeholder="Nomor"></div><div class="col-md-3"><input class="form-control" name="standard_year" value="{{ $standard->standard_year }}" placeholder="Tahun"></div><div class="col-md-3"><input type="date" class="form-control" name="effective_at" value="{{ optional($standard->effective_at)->format('Y-m-d') }}"></div><div class="col-md-9"><input class="form-control" name="source_url" value="{{ $standard->source_url }}" placeholder="URL sumber resmi"></div><div class="col-12"><textarea class="form-control" name="description" rows="2">{{ $standard->description }}</textarea></div><div class="col-12 text-end"><button class="btn btn-primary btn-sm">Simpan Sebagai Revisi Baru</button></div></div></form></div>@endif

 @foreach($standard->tables as $table)<div class="border rounded p-3 mb-3 {{ !$table->is_active?'opacity-75 bg-light':'' }}"><div class="d-flex justify-content-between gap-2"><div><h6 class="mb-1">{{ $table->name }} <span class="badge text-bg-light">{{ $table->key }}</span></h6><div class="small text-secondary">Revisi {{ $table->revision_number }} · {{ $table->unit ?: 'tanpa satuan' }} · {{ $table->is_active?'aktif':'riwayat' }}</div></div>@if($standard->is_active&&$table->is_active)<button class="btn btn-sm btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#tableEdit{{ $table->id }}">Revisi Tabel</button>@endif</div>
 @if($standard->is_active&&$table->is_active)<div class="collapse mt-3" id="tableEdit{{ $table->id }}"><form method="post" action="{{ route('jmd.standard-tables.revise',$table) }}" class="row g-2 bg-light p-2 rounded">@csrf<input type="hidden" name="key" value="{{ $table->key }}"><div class="col-md-5"><input class="form-control form-control-sm" name="name" value="{{ $table->name }}" required></div><div class="col-md-2"><input class="form-control form-control-sm" name="unit" value="{{ $table->unit }}" placeholder="Satuan"></div><div class="col-md-3"><input class="form-control form-control-sm" name="notes" value="{{ $table->notes }}" placeholder="Catatan"></div><div class="col-md-2 d-grid"><button class="btn btn-sm btn-primary">Buat Revisi</button></div></form></div>@endif
 <div class="table-responsive mt-3"><table class="table table-sm align-middle"><thead><tr><th>Baris/Kolom</th><th>Dimensi</th><th>Nilai</th><th>Min–Maks</th><th>Satuan</th><th></th></tr></thead><tbody>@forelse($table->values as $value)<tr><td>{{ $value->row_key ?: '—' }} / {{ $value->column_key ?: '—' }}</td><td><code>{{ json_encode($value->dimension_values,JSON_UNESCAPED_UNICODE) }}</code></td><td>{{ $value->numeric_value ?? $value->text_value ?? '—' }}</td><td>{{ $value->min_value ?? '—' }} – {{ $value->max_value ?? '—' }}</td><td>{{ $value->unit ?: $table->unit }}</td><td class="text-end">@if($standard->is_active&&$table->is_active)<button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editValue{{ $value->id }}"><i class="bi bi-pencil"></i></button><form class="d-inline" method="post" action="{{ route('jmd.standard-values.destroy',$value) }}" onsubmit="return confirm('Hentikan nilai ini pada revisi baru?')">@csrf @method('delete')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-x-lg"></i></button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-secondary">Belum ada nilai.</td></tr>@endforelse</tbody></table></div>
 @if($standard->is_active&&$table->is_active)<form method="post" action="{{ route('jmd.standard-values.store',$table) }}" class="row g-2 border-top pt-3">@csrf<div class="col-md-2"><input class="form-control form-control-sm" name="row_key" placeholder="Baris"></div><div class="col-md-2"><input class="form-control form-control-sm" name="column_key" placeholder="Kolom"></div><div class="col-md-2"><input type="number" step="any" class="form-control form-control-sm" name="numeric_value" placeholder="Nilai angka"></div><div class="col-md-2"><input class="form-control form-control-sm" name="text_value" placeholder="Nilai teks"></div><div class="col-md-2"><input class="form-control form-control-sm" name="unit" value="{{ $table->unit }}" placeholder="Satuan"></div><div class="col-md-2 d-grid"><button class="btn btn-sm btn-outline-primary">Tambah Nilai</button></div></form>@endif</div>
 @endforeach
 @if($standard->is_active)<form method="post" action="{{ route('jmd.standard-tables.store',$standard) }}" class="row g-2 border rounded p-3">@csrf<h6>Tambah Kelompok Tabel</h6><div class="col-md-5"><select class="form-select" name="key" required><option value="">Pilih kelompok</option>@foreach($catalog as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="col-md-4"><input class="form-control" name="name" placeholder="Nama tabel" required></div><div class="col-md-2"><input class="form-control" name="unit" placeholder="Satuan"></div><div class="col-md-1 d-grid"><button class="btn btn-primary"><i class="bi bi-plus-lg"></i></button></div></form>@endif
</div></div></div>
@empty<div class="card p-5 text-center text-secondary">Belum ada master standar.</div>@endforelse
</div><div class="mt-3">{{ $standards->links() }}</div>

<div class="modal fade" id="newStandard"><div class="modal-dialog modal-lg"><form method="post" action="{{ route('jmd.standards.store') }}" class="modal-content">@csrf<div class="modal-header"><h5 class="modal-title">Referensi Standar Baru</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-12"><label class="form-label">Nama standar *</label><input class="form-control" name="name" required></div><div class="col-md-4"><label class="form-label">Nomor standar</label><input class="form-control" name="standard_number"></div><div class="col-md-4"><label class="form-label">Tahun</label><input class="form-control" name="standard_year"></div><div class="col-md-4"><label class="form-label">Tanggal berlaku</label><input type="date" class="form-control" name="effective_at"></div><div class="col-12"><label class="form-label">URL sumber resmi</label><input type="url" class="form-control" name="source_url"></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="description"></textarea></div></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Referensi</button></div></form></div></div>
@foreach($standards as $standard)@foreach($standard->tables as $table)@foreach($table->values as $value)<div class="modal fade" id="editValue{{ $value->id }}"><div class="modal-dialog"><form method="post" action="{{ route('jmd.standard-values.update',$value) }}" class="modal-content">@csrf @method('put')<div class="modal-header"><h5 class="modal-title">Revisi Nilai</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="is_active" value="0"><div class="row g-2"><div class="col-6"><label class="form-label">Baris</label><input class="form-control" name="row_key" value="{{ $value->row_key }}"></div><div class="col-6"><label class="form-label">Kolom</label><input class="form-control" name="column_key" value="{{ $value->column_key }}"></div><div class="col-6"><label class="form-label">Nilai angka</label><input type="number" step="any" class="form-control" name="numeric_value" value="{{ $value->numeric_value }}"></div><div class="col-6"><label class="form-label">Nilai teks</label><input class="form-control" name="text_value" value="{{ $value->text_value }}"></div><div class="col-4"><label class="form-label">Minimum</label><input type="number" step="any" class="form-control" name="min_value" value="{{ $value->min_value }}"></div><div class="col-4"><label class="form-label">Maksimum</label><input type="number" step="any" class="form-control" name="max_value" value="{{ $value->max_value }}"></div><div class="col-4"><label class="form-label">Satuan</label><input class="form-control" name="unit" value="{{ $value->unit }}"></div><div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes">{{ $value->notes }}</textarea></div><div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="active{{ $value->id }}" @checked($value->is_active)><label class="form-check-label" for="active{{ $value->id }}">Aktif</label></div></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan sebagai Revisi Tabel</button></div></form></div></div>@endforeach @endforeach @endforeach
@endsection
