@extends('layouts.app')
@section('title',$config['title'])
@section('subtitle',($project->jmd_number ?: $project->number).' — '.$project->name)
@section('content')
@php
$definitions = [
 'moisture' => [['container_mass','Massa wadah W1','number'],['wet_container_mass','Wadah + basah W2','number'],['dry_container_mass','Wadah + kering W3','number']],
 'silt' => [['container_mass','Massa wadah','number'],['before_wash_container_mass','Wadah + sebelum cuci','number'],['after_wash_container_mass','Wadah + setelah cuci','number']],
 'fine-specific-gravity' => [['pycnometer_mass','Piknometer','number'],['ssd_sample_mass','Sampel SSD (B)','number'],['pycnometer_sample_water_mass','Piknometer+sampel+air (C)','number'],['pycnometer_water_mass','Piknometer+air (D)','number'],['oven_dry_sample_mass','Kering oven (E)','number']],
 'coarse-specific-gravity' => [['ssd_air_mass','SSD di udara (A)','number'],['submerged_mass','Dalam air (B)','number'],['oven_dry_mass','Kering oven (C)','number']],
 'bulk-density' => [['condition','Kondisi','condition'],['mould_volume_cm3','Volume mould (cm³)','number'],['mould_mass','Massa mould','number'],['filled_mould_mass','Mould + bahan','number']],
 'cement-specific-gravity' => [['bottle_kerosene_mass','Botol + kerosin','number'],['bottle_cement_kerosene_mass','Botol + semen + kerosin','number'],['initial_reading_ml','Bacaan awal (ml)','number'],['final_reading_ml','Bacaan akhir (ml)','number'],['test_temperature_c','Suhu (°C)','number'],['water_density','Densitas air','number']],
 'sieve' => [['sieve_label','Saringan','text'],['sieve_size_mm','Ukuran (mm)','number'],['is_pan','Pan','checkbox'],['retained_mass','Massa tertahan','number'],['lower_limit_percent','Batas bawah (%)','number'],['upper_limit_percent','Batas atas (%)','number'],['planned_passing_percent','Rencana lolos (%)','number']],
 'abrasion' => [['passing_sieve_mm','Lolos saringan (mm)','number'],['retained_sieve_mm','Tertahan saringan (mm)','number'],['initial_mass','Massa awal','number'],['retained_no12_mass','Tertahan No. 12','number']],
];
$rows = old('observations', $record ? $record->items->map->toArray()->all() : [[],[]]);
$value = fn($name,$default=null) => old($name, data_get($record,$name,$default));
$storeRoute = route('jmd.material-tests.'.$module.'.store',$project);
@endphp
<div class="d-flex justify-content-between flex-wrap gap-2 mb-3"><div><a class="small text-decoration-none" href="{{ route('jmd.material-tests.index',$project) }}"><i class="bi bi-arrow-left me-1"></i>Dashboard pengujian</a><h3 class="fw-bold mt-2 mb-0">{{ $config['title'] }}</h3></div>@if($record)<div class="text-end"><div class="small text-secondary">Nomor pengujian</div><b>{{ $record->test_number }}</b></div>@endif</div>

<form method="post" action="{{ $storeRoute }}" id="test-form">@csrf
<input type="hidden" name="project_id" value="{{ $project->id }}"><input type="hidden" name="test_id" value="{{ $record?->id }}">
<div class="card p-4 mb-3"><h5 class="mb-3">Identitas Pengujian</h5><div class="row g-3">
 <div class="col-md-4"><label class="form-label">Tanggal uji *</label><input type="date" class="form-control" name="tested_at" value="{{ $value('tested_at',now()->format('Y-m-d')) instanceof \Carbon\CarbonInterface ? $value('tested_at')->format('Y-m-d') : $value('tested_at',now()->format('Y-m-d')) }}" required></div>
 <div class="col-md-4"><label class="form-label">Teknisi *</label><input class="form-control" name="technician" value="{{ $value('technician',auth()->user()->name) }}" required></div>
 <div class="col-md-4"><label class="form-label">Nomor sampel</label><input class="form-control" name="sample_number" value="{{ $value('sample_number') }}"></div>
 <div class="col-md-6"><label class="form-label">Material proyek</label><select class="form-select" name="jmd_project_material_id"><option value="">— Tidak ditautkan —</option>@foreach($materials as $material)<option value="{{ $material->id }}" @selected((string)$value('jmd_project_material_id')===(string)$material->id)>{{ ucfirst($material->material_type) }} — {{ $material->name ?: $material->source ?: 'Material #'.$material->id }}</option>@endforeach</select></div>
 <div class="col-md-6"><label class="form-label">Sumber standar/acuan *</label><input class="form-control" name="standard_source" value="{{ old('standard_source',data_get($record,'standard_snapshot.source')) }}" placeholder="Contoh: SNI 1971:2011" required><div class="form-text">Acuan disimpan bersama snapshot hasil.</div></div>
 @if(in_array($module,['moisture','silt','sieve']))<div class="col-md-4"><label class="form-label">Jenis agregat *</label><select class="form-select" name="aggregate_type" required><option value="fine" @selected($value('aggregate_type',request('aggregate_type','fine'))==='fine')>Halus</option><option value="coarse" @selected($value('aggregate_type',request('aggregate_type'))==='coarse')>Kasar</option></select></div>@endif
 @if($module==='silt')<div class="col-md-4"><label class="form-label">Batas kadar lumpur (%) *</label><input type="number" step="any" min="0" class="form-control" name="limit_percent" value="{{ $value('limit_percent') }}" required></div>@endif
 @if($module==='bulk-density')<div class="col-md-4"><label class="form-label">Jenis material *</label><select class="form-select" name="material_type"><option value="fine" @selected($value('material_type','fine')==='fine')>Agregat halus</option><option value="coarse" @selected($value('material_type')==='coarse')>Agregat kasar</option><option value="cement" @selected($value('material_type')==='cement')>Semen</option></select></div><div class="col-md-4"><label class="form-label">Satuan massa *</label><select class="form-select" name="mass_unit"><option value="g" @selected(old('mass_unit',data_get($record,'standard_snapshot.mass_unit','g'))==='g')>gram</option><option value="kg" @selected(old('mass_unit',data_get($record,'standard_snapshot.mass_unit'))==='kg')>kilogram</option></select></div>@endif
 @if($module==='sieve')<div class="col-md-4"><label class="form-label">Massa awal (g) *</label><input type="number" step="any" min="0.000001" class="form-control" name="initial_sample_mass" value="{{ $value('initial_sample_mass') }}" required></div><div class="col-md-4"><label class="form-label">Toleransi kehilangan (%) *</label><input type="number" step="any" min="0" class="form-control" name="loss_tolerance_percent" value="{{ $value('loss_tolerance_percent') }}" required></div><div class="col-md-4"><label class="form-label">Zona gradasi</label><input class="form-control" name="gradation_zone" value="{{ $value('gradation_zone') }}"></div>@endif
 @if($module==='abrasion')<div class="col-md-3"><label class="form-label">Gradasi pemeriksaan</label><input class="form-control" name="inspection_gradation" value="{{ $value('inspection_gradation') }}"></div><div class="col-md-3"><label class="form-label">Jumlah bola baja</label><input type="number" min="0" class="form-control" name="steel_ball_count" value="{{ $value('steel_ball_count') }}"></div><div class="col-md-3"><label class="form-label">Jumlah putaran</label><input type="number" min="0" class="form-control" name="revolution_count" value="{{ $value('revolution_count') }}"></div><div class="col-md-3"><label class="form-label">Batas abrasi (%) *</label><input type="number" step="any" min="0" max="100" class="form-control" name="limit_percent" value="{{ $value('limit_percent') }}" required></div>@endif
 <div class="col-12"><label class="form-label">Catatan</label><textarea class="form-control" name="notes" rows="2">{{ $value('notes') }}</textarea></div>
</div></div>

<div class="card p-4 mb-3"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="mb-1">Observasi</h5><div class="small text-secondary">Minimal dua baris. Hapus baris lalu simpan untuk menghapus observasi terpilih.</div></div><button type="button" class="btn btn-sm btn-outline-primary" id="add-row"><i class="bi bi-plus-lg me-1"></i>Tambah baris</button></div>
<div class="table-responsive"><table class="table align-middle"><thead><tr><th style="width:45px">No.</th>@foreach($definitions[$module] as [$name,$label])<th>{{ $label }}</th>@endforeach<th style="width:50px"></th></tr></thead><tbody id="observation-rows">
@foreach($rows as $index=>$row)<tr data-row><td class="row-number">{{ $index+1 }}</td><input type="hidden" data-field="id" name="observations[{{ $index }}][id]" value="{{ $row['id']??'' }}">@foreach($definitions[$module] as [$name,$label,$type])<td>@if($type==='condition')<select class="form-select form-select-sm" data-field="{{ $name }}" name="observations[{{ $index }}][{{ $name }}]" required><option value="loose" @selected(($row[$name]??'loose')==='loose')>Lepas</option><option value="rodded" @selected(($row[$name]??'')==='rodded')>Padat/ditusuk</option></select>@elseif($type==='checkbox')<div class="form-check"><input type="hidden" data-checkbox-hidden="{{ $name }}" name="observations[{{ $index }}][{{ $name }}]" value="0"><input class="form-check-input" type="checkbox" data-field="{{ $name }}" name="observations[{{ $index }}][{{ $name }}]" value="1" @checked($row[$name]??false)></div>@else<input class="form-control form-control-sm" type="{{ $type }}" data-field="{{ $name }}" name="observations[{{ $index }}][{{ $name }}]" value="{{ $row[$name]??'' }}" @if($type==='number') step="any" min="0" @endif @if(!in_array($name,['test_temperature_c','sieve_size_mm','lower_limit_percent','upper_limit_percent','planned_passing_percent','passing_sieve_mm','retained_sieve_mm'])) required @endif>@endif</td>@endforeach<td><button type="button" class="btn btn-sm btn-outline-danger remove-row" title="Hapus baris"><i class="bi bi-x-lg"></i></button></td></tr>@endforeach
</tbody></table></div></div>
<div class="d-flex justify-content-end gap-2 mb-4"><a href="{{ route('jmd.material-tests.index',$project) }}" class="btn btn-light">Batal</a><button class="btn btn-primary" @disabled($project->locked_at)><i class="bi bi-calculator me-2"></i>Simpan & Hitung Ulang</button></div>
</form>

@if($record?->result_snapshot)<div class="card p-4 mb-3"><div class="d-flex justify-content-between"><h5>Hasil Perhitungan</h5><span class="badge {{ data_get($record->result_snapshot,'valid')?'text-bg-success':'text-bg-warning' }}">{{ data_get($record->result_snapshot,'valid')?'Valid':'Perlu verifikasi' }}</span></div><pre class="bg-light rounded p-3 mb-0 mt-2" style="white-space:pre-wrap">{{ json_encode(data_get($record->result_snapshot,'rounded'),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre>@if(data_get($record->result_snapshot,'messages'))<div class="alert alert-warning mt-3 mb-0">{{ implode(' ',data_get($record->result_snapshot,'messages')) }}</div>@endif</div>@endif

@if($history->isNotEmpty())<div class="card p-3"><h5 class="mb-3">Riwayat Pengujian</h5><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Nomor</th><th>Tanggal</th><th>Teknisi</th><th>Status</th><th></th></tr></thead><tbody>@foreach($history as $item)<tr><td>{{ $item->test_number }}</td><td>{{ optional($item->tested_at)->format('d/m/Y') }}</td><td>{{ $item->technician }}</td><td>{{ str_replace('_',' ',$item->status) }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('jmd.material-tests.form',[$project,$module,'test'=>$item->id]) }}">Buka</a></td></tr>@endforeach</tbody></table></div></div>@endif
@endsection
@push('scripts')
<script>
(() => {
 const body=document.getElementById('observation-rows');
 const reindex=()=>[...body.querySelectorAll('[data-row]')].forEach((row,index)=>{row.querySelector('.row-number').textContent=index+1;row.querySelectorAll('[name]').forEach(input=>input.name=input.name.replace(/observations\[\d+\]/,`observations[${index}]`));});
 document.getElementById('add-row').addEventListener('click',()=>{const source=body.querySelector('[data-row]:last-child');const row=source.cloneNode(true);row.querySelectorAll('input').forEach(input=>{if(input.type==='checkbox')input.checked=false;else input.value=input.dataset.checkboxHidden!==undefined?'0':'';});row.querySelectorAll('select').forEach(select=>select.selectedIndex=0);body.appendChild(row);reindex();});
 body.addEventListener('click',event=>{const button=event.target.closest('.remove-row');if(!button)return;if(body.querySelectorAll('[data-row]').length<=2){alert('Minimal dua observasi harus dipertahankan.');return;}button.closest('[data-row]').remove();reindex();});
})();
</script>
@endpush
